# Data

Data comprise the foundational components of stock assessment models. The decision to include or exclude particular data sources in an assessment model depends on many factors. These factors often include, but are not limited to, the way in which data were collected (e.g., measurement method and consistency); the spatial and temporal coverage of the data; the quantity of data available per desired sampling unit; the representativeness of the data to inform the modeled processes of importance; limitations imposed by the Pacific Fishery Management Council Groundfish Terms of Reference; and the presence of an avenue for the inclusion of the data in the assessment model. Attributes associated with a data source can change through time, as can the applicability of the data source when different modeling approaches are explored (e.g., stock structure or time-varying processes). Therefore, the specific data sources included or excluded from this assessment should not necessarily constrain the selection of data sources applicable to future stock assessments for `r spp`. Even if a data source is not directly used in the stock assessment they can provide valuable insights into biology, fishery behavior, or localized dynamics.

Data from a wide range of programs were available for possible inclusion in the current assessment model. Descriptions of each data source included in the model (Figure \@ref(fig:data-plot)) and sources that were explored but not included in the base model are provided below. In some cases, the inclusion of excluded data sources were explored through sensitivity analyses (see Section \@ref(assessment-model)).

## Data sources used in this assessment

This assessment uses data from the following sources, updating the data that were used in the 2015 benchmark assessment and the corrections to catch applied for the 2017 catch only update, as well as utilizing additional data that were collected since the last benchmark. Fishery data sources (including length composition, age composition, and catch time series) are split among three strata to make comparisons to and explorations from the 2015 benchmark assessment more direct, whereas abundance indices and corresponding length and age compositions from the fishery-independent surveys are combined across these strata to match the population scale reflected in the model. Each data source is summarized here, and then discussed in more detail below:

1.  Data regarding total removals of canary rockfish, from all fisheries and surveys, are compiled for years 1892-2022. These data are obtained from several sources:

a.  In California, landed recreational (1928--2022) and commercial (1916--2022) catches along with estimates of recreational dead discards come from multiple data sources including state reconstructions, \gls{calcom}, \gls{recfin}, and \gls{pacfin}. Historical recreational landings up to 1980 are based on those used in the previous benchmark assessment.
b.  In Oregon, landed recreational and commercial (1892--2022) catches along with estimates of recreational dead discards were provided directly by \gls{odfw} and come from multiple data sources including state reconstructions, \gls{pacfin}, and \gls{recfin}.
c.  In Washington, landed recreational catches (1967--2022) along with estimates of recreational releases were provided directly by \gls{wdfw}. Historical commercial landed catches (1935--1980) are based on those used in the previous assessment. Commercial landed catches from 1981--2022 are from \gls{pacfin}.
d.  Foreign trawl fleet catches from 1966--1976 are based on [@rogers_species_2003].
e.  Total removals of canary in the at sea hake fishery (1973--2022) were provided by the \gls{nwfsc} \gls{ashop}. 
f.  Total commercial discards for recent years (2003--2021) are estimated in the annual mortality report using data from a variety of sources including the West Coast Groundfish Observer Program, and are publicly available: <https://www.pcouncil.org/documents/2022/08/g-1-b-nwfsc-report-1-estimated-discard-and-catch-of-groundfish-species-in-the-2021-west-coast-fisheries.pdf/>. 
g.  Discard rates for 1981-1994 are obtained from the Pikitch study as analyzed by J. Wallace.

<!-- -->

2.  Fishery-independent data are included from three different surveys:

<!-- -->

a.  The \gls{s-tri} conducted by the Alaska Fisheries Science Center provides abundance index, length composition, and age-composition samples and was included for years 1980-2001.
b.  The \gls{s-wcgbts} conducted by the \gls{nwfsc} provides abundance index, length composition, and age-composition samples, and was available for years 2003-2022, with the exception of 2020 due to the COVID-19 pandemic.
c.  The pre-recruit survey, which combines data collected by the \gls{swfsc}, \gls{nwfsc}, and Pacific Whiting Conservation Cooperative provides a relative index of density for pre-recruit fish, and was included for most years from 2001-2022. Composition data are not used for this survey. 

<!-- -->

3.  Fishery-dependent composition data are included from the following sources:

<!-- -->

a.  Commercial length and age composition data were obtained from \gls{pacfin}.
b.  Recreational length and age composition data from state sampling programs or historical sampling efforts were either provided by the state agencies or were obtained from \gls{recfin}.
c.  Length and age data for canary rockfish from the at-sea hake fishery were obtained from the \gls{nwfsc} \gls{ashop}.

<!-- -->

4.  Estimates of life history parameters are generated from various sources, and include:

<!-- -->

a.  Updated maturity schedule from analyses based on functional age-at-maturity, which accounts for abortive maturation, wherein young spawners may have yolk present but are not yet spawning capable, and skip spawning, wherein mature individuals do not spawn in every year.
b.  Updated fecundity relationship based on a meta-analysis assuming fecundity is a power function of length.
c.  Updated prior for natural mortality rate along with updated treatment of mortality as age-invariant but sex dependent.
d.  Updated prior on steepness according to best practices.
e.  Updated weight-at-length relationship as estimated from the \gls{wcgbts}.
f.  Estimates of ageing error for break-and-burn ages were maintained from the previous benchmark assessment. 


*TO DO - add figure 3*

These data sources are illustrated in Figure 3.


## Data sources considered but not used


*We should specify what sources of data (catch, lengths, ages, indices) these refer to*
*Also possibly move to end of data section. Id prefer to say what we did first and what we didn't do later*


### California Collaborative Fisheries Research Program (CCRFP)

The \gls{ccfrp} has conducted fishery-independent data collection efforts onboard commercial passenger fishing vessels both inside and outside of MPAs between 2007 and present. Aspects of canary rockfish life history make the data set less than ideal. One important consideration is the limitation of sampling to less than 150 ft to minimize barotrauma for fish released by this hook and line survey, which limits access to the primary depth distribution of adult canary rockfish. In addition, until 2017 the sampling was focused on central California at the southern edge of the species range in California. While additional data has been collected subsequently to better represent the statewide abundance of groundfish stocks, the limited depths sampled and spatial limitations early in the survey further the utility and representativeness of the survey for this northernly distributed stock. Lastly, the high degree of vagility of canary rockfish makes accounting for MPA effects of lesser importance reducing the impetus to account for trends in closed areas for this species.

### Commercial Collection Report System

From 1977-1985 Commercial Collection Report System (CCRS) provided data on commercial passenger fishing vessels sampled at dockside. This study was very limited in spatial scale, focusing efforts on a limited portion of the species range in the Monterey Bay area representing only the southern end of the distribution of canary rockfish. In addition, this region is unique in providing access to deeper depths a short distance from shore along the sub-marine canyons of Monterey and Carmel Bays potentially biasing representation relative to the entire coast north of Point Conception within California where they are commonly found. Though 488 canary rockfish were sampled during the duration of the survey limited geographic representation at the southern edge of the species range and lack of representation from other ports with more distant grounds on the shelf/slope limits the utility of this data and comparability to other data sets.

### Historical CDFW Dockside Sampling

A dockside sampling effort was undertaken by CDFW during the 1950s-1970s to collect data from the private and rental boat and party charter fleets. Data collected from 1958 to 1972 from Miller and Gotshall 1965. Miller and Geibel 1973 and efforts were made to digitize data from sample sites in the Monterey Bay Area from Ano Nuevo to Point Sur. Over the course of the survey, 1032 canary rockfish lengths were collected from party boats and 461 from private boats. The limited geographic representation at the southern edge of the species range and lack of representation from other ports with more distant grounds on the shelf/slope limits the utility of this data and comparability to other data sets.

### Washington Sport Dockside interview data

The WDFW provided recreational dockside fisheries data from 1981 through 2022 for consideration in this assessment. Data were collected at the trip level, with the number of landed fish and the number of anglers on each vessel being recorded. The amount of time fished by each angler was not recorded. The recreational dockside data was considered for use in this assessment, however, management measures implemented over the past several decades impeded extracting a reliable signal for use as abundance indices. In 2003, management restricted summer fishing depths to shallower than 20-fathoms in WDFW marine areas 3 and 4, and in 2006 modified this depth restriction to 30-fathoms in marine areas 2, 3, and 4. Additionally, daily rockfish limits were 15 fish from 1981-1991, 12 fish from 1992-1994 (except in area 1 where it remained at 15), 10 fish from 1995-2016, and a reduction to 7 fish from 2017-2022. The effects of these management changes to CPUE of canary rockfish could not be reconciled with changes in the abundance indices and therefore this dataset was not used in this assessment.

### Washington nearshore rod-and-reel survey

Fishery-independent data available for this assessment came from two distinct WDFW research projects. The first was the Rockfish Tagging Program that was initiated in the early 2010s primarily off the central coast of Washington with sparse coverage in the northern and southern coast. The second data set was from the standardized Coastwide Rod-and-Reel Survey that began in 2019. The tagging program had strong focus on black rockfish and had little information for canary. The new nearshore survey was impacted by the COVID pandemic and was not completed as originally designed. Due to their short time spans and spatial coverage limited to Washington waters, these two datasets are not used in this assessment.

### Oregon indices

Two indices of relative abundance were developed for canary rockfish in Oregon using the sdmTMB package, but ultimately not included in the base model.  Given the period of non-retention for canary rockfish, the only viable fishery-dependent index was based on onboard sampling of charter vessels that includes both retained and released fish.  Additionally, a second index from Oregon’s marine reserve hook and line survey was also developed.