## Total removals

Removals (1892-2022) for canary rockfish were compiled from multiple data sources. This assessment includes total removals (landings plus dead discards) by state for the following fleets: trawl, non-trawl, recreational, foreign trawl, and at-sea hake. A summary of total removals are provided in Table 5, Table 6, and Figure 2.

<!-- ## Fishery-Dependent Data -->

<!-- Commercial landings of rockfish and the biological characteristics of these landings were not consistently sampled for scientific purposes until the early 1960s (Niska, 1976). Statewide sampling programs to determine species compositions of the landed catches began in the late 1960s. The first rigorous monitoring programs that included routine collection of biological data (e.g., sex, age, size, maturity states, etc.) were begun in 1980. Currently, port biologists employed by each state fishery agency (\gls{cdfw}, \gls{odfw}, \gls{wdfw}) collect species-composition information and biological data from the landed catches of commercial trawling vessels that have completed their fishing trips. The sampling sites are commonly processing facilities located at ports along the coasts of California, Oregon and Washington. The monitoring programs currently in place are generally based on stratified, multistage sampling designs. -->

<!-- Commercial length-frequency distributions were developed for each fleet for which observations were available, following the same bin structure as was used for research observations. For each fleet, the raw observations (compiled from \gls{pacfin}) were expanded to the sample level, to allow for any fish that were not measured, then to the trip level to account for the relative size of the landing from which the sample was obtained. These expanded length observations were then combined within years for each fleet. Age frequencies were computed in the same manner. Sampling statistics for each fleet and year are given in , and clearly show the different sampling targets employed over different time periods and between state agencies. -->

<!-- The weighted length-frequency distributions are shown in . The annual observations were recorded as unidentified sex; both sexes were combined and are treated as such in the model. By fleet, a number of important patterns are visible in the data. The trawl fleets for each state, although the data are noisy, appear to show a decline in mean length of the catch from 1978 to 2000 (figures), with an increase in the mean length for recent years of the landed catch. The length composition data from the non-trawl fleet are much sparser compared to the trawl fleet making it difficult to discern a pattern in the mean length landed (Figures). The at-sea hake fishery was comprised of larger lengths relative to the trawl fishery, with the majority of length samples from Washington (Figures). All three recreational fleets appear to generally target smaller fish relative to the other fleets (Figures). -->

<!-- Marginal commercial age-frequency distributions were compiled and are presented in FIGURES. Age composition samples are expanded similarly to the commercial length samples (i.e., first by sample, and then by trip). We expand age composition samples independently for each state, and also separately for three age determination categories: (1) ages read by using break-and-burn methods by \gls{odfw} or CAPS, (2) ages read by break-and-burn methods by \gls{wdfw}, and (3) ages read using surface methods by any lab. Age data for California were very sparse (no data between 1986 and 2000), but the majority of observed fish being younger than age 19 in recent years (Figure 24). Age compositions for the Oregon trawl fleet show a clear decline in both males and females older than \~ age 20 from the mid-1980s to recent years (Figure 25). In Washington, although missing age data from much of the time-series, there are larger proportions of older ages compared to the other two states (Figure 26). Age data for the non-trawl fleet for all states is sparse enough that little pattern can reliably be discerned (Figure 27-Figure 29). Age data from the at-sea hake fishery was available for 2003-2013 and shows little pattern. Washington is the only state with age data from the recreational fleets, and these data show a larger portion of the sample fish being less than 10 years of age (Figure 33). -->

<!-- In aggregate, the biological data from fishery sources shows no evidence of strong year-classes moving through the population. This could be due to low recruitment variability, noisy data, or both. Further, declines in mean size and age seem to show a latitudinal cline, with more extreme declines to the south, and limited declines observed in Washington and Oregon. -->

### Commercial landings by State

#### Washington

Commercial landings data in Washington were available from 1935--2022. Historical landings (1935--1980) were retained from the last full assessment where they were assumed to be for trawl gears [see @stewart2007canary and @thorson_status_2015 for additional details]. Recent landings (1981--2022) for the trawl and non-trawl (mainly hook and line) gears were obtained from \gls{pacfin}, the central repository for West coast commercial landings (extracted on 03/23/2023, Pacific States Marine Fisheries Commission, Portland, Oregon; www.psmfc.org).

#### Oregon

Commercial landings data in Oregon were available from 1892--2022. Historical landings from 1892 to 1986 were provided by \gls{odfw} [@karnowski_historical_2014]. Landings in 1987--1999 were compiled from a combination of \gls{pacfin}, (extracted on 03/23/2023), and a separate \gls{odfw} reconstruction that delineated canary rockfish-specific landings among unspecified species categories within \gls{pacfin} [e.g. URCK and POP1, @odfw2017informational]. Canary rockfish landings from this reconstruction were substituted for the URCK and POP1 landings available from \gls{pacfin} and added to \gls{pacfin} landings from other categories for a complete time series of canary rockfish during this time period. Commercial landings in 2000--2022 were available on \gls{pacfin} (extracted on 03/23/2023).

#### California

Commercial landings data in California were available from 1916--2022. Historical landings from 1916 to 1980 were obtained following the process described in the southern California vermilion rockfish (*Sebastes miniatus*) assessment [see @dick2021vermillion for complete details]. Briefly, landings 1916--1968 came from a state reconstruction [@ralston_documentation_2010]. Landings from unknown gears in known regions were allocated proportional to landings from known gears within the same region for each year. Landings from unknown locations (Region 0) and unknown gears were allocated proportional to the landings from known gears across all known locations for each year. Landings from 1969--1980 came from \gls{calcom}, which for 1969--1977 incorporates fish ticket data including mixed species categories for rockfish that were assigned to individual species using the earliest species composition samples (from the late 1970s and ealy 1980s). Recent (1981--2022) landings by trawl and non-trawl gears were obtained from \gls{pacfin} (extracted on 03/23/2023).

Additional catches caught off the coast of Oregon or Washington but landed in California from 1948-1968 were included, as these were not incorporated within the [@ralston_documentation_2010] reconstruction (E. Dick, personal communication, 3/16/23). These final landings are in the California landings history for consistency with treatment for other states, because historical catches landed in Oregon or Washington but caught in the other state's waters are similarly attributed to the state where they were landed. 

### Commercial Discards

Estimates of dead discards were combined with landed catch to provide estimates of total removals that were used as input catches within the Stock Synthesis model (Table 8). In recent years (2000--2022), estimates of dead discards were calculated from discard data, but in earlier years (before 2000), estimates of dead discards were calculated based on assumed discard ratios. 

The ratio of discarded weight to landed weight (here termed the "discard ratio") for the domestic trawl and non-trawl fisheries was assumed at the following values: 1% discard ratio for 1892--1980, based on the assumption that discard rates were low prior to management actions due to the high-value nature of the fishery [and consistent with the previous assessment, @thorson_status_2015]; 5% discard ratio for 1981--1994 which is approximately the value calculated by J. Wallace, NMFS using data from @pikitch_evaluation_1988; 20% discard ratio for 1995--1999, based on the assumption that discard ratios would be higher than previous years but less than years when discard data was present due to the period of non-retention [and consistent with the previous assessment, @thorson_status_2015].  

Onboard observers were deployed on fishing vessels starting in 2002 to collect data on discarding practices. Discard amounts for the domestic trawl, non-trawl, and at-sea hake fisheries from 2002--2021 were determined based on \gls{wcgop} data provided in the \gls{gemm} product (TO DO: cite GEMM). The \gls{gemm} provides estimates of dead discards coastwide. Therefore, the total coastwide estimates of dead discards in trawl and fixed gears as provided in the \gls{gemm} were allocated by state based on the total observed landings and discards for each state as observed by \gls{wcgop}. Dead discards were added to landings to obtain total removals for 2002--2021. Total removals in 2000, 2001, and 2022 where no \gls{wcgop} data were available were calculated by applying the average discard ratios from 2002--2004 (for estimates in 2000 and 2001) and 2019--2021 (for estimates in 2022) for each gear to landings for that gear. 


### Recreational landings and discards by state

#### Washington

Washington recreational landings, in number of fish retained, were provided by \gls{wdfw} for 1967 and 1975--2022. Landings estimates starting in 1990 were reworked by the \gls{wdfw} sport sampling unit since the previous assessment. For 1968--1974, a linear ramp between the values in 1967 and 1975 was used to approximate landings. Similarly, a linear ramp between values in 1986 and 1990 was used to approximate landings from 1987--1989, which were also unavailable. Recreational landings were assumed zero prior to 1967.

Discard estimates for 2002--2022, in numbers of fish released were also provided by \gls{wdfw}, with numbers released in specific depth categories available from 2005--2022. Released fish at unknown depths were allocated proportional to released fish at known depths in years with depth specific values. For 2002--2004, which had no depth-specific information, the average total release mortality rate in 2005--2007 was used to calculate the number of dead discards. Depth-specific release-mortality rates were based on agreed upon values for canary rockfish [Table 1-10; @pfmc2014status]. 

The total discard mortality rate (release rate multiplied by release mortality rate) for 2002 was also applied to 2000--2001 landings. All three years shared a two canary daily bag limit, and were assumed to have similar discarding practices. We assumed zero recreational releases prior to 2000 when canary rockfish was included as part of a ten rockfish daily limit, and release rates were generally low (P. Anderson, personal communication, 03/20/23).

Total removals in the Washington recreational fleet were converted from numbers to weight to maintain consistency with units from other fleets. Length data for sport catches were provided by \gls{wdfw} for 1979--2022. The average length of canary rockfish by year was calculated and converted to average weight based on parameters of the length-weight relationship ($\alpha$ = 1.040E-05 and $\beta$ = 3.084 for length in cm and weight in kg) as used in \gls{recfin}. In years where the number of length samples was fewer than 25, lengths were borrowed from the nearest neighboring years to calculate a three year weighted-average. A value of 25 was used because it was the 'small sample size' threshold used by @dick_lengthborrow_2021 and had increased percent standard error compared to other sample sizes. Borrowing lengths from neighboring years was only applied from years with roughly similar fishing regulations. Thus, lengths were only calculated from neighboring years in the periods <1999 (canary rockfish part of group daily bag limits), 2000--2003 (canary rockfish with individual daily bag limits), 2004--2016 (period of no retention), and 2017--2022 (post non-retention). Any years without lengths were assigned the non-weighted-average length across years within a  period. A non-weighted length was applied to give each year equal weight in calculating an overall average for each period.      


#### Oregon

##### Historic Ocean Boat Landings and Discards (1979--2000)

Recently, \gls{odfw} undertook an effort to comprehensively reconstruct all marine fish recreational ocean boat landings prior to 2001 [@whitman2023, in review]. Reconstructed catch estimates from the \gls{orbs} improve upon estimates from the federal \gls{mrfss}, which have known biases related to effort estimation and sampling [@vanvoorhees2000] that resulted in catch estimates considered implausible by \gls{odfw}. However, the \gls{orbs} sample estimates are known to lack the comprehensive spatial and temporal coverage of \gls{mrfss} Addressing this coverage issue is a major part of this reconstruction. In general, the base data and methodology for these reconstructed estimates are consistent with recent assessments for other nearshore species [@cope2021vermillion_or; @langseth2021quillback_or; @taylor2021lingcod_n; @wetzel2021copper_or].

Prior to 2001, \gls{orbs} monitored marine species in both multi-species categories, such as rockfish, flatfish, and other miscellaneous fishes, and individual species, such as lingcod or halibut. For this comprehensive reconstruction, four species categories were selected to reconstruct, including rockfish, lingcod, flatfish and miscellaneous, which constitute the bulk of the managed marine fish species. Canary rockfish are a component of the rockfish species category.

Category-level estimates were expanded to account for gaps in sampling coverage in two separate pathways. First, estimates from five major ports were expanded to include unsampled winter months in years lacking complete coverage. Expansions were based on available year-round sampling data and excluded years where regulations may have impacted the temporal distribution of catch. Second, all other minor port estimates were expanded to include seasonal estimates in years lacking any sampling based on the amount of minor port catch as compared to all major port estimates. A subset of landings were sampled by ORBS for species compositions within these categories. Once category-level landings were comprehensive in space and time, species compositions were applied for the three multi-species categories, including rockfish, flatfish and miscellaneous fish. Borrowing rules for species compositions were specific to the category and determined based on a series of regression tree analyses that detailed the importance of each domain (year, month, port and fishing mode) to variability in compositions.

Ocean boat estimates 1979--2000 in numbers of fish of canary rockfish from the above described methods were converted to biomass using biological samples from MRFSS (A. Whitman, ODFW, personal communication, 2023). \Gls{mrfss} biological data are available 1980--1989 and 1993--2000. An annual average weight was applied to the total annual number of fish to obtain an annual biomass estimate of the landings. Several years of missing biological data (1979, 1990--1992) were filled in using neighboring years or interpolation. Landings from 1979 to 2000 averaged 29.9 mt and are of similar magnitude to the previous assessment, though landings appear to have less interannual variability than the previous assessment [@thorson_status_2015]. Landings were relatively high in the first year of available data (1979) and so landings from 1972 to 1978 were initiated at zero in 1972 and linearly ramped up to the value in 1979. The provided landings do not include an estimate of discarded fish, and thus are assumed as total removals. Bag limits in the recreational fishery during this time period (prior to 2001) were generally liberal and \gls{odfw} staff recommended that no additional mortality of discarded fish be included prior to 2001.

##### Modern Ocean Boat Landings and Discards (2001 -- 2022)

Recreational landings for ocean boat modes from 2001--2022 are available from \gls{recfin}. Both retained and released estimates of mortality are included, though retained mortality contributes the vast majority to total mortality in years outside the overfished designation for canary rockfish. Release mortality is estimated from angler-reported release rates and the application of discard mortality rates from the PFMC [@pfmc2014status]. The average proportion of canary rockfish discarded averaged 4.5% in 2001--2003 and 2017--2022. During years where canary rockfish retention was prohibited, discard rates increased to 96.1% on average (2004--2016). From 2001 to 2022, total landings averaged 16.0 mt, ranging from 1.7 to 60.6 mt. In 2022, estimated ocean boat landings were 55.7 mt.

#### California

Recreational landings in California were available from 1928--2022. Historical estimates of recreational landings 1928--1979 were obtained from the previous assessment [@thorson_status_2015], which were in turn were obtained from \gls{calcom}. For years since 1979, recreational landings along with estimates of dead discards came from \gls{recfin} via \gls{mrfss} (1980--2003) and \gls{crfs} (2005--2022) sampling programs. Landings and dead discards were added together to obtain estimates of total removals. Discards prior to 1980 were assumed to be zero.

A number of years with missing or incomplete estimates for recreational removals were filled in. The removals in 1980 from \gls{mrfss} were not used due to survey quality problems related to 1980 being the first year of \gls{mrfss} [@Karpov1995, @cope_status_2009]. Removals for this year were averaged across removals in 1979 and 1981. No or minimal party/charter (PC) estimates were available from 1993--1995, so PC mode removals for these years were calculated assuming an average ratio of private/rental (PR) to PC modes across all years with data within \gls{mrfss} and added to PR values to obtain total recreational estimates. The \gls{mrfss} sampling program did not sample from 1990--1992, and so estimates during these three years were obtained as averages from neighboring years. Estimates in 1990 were the average from 1987--1989, estimates in 1991 were the average from 1987--1989 and 1993--1995, and estimates in 1992 were the average from 1993-1995. Because of the transition from \gls{mrfss} to \gls{crfs}, no estimate was available in either database in 2004 for this assessment cycle. \Gls{cdfw} provided a value of 10.59 mt for 2004 (J. Budrick, CDFW, personal communication), based on an available previous pull of \gls{mrfss} data for the gopher rockfish assessment. Estimates for California recreational removals from the previous canary rockfish assessment were not used because these appeared to only reflect estimates of landings, and not total removals. 

##### CA Recreational data impacted by COVID-19 pandemic

The COVID-19 pandemic impacted recreational port sampling in 2020 and 2021. No sampling occurred at all in April-June, 2020. \Gls{cdfw} provided proxy values for these months (M. Parker, CDFW, personal communication). In addition, California recreational total mortality estimates in the "rockfish genus" were inflated due to \gls{crfs} samplers being unable to closely examine catch and identify catch to species. This was a problem for both PR and PC modes in 2020 and primarily for the PC mode in 2021. An effort was made to allocate some of the rockfish genus mortality to other rockfish species for these modes and years (J. Coates, CDFW, personal communication). An expected value of rockfish genus mortality in 2020 and 2021 was generated by mode and year according to the average proportion to the total rockfish mortality that this category represented in 2018 and 2019, when regulations were consistent with 2020 and 2021. Mortality above this expected value was attributed to the other species also based on proportions each species represented to the total from 2018 and 2019. Calculations were made by year, mode, and district. The shore-based modes were grouped in with the PR mode. Calculations were initially made in numbers of fish because rockfish genus mortality is only recorded this way. Numbers of fish by species were then converted to weight in kilograms based on average weights of fish recorded by the \gls{crfs} program by district in 2019. Total proxy values in for canary rockfish weight were summed across modes and districts and added to existing estimates for 2020 and 2021 from \gls{recfin}.


<!-- #### Length Compositions -->

<!-- California: -->

<!-- Recreational length-frequency distributions were compiled from data available through RecFIN for California, while data were obtained from Oregon (A. Dauble, personal communication) and Washington (P. Weyland, personal communication). Age-frequencies were only available for Washington (P. Weyland, personal -->

<!-- Recreational length samples were obtained from two primary sources: MRFSS and RecFIN (ORBS). ODFW special project sampling data were considered but given the high sample sizes available from standard sampling, these data were not utilized. From 1980 -- 1989 and from 1993 -- 2000, the MRFSS program collected samples from both ocean and inland (estuary) areas (n = 46,656). ODFW provided MRFSS samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values (n = 7,176). From 1980 -- 1989, total lengths (mm) were collected by MRFSS, which were converted to fork length. From 1993 -- 2000, fork length (mm) was collected. Length samples from 2001 -- 2022 from the ORBS sampling program are available on RecFIN (n = 27,135). All ORBS samples are by fork length (mm). The vast majority (99.4%) of these samples are from ocean trips (n = 26,985). Table X details sample sizes by year and recreational fleet. -->

<!-- #### Washington -->

<!-- Length compositions were provided by \gls{wdfw}, as well. At least one sample is available from 1981-1983, 1987, 1995-1998, and 2002-2022. -->

<!-- Washington sport catches were available in numbers of fish. We converted numbers of fish to biomass using length composition data from WDFW. BRIAN HOW DID YOU DO THIS? We used the applicable \gls{recfin} length-weight relationship of $W = aL^b$ where $a = 1.04058\text{E}-08$ and $b = 3.084136662$. -->

<!-- #### Oregon -->

<!-- ##### Length compositions -->

<!-- Recreational length samples were obtained from two primary sources: \gls{mrfss} and \gls{recfin} (\gls{orbs}). \Gls{odfw} special project sampling data were considered but given the high sample sizes available from standard sampling, these data were not utilized. From 1980 -- 1989 and from 1993 -- 2000, the \gls{mrfss} program collected samples from both ocean and inland (estuary) areas (n = 46,656). \Gls{odfw} provided \gls{mrfss} samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values (n = 7,176). From 1980 -- 1989, total lengths (mm) were collected by \gls{mrfss}, which were converted to fork length. From 1993 -- 2000, fork length (mm) was collected. Length samples from 2001 -- 2022 from the \gls{orbs} sampling program are available on \gls{recfin} (n = 27,135). All \gls{orbs} samples are by fork length (mm). The vast majority (99.4%) of these samples are from ocean trips (n = 26,985). Table X details sample sizes by year and recreational fleet. -->

<!-- #### California -->

<!-- ### At Sea Hake Fishery -->

<!-- Catches of canary rockfish are monitored aboard the vessel by observers in the At-Sea hake Observer program (ASHOP) and were available for the years of 1975-2014. Observers use a spatial sample design, based on weight, to randomly choose a portion of the haul to sample for species composition. For the last decade, this is typically 30-50% of the total weight. The total weight of the sample is determined by all catch passing over a flow scale. All species other than hake are removed and weighed, by species, on a motion compensated flatbed scale. Observers record the weights of all non-hake species. Non-hake species total weights are expanded in the database by using the proportion of the haul sampled to the total weight of the haul. The catches of non-hake species in unsampled hauls is determined using bycatch rates determined from sampled hauls. Since 2001, more than 97% of the hauls have been observed and sampled. -->

### Foreign Catches

From the 1960s through the early 1970s, foreign trawling enterprises harvested considerable amounts of rockfish off Washington and Oregon, including large quantities of canary rockfish. Foreign catches of individual species were estimated by @rogers_species_2003 and attributed to \gls{inpfc} areas from 1966-1976 for canary rockfish. \Gls{inpfc} areas do not coincide with the spatial strata defined in this assessment. Therefore, INPFC catches were translated to strata in the following manner: catches from the US Vancouver INPFC area were designated to the 46-49°N stratum (Washington), catches in the Columbia INPFC area were allocated to the 42-46°N stratum (Oregon), and catches from the Eureka and Monterey INPFC areas were assigned to the 32-42°N stratum (California). These definitions match where the majority of commercial trawl landings occur by state for each INPFC area within  \gls{pacfin}.


<!-- ### Expansion of length and age-composition samplmes -->

<!-- Twenty-eight bins from 12 to 66 cm were used to summarize the length frequency of the survey catches in each year, the first bin including all observations less than 12 cm and the last bin including all fish larger than 66 cm. For the length-composition samples from the WCGBTS, these bins are populated with a modest, but consistent degree of sampling: 32-75 tows and 423-1467 fish per year (Table 1). The Triennial survey (Table 2) has a similar number of tows per year (13-95) but considerably larger numbers of fish per year (407-3119). Input sample sizes for length-composition data are calculated using the same formula as was used in the 2007 benchmark assessment. In summary, this method was based on analysis of the input and model-derived effective sample sizes from stock assessments completed in 2005 for west coast groundfish. It makes the input sample size a function of both the number of fish sampled and the number of trips or hauls sampled. A piece-wise linear regression was used to estimate the increase in effective sample size per sample based on fish-per-sample and the maximum effective sample size for large numbers of individual fish: -->

<!-- *INSERT EQUATION HERE* -->

<!-- These values are likely to represent a reasonable starting point that generally reflects the degree of observation error commensurate with sampling a given number of fish from a given number of samples. They were used most recently in the 2013 darkblotched rockfish benchmark assessment (Gertseva and Thorson, 2013). -->

<!-- Age-frequency data from the Triennial and WCGBT surveys were compiled as conditional age-at-length distributions by sex and year. Individual length- and age-observations can be thought of as entries in an age-length key (matrix), with age across the columns and length down the rows. The approach consists of tabulating the sums within rows as the standard length-frequency distribution and, instead of also tabulating the sums to the age margin, instead the distribution of ages in each row of the age-length key is treated as a separate observation, conditioned on the row (length) from which it came. This approach has several benefits for analysis above the standard use of marginal age compositions. First, age structures are generally collected as a subset of the fish that have been measured. If the ages are to be used to create an external age-length key to transform the lengths to ages, then the uncertainty due to sampling and missing data in the key are not included in the resulting age-compositions used in the stock assessment. If the marginal age compositions are used with the length compositions in the assessment, the information content on sex-ratio and year class strength is largely double-counted as the same fish are contributing to likelihood components that are assumed to be independent. Using conditional age-distributions for each length bin allows only the additional information provided by the limited age data (relative to the generally far more numerous length observations) to be captured, without creating a 'double-counting' of the data in the total likelihood. The second major benefit to using conditional age-composition observations is that in addition to being able to estimate the basic growth parameters (L age-1, L age-30, K) inside the assessment model, the distribution of lengths at a given age, usually governed by two parameters; the CV of length at some young age and the CV at a much older age, are also quite reliably estimated. This information could only be derived from marginal age-composition observations where very strong and well-separated cohorts existed, that were quite accurately aged and measured; rare conditions at best. By fully estimating the growth specifications within the stock assessment model, this major source of uncertainty is included in the assessment results, and bias due to size-based selectivity is avoided. Therefore, to retain objective weighting of the length and age data, and to fully include the uncertainty in growth parameters (and avoid potential bias due to external estimation where size-based selectivity is operating) conditional age at-length compositions were developed for the triennial and WCGBT survey data. -->

<!-- Age distributions included 35 bins from age 1 to age 35, with the last bin including all fish of greater age. Input sample sizes were fixed at the number of unique fish within a given length bin. The age samples consists of approximately one-quarter as many fish, as the samples for length (Table 3 and Table 4). These distributions show a tight range of ages at a given length, and clearly show the growth trajectory of females reaching larger sizes than males for a given age. It is often useful for interpretation to compute the marginal age-compositions, and include these in the assessment model (with the likelihood contribution turned off, so they do not affect model fit in any way) for comparison of the 'implied' fit to the margin of the age-length key. Although these NWFSC age distributions seem to show some diagonal structure, close inspection reveals that it does not track consistently through any of the recent cohorts. This time series is short, and does not encompass the period when substantial reductions in the canary population occurred, and so may be relatively uninformative in the assessment model, except for estimation of growth parameters. -->
