## Composition data

Commercial landings of rockfish and the biological characteristics of these landings were not consistently sampled for scientific purposes until the early 1960s (Niska, 1976). Statewide sampling programs to determine species compositions of the landed catches began in the late 1960s. The first rigorous monitoring programs that included routine collection of biological data (e.g., sex, age, size, maturity states, etc.) were begun in 1980. Currently, port biologists employed by each state fishery agency (\gls{cdfw}, \gls{odfw}, \gls{wdfw}) collect species-composition information and biological data from the landed catches of commercial vessels that have completed their fishing trips. The sampling sites are commonly processing facilities located at ports along the coasts of California, Oregon and Washington. The monitoring programs currently in place are generally based on stratified, multistage sampling designs.

Recreational landings of rockfish and the biological characteristics of these landings were not consistently sampled for scientific purposes until the late 1970s. The first rigorous monitoring programs that included routine collection of biological data (e.g., sex, age, size, maturity states, etc.) were begun in 1980 by the national MRFSS program and state sampling programs. Currently, port biologists employed by each state fishery management agency (\gls{cdfw}, \gls{odfw}, \gls{wdfw}) collect catch, effort, and biological data from the landed catches of recreational vessels that have completed their fishing trips. Onboard sampling also occurs but is generally associated with charter vessels. 

Twenty-eight bins from 12 to 66 cm were used to summarize the length frequency distributions of fishery-dependent and fishery-independent sources of catch. The first bin includes all observations less than 12 cm and the last bin includes all fish larger than 66 cm. Thirty-five bins from age 1 to age 35 were used to summarize the age frequency distributions of fishery-dependent sources of catch, with the last bin including all fish aged greater than 35 years. Conditional age at length data was used to summarize fishery-independent sources of age data, and is described in more detailed in Section \@ref(TO DO: add section here).
**Fix reference to section above**


### Fishery-Dependent Composition Data

#### Commercial trawl and non-trawl fisheries

Length- and marginal age-frequency distributions were calculated for each commercial fleet for which observations were available. Biological length and age data were extracted from the \gls{pacfin} Biological Data System on May 8, 2023. Biological data were divided into trawl and nontrawl fleets for each state according to the fleet structure used for this assessment. Length samples were available starting in 1977 for California fleets, 1973 for Oregon fleets, and 1968 for Washington fleets. Age samples were available starting in 1980 for all states' fleets. There was a mix of biological length and age samples with and without sex information but the majority of length and nearly all age samples included information on sex, so were modelled as sex specific compositions. 

During data exploration it was noted that samples previously labelled as special project samples from Oregon were appropriate to represent dynamics from the fishery. The majority of these occurred during 1973--1986, and therefore 5,859 special project samples from Oregon up through 1986 were retained for composition data. Also during data exploration, there were 700 age samples from Washington without a final age determination. These represented a small proportion of samples among the years which they occurred and so were excluded.

*TO DO: DO surface read sensitivity or exclude the text below about doing it*
Among age samples, 6,645 were from surface reads, starting in 1973 for Oregon and 1975 for Washington. Ages of surface reads were truncated to around 30 prior to 1980, and were more similar to break and burn reads when both were available starting in 1980. Given known biases of surface reads, and the clear truncation in years where only surface years were available, we excluded surface reads from age compositions. A sensitivity to the presence of surface read showed negligible effect on model results (see Section \@ref(sensitivities)). 

For commercial trawl and nontrawl fleets, the raw observations (compiled from \gls{pacfin}) were expanded to the sample level, to allow for any fish that were not measured, then to the trip level to account for the relative size of the landing from which the sample was obtained. These expanded length and age observations were then combined within a year for each fleet.

The input sample sizes for the expanded commercial length and age data were calculated via the Stewart method (Ian Stewart, personal communication) which incorporates the number of trips or hauls and fish by year:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

The magnitude of sampling for each fleet and year are given in Table \@ref{tab:comm-sample-lengths} and Table \@ref{tab:comm-sample-age}, which shows the different magnitudes of sampling across time and between state agencies. Thess tables show both the total number of fish samples as well as the number of trips by year and state over which samples were obtained. 

During modeling we noticed sparse length and age composition data of unsexed fish for a few years across fleets. Years with very few unsexed length and age samples relative to sexed samples were excluded from the model. See [Appendix A](#excluded-data) for implied fits to these length and age data.
*We may not even need implied fits to these. A sensitivity would be to remove anything less than a certain number, whether sexed or unsexed*

**Many assessment include actual lengths. Could add in like I did for rec fleets**
The weighted commercial length-frequency distributions are shown in (Figures \ref{fig:CA_twl_lencomp}-\ref{fig:WA_ntwl_lencomp}). A number of important patterns are visible in the data although the data are noise. The trawl fleets appear to show a decline in mean length of the catch from 1978 to 1990 for California and from around 1980 to 2000 for Oregon (Figures \ref{fig:CA_twl_lencomp} and \ref{fig:OR_twl_lencomp}), with variable length since 2000 and some increase from around 2013 for the Oregon and Washington trawl fleets (Figures \ref{fig:OR_twl_lencomp} and \ref{fig:WA_twl_lencomp}). The length-frequency distributions from the non-trawl fleet are much more sparse compared to the trawl fleet, especially during the period of no retention where no lengths were sampled, making it difficult to discern a pattern in the mean length landed (Figures \ref{fig:CA_ntwl_lencomp}-\ref{fig:WA_ntwl_lencomp}). However, Oregon non-trawl lengths show some decline during the 1990s and Oregon and California non-trawl lengths show increases in the most recent years, though these can also be explained by changes in regulations for `r spp` in recent years. 

**Many assessment include actual ages. Could add in like I did for rec fleets**
The weighted marginal commercial age-frequency distributions are shown in (Figures \ref{fig:CA_twl_agecomp}-\ref{fig:WA_ntwl_agecomp}). Age data for California were very sparse (no data between 1987 and 2001 as well as after 2009) compared to age data from Oregon and Washington (Figure \ref{fig:CA_twl_agecomp}). Age compositions for the trawl fleets were generally similar, ranging from approximately 5 to 25 years, with peaks at 10 years of age for both sexes. Oregon trawl fleet show a clear decline from around age 20 from the mid-1980s to around age 10 in 2000, with periods of increases each decade since 2000 (Figure \ref{fig:OR_twl_agecomp}). Washington age data show highly variable patterns that make general patterns difficult to determine Figure \ref{fig:WA_twl_agecomp}. Age data for the non-trawl fleet for all states are sparse enough that no pattern can reliably be discerned (Figures Figure \ref{fig:CA_ntwl_agecomp}-\ref{fig:WA_ntwl_agecomp}) though the distribution of ages in Washington is shifted towards older `r spp` compared to other states' non-trawl and trawl fisheries. 
  
#### At-Sea-Hake fishery 

Length- and marginal age-frequency distributions were calculated for the at-sea-hake fishery using data collected by the \gls{nwfsc} \gls{ashop} (extracted on 3/31/23 for lengths and 5/1/2023 for ages). Length and age observations were available starting in 2003, which was after the period that at sea processing was restricted to north of 42$^\circ N$. Consequently, length and age compositions were only available only for Oregon and Washington components of the at sea hake fishery. Raw observations were aggregated within a year for each fleet, and the input sample sizes for composition data was the number of hauls. 

The magnitude of sampling for the at-sea-hake fishery is given in Table \@ref{tab:ashop-sample-lengths} and Table \@ref{tab:ashop-sample-age}. These tables show both the total number of fish samples as well as the number of trips by year and state over which samples were obtained and which were used as input sample sizes. During modeling we noticed sparse length and age composition data of unsexed fish for a few years across fleets. Years with very few unsexed length and age samples relative to sexed samples were excluded from the model. See [Appendix A](#excluded-data) for implied fits to these length and age data.

**Many assessment include actual ages. Could add in like I did for rec fleets**
The at-sea hake fishery was comprised of similarly sized `r spp` relative to the commercial trawl fisheries and exhibited little trend over time (Figures \ref{fig:OR_hake_lencomp}-\ref{fig:WA_hake_lencomp}). Age data were also comparable to ages from the commercial trawl fisheries and show little discernible pattern over time (Figures \ref{fig:OR_hake_agecomp}-\ref{fig:WA_hake_agecomp}). 


#### Foreign fishery

No length or age data were available from foreign fleets. Selectivity of these fleets was assumed to be the same as the state specific trawl fisheries.


#### Recreational fishery

Length- and marginal age-frequency distributions were calculated for each recreational fleet for which observations were available. Biological length and age composition data were extracted from various sources. For Washington, biological samples starting in 1979 (for lengths) were obtained from sport biodata as provided by \gls{wdfw} on April 27, 2023. Age samples began in 2004. For Oregon, biological samples starting in 1980 (for lengths) were obtained from \gls{odfw} via the \gls{mrfss} and \gls{orbs} sampling programs as accessed via \gls{recfin} on January 25, 2023 for lengths and April 28, 2023 for ages. Age samples began in 1999. For California, length samples 1980--2003 were obtained via the \gls{mrfss} sampling program as accessed via \gls{recfin} (accessed March 30, 2023) and provided by \gls{cdfw}. Length samples starting in 2003 were obtained via the \gls{crfs} sampling program as accessed via the \gls{recfin} website (accessed April 14, 2023). Length samples collected from the Deb Wilson-Vandenberg onboard CPFV survey for 1987--1998 were also obtained from \gls{cdfw}. California has no age samples of `r spp`.  

Between 1987-1989 and 1993-1998 there were recreational length data for the CPFV fleet from both MRFSS and the Deb Wilson-Vandenberg data sets. During data exploration it was determined that the lengths in MRFSS from 1997 and 1998 were also included in the Deb Wilson-Vandenberg data, indicating that these data sources were duplicated for these years but also potentially other years where they overlapped. In order to avoid duplicate data, the length data from \gls{mrfss} for private/charter mode, which had far fewer length samples for the overlapping years with Deb Wilson-Vandenberg for the CPFV fleet, were removed from the data used within the model. A sensitivity was run using only the \gls{mrfss} data to test the effect of this choice (see Section \@ref(sensitivities)).

Biological length data were aggregated across party/charter and private/rental mode based on similarity in the overall length distributions, and consistent with past canary rockfish assessments. There was a mix of biological length and age samples with and without sex information. The majority of length samples for Washington and Oregon, and all length samples for California did not include information on sex. The majority of age samples included information on sex, so were modeled as sex-specific age distributions. Only lengths from retained fish were used as were samples from ocean areas. In addition, \gls{odfw} provided \gls{mrfss} length samples with the addition of a column that flagged length values imputed from weights to allow for selection of directly measured values. A sensitivty to using lengths from both retained and released fish was explored and described in Section \@ref(sensitivities). Altogether there were very limited number of samples from inland/estuary areas and from which direct measurements were not available so no sensitivity of inclusion of these samples was done.    

For each fleet, the raw observations were aggregated within a year. A catch-weighted approach was explored for Oregon and Washington observations from \gls{recfin} because these states have a formalized appraoch (E.J. Dick, personal communication, \gls{swfsc}) and a separate data table exists within \gls{recfin} (J. Edwards, personal communication, \gls{psmfc}) that includes the weightings. The catch-weighted distributions were very similar to the disributions based on raw observations, so raw distributions were used for simplicity.

The approach to determine the input sample sizes for the recreational length and age data varied by data source and data type. Some data sources had unique trip numbers within the data (Deb Wilson-Vandenberg and Oregon CPFV releases). Other data sources that lacked a clear trip identifier used combinations of multiple fields to attempt to estimate unique combinations that represented the number of trips sampled. In general the number of trips for both age and length composition data was estimated based on a mix of time, location, and fishery type. The number of trips for length and age compositions from Washington sport biodata was estimated using a combination of fish sample date (or sample date if blank), fish (or sample) punch card area, and fishing mode. The number of trips for length compositions from \gls{orbs} sampling was estimated using a field (ANGLER_ID) that encompasses time, area, and fishing mode. The number of trips for age composition from \gls{orbs} sampling was estimated using sampling date, sampling site (PORT_NAME), and fishing mode. The number of trips for length compositions from \gls{mrfss} sampling was estimated using year and id code, \gls{mrfss} area code and sampling location (INTSITE for California or ORBSport for Oregon), and fishery mode. The number of trips for length compositions from \gls{crfs} sampling was estimated using sampling date, sampling site (COUNTY_NUMBER), and fishing area and mode. Collectively, the estimates for the number of trips are meant to represent a reasonable starting point that generally reflects the degree of similarity of information from sampling a given number of likely similar fish within any sampling events.

The magnitude of sampling for each fleet and year are given in Table \@ref{tab:rec-sample-lengths} and Table \@ref{tab:rec-sample-age}, and show the different sampling frequencies employed over different time periods and between state agencies. These tables show both the total number of fish samples as well as the number of trips by year and state over which samples were obtained and which were used as input sample sizes. 

During modeling we noticed sparse age composition data of unsexed fish for a few years across recreational fleets. Years with very few unsexed age samples relative to sexed samples were excluded from the model. See [Appendix A](#excluded-data) for implied fits to these age data.
*We may not even need implied fits to these. A sensitivity would be to remove anything less than a certain number, whether sexed or unsexed*

The recreational length-frequency distributions are shown in (Figures \ref{fig:CA_rec_lencomp}-\ref{fig:WA_rec_lencomp}). All three recreational fleets appear to generally target smaller fish relative to the commercial fleets within the same state. Recreational lengths from California are highly variable, with sizes typically between 20-40 cm, but with sudden shifts in time (Figure \ref{fig:CA_rec_lencomp}). Recreational lengths from Oregon are less variable and typically range 25-40 cm, but had limited and variable sampling during the period of non-retention (Figure \ref{fig:OR_rec_lencomp}). In Washington, recreational lengths tend to be larger than in either California and Oregon, typically ranging from 30-45 cm (Figure \ref{fig:WA_rec_lencomp}). Length distributions for all recreational fleets showed an increase is sizes in recent years, which could be due to changes in regulations. Length distributions for Oregon and Washington also showed patterns of bimodality with a peak around 35 cm and then another around 50 cm (Figure \ref{fig:agglencomp}. This pattern was not due to combining across modes as it was present for both party/charter and private/rental modes.  

The recreational marginal age-frequency distributions are shown in (Figures \ref{fig:OR_rec_agecomp}-\ref{fig:WA_rec_agecomp}). Recreational ages were typically younger than in commercial fisheries. Ages ranged between 5-10 years but had long tails of older fish, with a larger proportional tail of older fish observed in Washington compared to Oregon. An increase in the age of sampled catch was observed in both Washington and Oregon recreational fleets, although the few years of Washington samples makes comparisons difficult. The changes in regulations in recent years complicate whether this pattern was due to increased ages of fish in the population or changes in fishing practices. 



*This section below (commented out) is really just fishery-independent comps - and mostly CAAL for the surveys KLO: I removed the data pieces, what remains is more a description of CAAL which I think belongs more in modeling.*
<!-- ### Expansion of length and age-composition samplmes -->

<!-- Age-frequency data from the Triennial and WCGBT surveys were compiled as conditional age-at-length distributions by sex and year. Individual length- and age-observations can be thought of as entries in an age-length key (matrix), with age across the columns and length down the rows. The approach consists of tabulating the sums within rows as the standard length-frequency distribution and, instead of also tabulating the sums to the age margin, instead the distribution of ages in each row of the age-length key is treated as a separate observation, conditioned on the row (length) from which it came. This approach has several benefits for analysis above the standard use of marginal age compositions. First, age structures are generally collected as a subset of the fish that have been measured. If the ages are to be used to create an external age-length key to transform the lengths to ages, then the uncertainty due to sampling and missing data in the key are not included in the resulting age-compositions used in the stock assessment. If the marginal age compositions are used with the length compositions in the assessment, the information content on sex-ratio and year class strength is largely double-counted as the same fish are contributing to likelihood components that are assumed to be independent. Using conditional age-distributions for each length bin allows only the additional information provided by the limited age data (relative to the generally far more numerous length observations) to be captured, without creating a 'double-counting' of the data in the total likelihood. The second major benefit to using conditional age-composition observations is that in addition to being able to estimate the basic growth parameters (L age-1, L age-30, K) inside the assessment model, the distribution of lengths at a given age, usually governed by two parameters; the CV of length at some young age and the CV at a much older age, are also quite reliably estimated. This information could only be derived from marginal age-composition observations where very strong and well-separated cohorts existed, that were quite accurately aged and measured; rare conditions at best. By fully estimating the growth specifications within the stock assessment model, this major source of uncertainty is included in the assessment results, and bias due to size-based selectivity is avoided. Therefore, to retain objective weighting of the length and age data, and to fully include the uncertainty in growth parameters (and avoid potential bias due to external estimation where size-based selectivity is operating) conditional age at-length compositions were developed for the triennial and WCGBT survey data. -->

<!--  -->