## Fishery-Independent Data

Fishery-independent data are derived from three main sampling programs: the triennial survey (1980-2004), the West Coast groundfish bottom trawl survey (WCGBTS; 2003-2022), and the pre-recruit survey.  Each source of information is used to generate an index of abundance.  The triennial and WCGBTS also provide age and length-composition sampling data.

### West Coast Groundfish Bottom Trawl Survey

The WCGBTS is based on a random-grid design, covering the coastal waters from a depth of 55 m to 700 fm [@bradburn_2003_2011]. This design uses four vessels per year (except in years 2004 and 2014, when only three vessels were available, and 2020 when the survey did not occur due to COVID-19), assigned to a roughly equal number of randomly selected grid cells divided into two ‘passes’ of the coast executed from north to south. Two vessels fish during each pass. This design therefore incorporates both vessel-to-vessel differences in catchability as well as variance associated with selecting a relatively small number (~700) of possible cells from a very large population of possible cells spread from the Mexican to the Canadian border. Much effort has been expended on appropriate analysis methods for this type of data [@helser_generalized_2004; @thorson_accounting_2011; @thorson_accounting_2013; @thorson_geostatistical_2015].

The WCGBTS encounters canary infrequently, generally in less than 10% of the total tows conducted, though this includes (Table \ref{tab:wcgbts}). However, when canary aggregations are encountered, catches can be as large as 4.9 mt in a single 12-15 minute tow; this equates to an average density of approximately 1 kg·2.5 m$^{-2}$. There are 19 tows that have encountered at least 500 kg of canary, and four tows have encountered over 1000 kg (2088 in 2015, 3033 in 2017, 3650 in 2018, and 3984 in 2006). These large tows are located primarily off the northern Washington coast near the Canadian border, with some located off the Oregon or Northern California coasts. The presence of infrequent very large tows creates a strongly right-skewed distribution of catch rates, still visible after log-transformation. These very large catches do not appear to be dominated by either very large individuals or very small individuals, indicating that these areas represent neither recruitment ‘hot-spots’, nor unexploited ‘pockets’ of very old canary rockfish.

### Triennial Survey

Prior to the \gls{s-wcgbt}, the triennial shelf trawl survey conducted by NMFS starting in 1977 served as the main fishery-independent data source regarding the abundance of canary rockfish [@dark_distribution_1994]. The sampling methods used in the survey over the 24-year period are most recently described in Weinberg et al. [-@weinberg_2001_2002]; the basic design was a series of equally spaced transects from which searches for tows in a specific depth range were initiated. In some parts of the coast this led to a very non-random allocation of stations with regard to the entire shelf area *TODO: Figure*(Figure \ref{}). In general, all of the surveys were conducted in the mid-summer through early fall: the survey in 1977 was conducted from early July through late September; the surveys from 1980 through 1989 ran from mid-July to late September; the survey in 1992 spanned from mid-July through early October; the survey in 1995 was conducted from early June to late July; the 1998 survey ran from early June through early August; and the 2001/2004 surveys were conducted in May-July. The initial year of the survey in 1977 was based on a sampling design that spanned from 50 to 260 fm. (91 to 475 m), i.e., it did not come as far inshore (30 fm.) as the subsequent surveys conducted on a triennial basis from 1980 to 2001. 

When estimating an index of abundance, we restrict analysis to depths from 55-366m and excluded tows outside to the US exclusive economic zone (i.e., in Canadian waters) to produce the only consistent time-series available. Surveys that have extended south of Monterey have detected only very small abundances relative to the north, so lack of sampling in this area does not influence the relative index. Because of the large number of ‘water hauls’ eliminated in 1977, especially in the US Vancouver INPFC area, and because the sampling depths were not the same as the other years, the 1977 survey year was not used in the assessment. A full description of the water haul issue can be found in Zimmerman et al. [-@zimmermann_retrospective_2001]. 

### Pre-recruit survey

*We have some figures in this text (4 and 5) that we dont have figures for*

The Fishery Ecology Division of the Southwest Fishery Science Center has conducted a standardized pelagic juvenile trawl survey (the Rockfish Recruitment and Ecosystem Assessment Survey) during May-June every year since 1983 [@ralston_juvrockfish_2013; @sakuma2016anomalous; @field2021spatiotemporal). A primary purpose of the survey is to estimate the abundance of pelagic juvenile rockfishes (*Sebastes spp.*) and to develop indices of year-class strength for use in groundfish stock assessments on the U. S. West Coast. This is possible because the survey samples young-of-the-year rockfish when they are ~100 days old, an ontogenetic stage that occurs after year-class strength is established, but well before cohorts recruit to commercial and recreational fisheries. This survey has encountered tremendous interannual variability in the abundance of the species that are routinely indexed, as well as high apparent synchrony in abundance among the ten most frequently encountered species [@ralston_juvrockfish_2013]. Past assessments have used data from this survey to provide indices of year-class strength (as relative age-0 abundance), including the 2015 Canary rockfish assessment, and assessments for widow rockfish [@adams_status_2019], blue/deacon rockfish [@dick2018bluedeacon], bocaccio [@he_status_2015], shortbelly rockfish [@field_status_2007], and chilipepper rockfish [@field_status_2015].

Historically, the survey was conducted between $36^\circ 30^\prime$ N and $38^\circ 20^\prime$ N latitude (the ‘core area’ from approximately Carmel, CA to just north of Point Reyes, CA), but starting in 2004 the spatial coverage expanded to cover from the U.S./Mexico border to Cape Mendocino. Additionally, since 2001 data are available from comparable surveys conducted by the Pacific Whiting Conservation Cooperative and the \gls{nwfsc} (2001--2009) and the \gls{nwfsc} “Pre-recruit” survey (2011--2022) for waters off of Oregon and Washington [@field_spatiotemporal_2021]. Coastwide data have revealed both spatial differences in species composition (e.g. north and south of Point Conception) and interannual shifts in the distribution of most pelagic juvenile rockfishes: The near absence of fish in the core survey area during the 2005--2007 period, which saw two of the lowest abundance levels of juvenile rockfish ever observed in the core area time series, was associated with an apparent redistribution of fish, both to the north and the south [@ralston_prerecruit_2013]. As the core area index seems to have failed to capture the magnitude of the 1999 year class for most stocks, the recommendations from the juvenile rockfish survey workshop held in 2005 were to use only the coastwide data (since 2001) for juvenile indices rather than the longer-term ‘core area’ indices unless a convincing case could be made otherwise. We used data from 2001 to 2022, the period for which we have coastwide coverage. On account of the COVID-19 pandemic, sampling in 2020 was very limited and restricted to the historical core area, so this year is excluded. In the years 2010, 2012, and 2022, sampling did not span the entire coastwide spatial domain, with data lacking from northern CA and OR **TODO:**(Figure \ref{}). These years were included in the model, but sensitivity of the stock assessment to exclusion of the index for these years should be explored. 

Catch per tow was adjusted to a common age of 100 days to account for interannual differences in age structure, as has been done for prior assessment indices using this dataset.


*TO DO sensitivity of excludnig the years 2010, 2012, and 2022*


### Surveys considered by not used

## Index Standardization

Data from all three surveys were analyzed using geostatistical delta-GLMMs implemented using the sdmTMB package (https://github.com/pbs-assess/sdmTMB). For the triennial and \gls{s-wcgbt}, this was done using the wrapper for west coast groundfish surveys, indexwc (https://github.com/kellijohnson-NOAA/indexwc). The \gls{pfmc} \gls{ssc} approved the use of sdmTMB for fishery-independent indices in WHEN. We used a lognormal error distribution for both surveys. The lognormal distribution has larger tails than the gamma distribution and is thus better able to catch the extreme tows observed when encountering large canary aggregations. We explored use of extreme catch event distributions which could even better capture such tows without undue influence on the index, but the models did not converge. The indices calculated using the lognormal distribution also displayed more autocorrelation across years, and were thus deemed more biologically realistic. Finally, the assumption of a lognormal distribution produced better Q-Q plots for the positive catch model compared to a gamma distribution.

We analyze data from the triennial survey using version 1.0.0 of the Bayesian stratified delta-GLMM, implemented as an R package BayesDeltaGLM and publicly available here: https://github.com/pfmc-assess/nwfscDeltaGLM.  A full description of this model can be found in Thorson and Ward (2013, 2014).  We include Julian calendar date as a covariate during analysis of data 1980-2004 to account for differences in availability due to changes in timing of the survey (i.e., before and after 1995).  We include three spatial strata, corresponding to the three strata in our base model, and also exclude any data with depth <55m or >366m (i.e., only using data for within the range of depths where canary are present).  We select among eight candidate models, formed from the combination of four potential distributions for positive catch rates (lognormal, gamma, lognormal-ECE, gamma-ECE) and two potential treatments of spatiotemporal variation (including or not including the interaction of spatial stratum and year as a random effect).    This Q-Q plot (Figure 5) reveals no evidence that the stratified delta-GLMM fails to capture the variability present in the positive catch rates of the triennial data.   We then extract indices of abundance for each of the three strata.  These indices show similar trends in abundance in all three strata, where relative abundance reached a low-point around the 1995 survey and has since exhibited some degree of rebuilding (Figure 6).  

	We analyze data from the WCGBTS using version 3.2.0 of the geostatistical model, implemented as an R package SpatialDeltaGLMM and publicly available here: https://github.com/pfmc-assess/geostatistical_delta-GLMM.  This software uses Template Model Builder (Kristensen, 2014; Kristensen et al., 2016) to integrate across the latent probability of random effects, when maximizing the marginal likelihood function (Thorson and Minto, 2015).  We additionally include pass (levels: first or second) as a covariate in the model, to account for unbalanced sampling between the first and second passes in years 2004 and 2014.  We select among four potential model treatments, i.e., treating positive catch rates as following a lognormal, gamma, lognormal-ECE, or gamma-ECE distribution.  The model using the gamma-ECE distribution did not converge, and AIC indicated greatest support for the lognormal-ECE distribution among other model options.  We therefore used the geostatistical model with the lognormal-ECE distribution to generate an index of abundance for the WCGBTS for years 2003-2014.  Following advice from the Science and Statistical Committee, we display the Quantile-Quantile plot, generated by comparing each observed datum with its predicted distribution under the fitted model, calculating the quantile of that datum, and comparing the distribution of quantiles with its expectation under a null model (i.e., a uniform distribution).  This Q-Q plot is shown in Figure 7, and shows no evidence that the model fails to capture the shape of dispersion shown in the positive catch rate data.  The estimated spatial distribution of canary densities is shown in Figure 8, and shows that the highest densities are predicted to occur in Northern Washington, where the extreme catch events are most often clustered.  This estimated density throughout the WCGBTS sampling domain is then post-processed to generate three separate indices of abundance, corresponding to the three spatial strata used in the base model (CA: 32-42°N, OR: 42-46°N, WA: 46-49°N), and coast-wide areas between depths of 55 and 366 m.  These indices are shown in Figure 9 and, as expected, the greatest estimated abundance occurs in WA, followed by OR and with substantially lower abundance in CA. 

A comparison of stratified and geostatistical indices of abundance, with the design-based estimate also shown (Figure 11) illustrates that the design-based index is highly sensitive to extreme catch events, as previously reported (Thorson et al., 2011).  The stratified and geostatistical indices are generally similar coast-wide and for each individual stratum, although the geostatistical model has slightly smaller intervals, as predicted by Thorson et al. (2015b).  We later present a sensitivity analysis when including the index estimated by the stratified model in the base assessment model, compared with using the geostatistical index.

### Pre-recruit survey

For the index model, we used data from 35–$48.2^\circ$ N latitude (just north of Point Conception to La Push, WA). Canary rockfish were never caught south of $35^\circ$ N. Since catch (and sampling) varied over space and time, we modeled catch using a spatial GLM with the package sdmTMB [@anderson_sdmtmb_2022]. The 100-day-standardized catch per tow was modeled as a function of fixed year effects along with Julian date (GAM smoother with k=4) to account for seasonality, a spatial random field, and IID spatiotemporal random fields. 

We fit the model using 3 different error structures: tweedie, delta-lognormal, and delta-gamma. Dharma quantile residuals from model simulations suggested that tweedie distribution was the best (Fig. 5), and so was used. The tweedie model also best reproduced the observed proportion of zeros in the data based on simulations from the fitted model. As expected, the Julian date effect showed a decline in catch towards the end of the sampling season, as juveniles begin to settle out of the water column. 

For the coastwide index, predictions from the model were made for all active sample stations within the survey region, for the mean Julian date, for each year. Predictions were added together for each year to produce the index. Active stations are those regularly and consistently sampled, and are located on a semi-regular grid spanning the sampling region. Interpolating to a finer spatial grid had little impact on the resulting index.

*NOTE: May or may not keep this in as it describes the state indices*
For state specific indices, we used predictions to active stations from the coastwide model, subdivided by state. The California index used stations south of $42^\circ$ N, the Oregon index used stations between $42^\circ$ N and $42.25^\circ$ N, and the Washington index used stations norther of $42.25^\circ$ N. Lengthy discussions were had as to whether to subdivide predictions from the coastwide model or to fit separate models for each state. Part of the difficulty with state-specific models is the sparsity of samples and positive catches from Oregon and Washington, which make it difficult to estimate the spatial and spatiotemporal random fields as well as the effect of Julian date. Additionally, when samples are split up by state, there end up being some years in all states with no positive catches, for which index values cannot be estimated using fixed year effects or year-by-state interactions. Using the coastwide model for the state-specific indices allows data from adjacent states to improve estimation of spatial fields near the borders and allows better estimation of the spatial scale of autocorrelation and Julian date effects, while still allowing abundance in each state to be determined by local data through the spatiotemporal fields. In model exploration for black rockfish (specifically the Oregon index for the combination of black and yellowtail rockfishes, which had similar positive catch rates as canary rockfish), fitting a nonspatial model spatially restricted to Oregon produced a similar index to a spatiotemporal model using additional data from California and southern Washington (with predictions restricted to Oregon) for years in which sampling occurred in Oregon. Thus we decided for sake of parsimony and to maximize the use of available data to subdivide the coastwide model, to exclude from the indices state/year combinations in which no sampling occurred at all (2010 for OR, and 2001, 2002, 2003, 2010, 2012, 2014, 2017, 2021 for WA), because in these years there is no local data to inform the index. As with the coastwide index, 2020 was excluded for all state-specific indices. Due to data sparsity (low number of samples and low number of positive catches), we consider the indices for Oregon and Washington to be more uncertain than California, with the Washington index most uncertain.






