## Data sources considered but not used


*We should specify what sources of data (catch, lengths, ages, indices) these refer to*

*Need to add debWV index and other california index from Melissa that were not done*

### \gls{s-ccfrp}

The \gls{s-ccfrp} has conducted fishery-independent data collection efforts onboard commercial passenger fishing vessels both inside and outside of MPAs between 2007 and present. Aspects of canary rockfish life history make the data set less than ideal. One important consideration is the limitation of sampling to less than 150 ft to minimize barotrauma for fish released by this hook and line survey, which limits access to the primary depth distribution of adult canary rockfish. In addition, until 2017 the sampling was focused on central California at the southern edge of the species range in California. While additional data has been collected subsequently to better represent the statewide abundance of groundfish stocks, the limited depths sampled and spatial limitations early in the survey further the utility and representativeness of the survey for this northernly distributed stock. Lastly, the high degree of vagility of canary rockfish makes accounting for MPA effects of lesser importance reducing the impetus to account for trends in closed areas for this species.

### Commercial Collection Report System

From 1977-1985 Commercial Collection Report System (CCRS) provided data on commercial passenger fishing vessels sampled at dockside. This study was very limited in spatial scale, focusing efforts on a limited portion of the species range in the Monterey Bay area representing only the southern end of the distribution of canary rockfish. In addition, this region is unique in providing access to deeper depths a short distance from shore along the sub-marine canyons of Monterey and Carmel Bays potentially biasing representation relative to the entire coast north of Point Conception within California where they are commonly found. Though 488 canary rockfish were sampled during the duration of the survey limited geographic representation at the southern edge of the species range and lack of representation from other ports with more distant grounds on the shelf/slope limits the utility of this data and comparability to other data sets.

### Historical CDFW Dockside Sampling

A dockside sampling effort was undertaken by CDFW during the 1950s-1970s to collect data from the private and rental boat and party charter fleets. Data collected from 1958 to 1972 from Miller and Gotshall 1965. Miller and Geibel 1973 and efforts were made to digitize data from sample sites in the Monterey Bay Area from Ano Nuevo to Point Sur. Over the course of the survey, 1032 canary rockfish lengths were collected from party boats and 461 from private boats. The limited geographic representation at the southern edge of the species range and lack of representation from other ports with more distant grounds on the shelf/slope limits the utility of this data and comparability to other data sets.

### Deb Wilson-Vandenberg CPFV Index

### CRFS Recreational Index

### California Remotely Operated Vehicle Survey

\Gls{cdfw} in collaboration with Marine Applied Research and Exploration (MARE) have been conducting remotely operated vehicle (ROV) surveys along the California coast in Marine Protected Areas (MPAs) and reference sites adjacent to them since 2007 for the purposed of long-term monitoring of changes in size, density (fish/sq meter) and length of fish and invertebrate species along the California coast. Surveys of the entire coast have been undertaken twice, taking three years to complete each resulting in super years of 2015 (2014-2016) and 2020 (2019-2021) available for analysis. The use of this data in stock assessments was approved by the \gls{ssc} for use in stock assessments after a methodology review conducted in 2019 for use as an index of abundance or absolute abundance estimate using seafloor mapping as the basis for expansion to rocky reef habitat. Ultimately, this survey was not used for this assessment due to limited temporal coverage (two three-year periods) and highly variable estimates, as well as limited representation to coastwide dynamics.

### Washington Sport Dockside interview data

The WDFW provided recreational dockside fisheries data from 1981 through 2022 for consideration in this assessment. Data were collected at the trip level, with the number of landed fish and the number of anglers on each vessel being recorded. The amount of time fished by each angler was not recorded. The recreational dockside data was considered for use in this assessment, however, management measures implemented over the past several decades impeded extracting a reliable signal for use as abundance indices. In 2003, management restricted summer fishing depths to shallower than 20-fathoms in WDFW marine areas 3 and 4, and in 2006 modified this depth restriction to 30-fathoms in marine areas 2, 3, and 4. Additionally, daily rockfish limits were 15 fish from 1981-1991, 12 fish from 1992-1994 (except in area 1 where it remained at 15), 10 fish from 1995-2016, and a reduction to 7 fish from 2017-2022. The effects of these management changes to CPUE of canary rockfish could not be reconciled with changes in the abundance indices and therefore this dataset was not used in this assessment.

### Washington nearshore rod-and-reel survey

Fishery-independent data available for this assessment came from two distinct WDFW research projects. The first was the Rockfish Tagging Program that was initiated in the early 2010s primarily off the central coast of Washington with sparse coverage in the northern and southern coast. The second data set was from the standardized Coastwide Rod-and-Reel Survey that began in 2019. The tagging program had strong focus on black rockfish and had little information for canary. The new nearshore survey was impacted by the COVID pandemic and was not completed as originally designed. Due to their short time spans and spatial coverage limited to Washington waters, these two datasets are not used in this assessment.

### WA olympic coast YOY survey (NOAA)

Dive surveys represent a promising data source for `r spp` as their habitat preferences for rocky untrawlable habitat means they are poorly sampled by NMFS trawl surveys. However, this seven-year dataset covering juvenile rockfish habitat (2015-2022, missing 2020) contained three years without any canary observations, and only covers the northern Washington coast. Due to limited sample sizes and coverage of only a small fraction of the assessed area, this dataset was deemed insufficient for inclusion in the assessment. Future research could synthesize dive surveys from throughout the range of canary to build a more robust recruitment index post-density dependence that may be more appropriate for inclusion in an assessment. 

### Oregon indices

*Kiva: I updated this text a little to clarify the two indices are those we mention. Can you confirm this is still accurate?*

Two indices of relative abundance were developed for canary rockfish in Oregon using the \gls{sdmtmb} package, one fishery-dependent and the other fishery independent, but ultimately not included in the base model due to their limited representation of coastwide `r spp` dynamics. Given the period of non-retention for canary rockfish, the only viable fishery-dependent index was based on onboard sampling of charter vessels that includes both retained and released fish. Additionally, a second index from Oregon’s marine reserve hook and line survey was also developed.

### \gls{s-hkl}

This survey operates south of Point Conception, whereas `r spp` density decreases substantially after that major biogeographic barrier. CITE MAP OF WCGBTS TOWS. Thus, this survey does not cover the main spatial range of the stock and was not considered representative.

### \gls{iphc} longline survey

Data from the \gls{iphc} longline survey data were examined for their utility in providing an index of abundance for `r spp`. This survey caught 178 `r spp` over 23 years, and thus was deemed insufficient for developing an index.