## History of Modeling Approaches

### Early assessment history

The first formal assessment of the canary rockfish resource off the U.S. Pacific coast was done in 1984 [@golden1984progress]. The final results from the initial assessment in 1984 were largely based on qualitative examinations of trends in age and size distributions generated from both fishery and survey data. The 1984 research also included exploratory efforts to fit dynamic models to time series data, using tools such as Virtual Population Analysis and Stock Reduction Analysis, but due to highly variable sample data and its lack of availability in all years, results from the modeling were not considered scientifically valid. The 1984 assessment concluded that the canary rockfish resource was generally stable at that time and that the current restrictions were still reasonable.

The canary rockfish assessment conducted in 1990 was the first evaluation to incorporate separable catch-at-age analysis and in particular, the first to use the Stock Synthesis Model [@golden1990status; @methot_stock_2013]. All subsequent stock assessments have used the Stock Synthesis Model to evaluate the status of canary rockfish, although the model has undergone considerable development. The Columbia INPFC area was the only portion of the canary rockfish resource formally modeled in 1990. The 1990 assessment was the first to propose two broad assumptions regarding the absence of old females in the sample information relative to males: (1) the females are subject to a different rate of natural mortality than males; or (2) the females are less vulnerable to the fishing and sampling gears. Based on a $F_{35\%}$ management model, results from the 1990 assessment indicated the ABC for the canary rockfish resource in the Columbia INPFC area should be decreased by roughly 30 percent.

The assessment conducted in 1994 again utilized the age-based version of the Stock Synthesis model to evaluate the status of the canary rockfish population in the Columbia, INPFC area, as well as the U.S. Vancouver INPFC area [@sampson1994canary]. The data sources in the previous assessment (1990) were updated, with the exception of the commercial trawl effort index from the fishery due to sample and estimation biases associated with logbook data. Results from the 1994 assessment clearly indicated that the current level of F exerted on the canary rockfish population exceeded $F_{20\%}$ (the overfishing threshold at that time) and thus, the researchers recommended that the ABC be reduced to allow the stock to recover [@sampson1994canary].

In 1996, the canary rockfish stock was assessed using similar methods and configurations as in 1994 [@sampson1996canary]. The model was largely similar to that in 1994. One difference between the 1994 and 1996 assessments was the manner in which error associated with age-composition data from the fisheries was accommodated. In the 1996 assessment, a single, percent-agreement error structure was used to describe the variability in the age-related data, whereas in 1994, an error-transition matrix was used to standardize multiple sets of age estimates generated from two age readers. Newly obtained data supported findings from the 1994 analyses and final results further indicated that the canary rockfish stock had suffered fishing in excess of $F_{20\%}$.

In 1999, two age-structured stock assessments were adopted. Williams et al. [-@williams1999stock] completed an assessment for the southern INPFC areas (Eureka and Monterey) and Crone et al. [-@stat1999canary] conducted a separate assessment for the Northern INPFC areas (Columbia and US Vancouver). Both assessments concluded that the abundance of canary rockfish was below the overfished threshold. A major source of uncertainty was the role that natural mortality and adult movements played in the relative lack of old females. The northern assessment was performed using an age-based stock synthesis model and relied on age distributions to summarize changes in the age-structure. The Southern assessment was a length-based (although still age-structured) model in \gls{admb}. The southern assessment also tried to account for effects of sized-based removals on population growth. The subsequent rebuilding analysis relied upon recruitment information from the northern area where the larger portion of the stock occurs.

### 2002 Benchmark

The 2002 assessment unified the previous northern and southern assessments into a coast-wide model [@methot2002canary]. This assessment was the first to incorporate the newly available survey information from the \gls{s-wcgbt}. This assessment focused on the exploration of two states of nature that were considered in previous assessments: age-dependent natural mortality for females versus dome-shaped female selectivity. Together with the STAR panel, it was concluded that these need not represent discrete hypotheses and that both scenarios could be modeled simultaneously. The 2002 assessment concluded that the canary stock was still at very low levels, 8% of the estimated unexploited conditions.

### 2005 Benchmark

The 2005 assessment converted and updated the 2002 effort using Stock Synthesis 2 [@methot2005canary]. The assessment reconfigured the spatial separation of fisheries to separate northern and southern California due to the north-south difference in occurrence of larger fish and the varying north-south distribution of fishery sampling. Fishery removals were divided among more fleets; separating trawl, non-trawl, and recreational fleets by state with some state/gear combinations. This assessment switched from age-based selectivity to length-based selectivity, and assumed asymptotic selectivity for males and allowed dome-shaped selectivity for females. Numerous changes to data in the model were utilized including adding ageing error bias, iterative re-weighting of data sources, dropping the trawl and recreational fishery CPUE, and fixing the parameters defining the variability in size-at-age at values estimated outside the model. 

SSC review of the canary rockfish assessment concluded that the parametric variance around a single base model underestimated the overall uncertainty in the canary rockfish assessment. After considerable deliberation, the SSC and STAT concluded that the base (selectivity allowed to differ by sex) and alternate (sex invariant selectivity) models were equally likely and supported a statistically based blend of the two models as the basis for the rebuilding analysis, with both indicating low levels of depletion.

### 2007 Becnhmark

The 2007 benchmark assessment proceeded by rebuilding all data streams and re-examining all assumptions regarding selectivity, growth, and mortality [@stewart2007canary]. The 2007 assessment updated to using a double-normal selectivity option which was simpler than the double-logistic used in the 2005 assessment by 2 parameters (6 vs. 8). The 2007 assessment incorporated substantial new assessment data as well as the addition of the at-sea whiting fleet, research catches, the improved ageing-error definitions and the introduction of conditional age-at-length data for survey fleets. Because of the use of conditional age data in place of marginal age-frequency distributions and mean-length at age data used in 2005, the parameters describing the distribution of length at a given age were also freely estimable. These changes had a larger effect than the selectivity parameterization, serving to increase the estimate of $SB_0$ and current stock size, but had little effect on relative trend over the time series. Changes to the stock-recruit relationship included fixing steepness at 0.35, estimating the full time series of recruitment deviations and adding a ramp to bias correction. The 2007 assessment also eliminated several discrete time-blocks for changes in fishery selectivity prior to recent management actions. In aggregate, these changes further scaled the estimate of the time series of spawning biomass up, but retained the relative trend. The 2007 assessment was also the first to split the triennial indces into an early and late period due to changes in the survey's timing. 

The 2007 model was subsequently updated twice, in 2009 [@stewart_update_2009] and 2011 [@wallace_update_2011]. The 2009 update decreased the catch time series prior to World War II, reducing the estimate of spawning biomass by an average of 14 percent (19 percent in the first 10 years of the series and 47 perecent in the last 10), and the 2011 update resulted in little additional change.

### 2015 Benchmark

The 2015 stock assessment updated data streams and biological relationships from the 2007 benchmark, and changed the modeled population structure compared to past assessments [@thorson_status_2016]. The most significant change in parameters governing biological relationships was an increase in the steepness parameter from 0.511 in 2007 to 0.773 in 2015, due to updates in the Thorson-Dorn rockfish prior from past meta-analysis [@dorn_advice_2002]. The change in steepness prior was for assigning alternative states of nature within the decision analysis in addition to values for natural mortality, which past assessments had used as a key uncertainty. Additional changes in biological relationships were in parameters governing the maturity relationship, which explicitly accounted for the presence of skip spawning, as well as updates to the fecundity relationship, and the natural mortality prior.

The 2015 assessment modeled the population of `r spp` along the U.S. West Coast across three areas, divided by each state. The spatial structure was modeled as a tool to "visualize and explore model residuals and a method to identify time-varying selectivity at the stock-wide level, rather than as a basis for spatially varying fisheries management". 
<!-- This was in part due to STAR panel recommendations from the 2007 to explore spatial patterns in the data and that emphasized tagging data would be essential to that effort, and also to establish a framework for trans-boundary management with Canada.  -->
The spatial areas in the 2015 assessment were similar in many ways in that they shared the same growth parameters, and no movement in adults among the areas was assumed (although this sensitivity was tested and found to have little effect on model results). The only connection modeled between the three areas was apportionment of recruits from a single shared stock-recruitment relationship to each area. Sensitivity to the assumed spatial structure found that compared to a coast-wide representation of the population, results from a spatial model were similar. 

In addition to updates in biological parameters, and spatial changes to the population model, the 2015 stock assessment made improvements in the analysis of age-error matrix for better accounting for uncertainty and bias in age reads for `r spp`, and significant improvements in including spatial-autocorrelation of survey data when calculating abundance indices. Analysis in ageing error bias resulted in the inclusion of surface reads from the late 1970s and early 1980s in that strong bias in surface read ages could be accounted for based on the ageing-error matrices, although the presence of surface reads was found through sensitivities to have negligible effect on model results. Improved survey index calculation is now accepted practice for U.S. West Coast assessments.

The 2015 assessment model indicated that `r spp` was above the management target (>40 percent) for spawning output relative to unfished levels, and was subsequently used to support the declaration that the stock was rebuilt. The 2015 model was since been updated three times, in 2017 [@thorson_update_2017], 2019 [@wallace_update_2019], and again in 2021 [@correa_update_2021] using catch-only updates. The 2017 catch-only update corrected an error found during the 2017 assessment cycle in the database used to inform historical catches for the California commercial fleets prior to 1951, which were found to be about half the amount used in the 2015 assessment model. The 2021 catch-only update corrected the catch time series in 2016--2018 that were used in the 2019 catch only update. All updates suggested a continued trend in the population as observed in the 2015 benchmark assessment. 

## Most Recent STAR panel and SSC Recommendations {#star-recs}

The 2015 STAR panel and SSC did not list any major deficiencies for the previous assessment. Responses to research recommendations from the 2015 STAR panel reported are below. 

**Recommendation**: The historical catch data ultimately used in the assessment differed from that which was given in the original draft assessment presented for review at the panel. The review process would be improved by ensuring that any such issues (i.e. disagreements about the best available historical catch) are resolved well in advance of the assessment review meeting. One possible approach might be to have an earlier step in the process intended to sign-off on the input data, analogous to the way that the STAR panel signs-off on the stock assessments. Ongoing efforts to reconstruct Washington catch data, in the way that has already been done for Oregon and California, should help to resolve these issues in the medium term, but until then, there will still be a need to work with agreed, interim catch estimates for inclusion in stock assessments.

**Response**: Significant progress has been made to streamline the review process to reduce the number of changes to catch streams during STAR reviews. The TOR outlines the steps for finalizing catch time series by a designated data deadline, which we have done. Increased communication between the STATs, management and advisory bodies, and state agencies have resulted in changes to the catch history during model development, and as of time of writing, not during the STAR review.

**Recommendation**: Catch and discard history for this stock in U.S. waters is highly uncertain. While the STAT was able to construct alternative upper and lower bounds for catch using simple multipliers on certain years of historical catch, this is arbitrary. Work to assess the uncertainty related to each individual data source would allow a better investigation of the overall combined uncertainty and its effect on 10 stock assessments.

**Response**: This assessment includes a new reconstruction of `r spp` landings in Oregon within unspecified PacFIN categories from 1987-1999. A formal Washington reconstruction is nearing completion, but was not yet ready for use in this assessment. Increased variation about catch time series was explored as a sensitivities.

**Recommendation**: Improved documentation is required to clearly outline the process used to construct the historical catch and discard time series from the various data sources. Such documentation should also include the process for construction of alternative catch histories that are used to propagate such uncertainty into the stock assessment.

**Response**: This assessment report has attempted to more clearly document the process used to construct the historical catch and discard time series. In addition, [the use of github for this assessment](https://github.com/pfmc-assessments/canary_2023) means that the code used to construct the time series, and many of the decisions involved, is publicly available and the process is reproducible. Finally, the STAT has communicated repeatedly with state partners and the GMT to ensure that catch time series are appropriate, per the TOR. This communication did result in changes to the catch history during model development.

**Recommendation**: Additional work on the geospatial index is required to better resolve differences in abundance trends among areas.

**Response**: This assessment did not use a spatially stratified abundance index, although during early index development separate year by area covariates were consider for use in index development.

**Recommendation**: Work towards a combined US/Canadian stock assessment would greatly aid our overall understanding of stock status.

**Response**: Little progress has been made on a combined US/Canadian stock assessment. The STAT did obtain catches and estimated recruitment and recruitment deviations from a recent British Columbia assessment. We have conducted a sensitivity with these catches added to Washington fleets, and compared the recruitment deviations estimated within our base model and the Canadian model to look for synchrony. Other than fisheries under a binational treaty, U.S. West coast assessments use the U.S.-Canadian border as the northern limit for data to use within models.

**Recommendation**: If data permit, the trawl fleet should be divided into separate components so that bycatches in the shrimp and pelagic trawls are separated from catches in the main bottom trawl fleet. In the current assessment, composition data for the trawl fleet have a major influence on the estimated stock trends, so it would be desirable to use data that are more representative of the main fleet in order to improve estimated selectivity of the fleet.

**Response**: Due to the already extremely complex fleet structure in this model, the shrimp and pelagic trawls were maintained with the main trawl fleet. The number of samples for the shrimp trawl gear is less than 1% of the samples compared to the trawl gear in Oregon, so is expected to have a small effect on selectivity estimates. The midwater trawl component has more samples and removals are higher in recent years (in part because midwater trawl codes were only available starting in 1979 for Oregon and in 2000 for Washington). However, selectivity blocks are imposed, and are expected to limit the effect of midwater trawl composition data on the entire trawl time series. Moreover, initial analyses indicated length and composition data from the shrimp and midwater trawl fisheries within \gls{pacfin} were comparable to other trawl gears. 

**Recommendation**: Basic life history research may help to resolve assessment uncertainties regarding appropriate values for natural mortality and steepness, and how to best account for the apparent loss of older females in the population.

**Response**: This assessment includes fecundity and maturity curves based on new data made available since the last benchmark assessment. While efforts have been undertaken to understand the apparent loss of older females, this has not resulted in any clear resolution. A research study sampling in non-trawlable habitat along the U.S. West Coast found a similar lack of old females in the data [@Brooks_thesis_2021]. Examination of data from the Oregon trawl fleet indicates that sex ratios have been more constant across ages in the last decade than they had been previously (L. Rasmuson, pers. comm.).

## Response to Groundfish Subcommittee Requests

To be completed after the STAR panel.
