## Model Structure and Assumptions

### Modeling Platform and Structure

We used Stock Synthesis version 3.30.21, compiled February 10, 2023 by
Rick Methot at the \gls{noaa} \gls{nwfsc} using the 64-bit version of
ADMB 13.1 [@methot_stock_2013]. This most recent version includes
improvements and corrections to older model versions. The previous
benchmark assessment used an older version of Stock Synthesis, version
3.24V. The R package `r4ss`, version 1.48.0 [@taylor2021beyond], along with R version 4.2.2
[@r2022r] were used to investigate and plot model fits.

### Balance of Realism and Parsimony

The base assessment model for `r spp` was developed to balance parsimony
and realism, and the goal was to estimate a spawning output trajectory
for the population of `r spp` off the U.S. West Coast. The model
contains many assumptions to achieve parsimony and uses many different
sources of data to estimate reality. A series of investigative model
runs were done to achieve the final base model, some of which are
described as sensitivities (Section \@ref(sensitivities)) and some of
which are included in the bridging steps described below. Notably, we
simplify the population structure of the last benchmark assessment model
by assuming a single coastwide stock, yet increase spatial fleet
structure by unmirroring fleet selectivities among states and allowing
sex-dependent selectivity at larger sizes. We balance the increased
complexity in spatial fleet structure by simplifying the selectivity
parameterization and combining fleets and minimizing the use of blocks
where possible, and assuming natural mortality to be age-invariant, as
opposed to increasing with age for females.

### Model Changes from the Last Assessment

The assessment model structure has been significantly altered from the
2015 benchmark stock assessment [@thorson_status_2016]. The primary
change affecting model results is the change in
modeling of natural mortality. We model natural mortality as
sex-dependent and age-invariant which offers a simplified and more
biologically believable approach to natural mortality than an increasing
linear ramp in female natural mortality. While natural mortality of females and males likely is similar at young ages, given that the fisheries and surveys do not fully select the smaller, younger fish, natural mortality at young ages does not matter as much as a reasonable cumulative natural mortality at older ages. Assumptions to this choice are
tested with sensitivities and described in Section \@ref(sensitivities).

Another substantial change is in the treatment of spatial structure in
the model, both in terms of population spatial structure as well as
fishery fleet structure. We simplify modeling the population structure
of `r spp` along the U.S. West Coast by assuming a coastwide population,
yet increase the spatial complexity of the fishery. This amounts to
using an areas-as-fleets approach [@punt_spatial_2019]. Although an
areas-as-fleets approach does not account for potential regional
differences in depletion, because catches are assumed to act over the
entire modeled area, explorations indicated instability when unmirroring and expanding selectivity, thus suggesting that the data does not support realistic parameterization within the spatial model. Through
bridging of the spatial model (described below) we show that the change in population
structure does not have a large effect on model results,
especially relative to changes in the modeling of natural mortality and the
relative contribution of various data sources to model estimates.

By reducing complexity in the population structure of the model, we
could increase the spatial complexity of the fishery. Spatial fleet
dynamics allow the model structure to account for varying selectivity
and historical management actions that may have impacted the fishery and
the available data in specific ways. In the 2015 assessment fleets were assumed to have the
same selectivity across states. We allowed
selectivity estimates to be informed by the dynamics in waters where
they fish, although we have mirrored some fleets where we believe and the data indicate it is
appropriate to do so. We have also increased the number of selectivity
blocks for the non-trawl and recreational fisheries, which is
appropriate given the large changes in regulations for `r spp`. Lastly,
we have elected to include sex-dependent selectivity, which both
improves fits to data and allows dynamics between male and also female
natural mortality to align better with observed sex-ratios.
Sensitivities to choices about selectivity are described in Section
\@ref(sensitivities).

While, in general, fleet structure in the base model is more complex than
in the 2015 assessment, we simplified our fleets where reasonable. We
treated survey fleets as exclusively survey fleets, and did not model
the small amount of catches from these surveys. It is no longer standard
practice to include surveys as fishing fleets in West Coast assessment.
We also removed the California at-sea-hake fishery composition data,
which was very sparse, and incorrectly assigned to California, and
combined selectivity for the Washington and Oregon fleets, which have
similar dynamics and fish across state boundaries.

Data has also been updated for this assessment. The synthesis and
treatment of data has been altered for this assessment based on updated
best practices and extensive work by \gls{nwfsc} to document, reproduce,
and standardize data processing steps, along with extensive work by
staff at state agencies and \gls{psmfc} in providing consistent and
accurate data in a more easily obtainable manner. Catch time series have
been updated according to current best knowledge. States have updated
their historical reconstructions, and past issues with catch time series
mentioned in the last assessment review process and in subsequent
catch-only updates have been corrected. Catch time series for the
foreign fleets was also repartitioned to states more consistently with
patterns observed in the non-foreign fishery. We assigned data from
shrimp trawls as part of the trawl, where for the 2015 assessment they
were included within the non-trawl fleets. Available length and age data
have been processed using updated and more reproducible approaches.
Substantial effort was made by the \gls{nwfsc} ageing lab in providing
age reads for new and previously collected `r spp` otoliths. These allow age composition data for
recreational fleets to be included as well as additional years of data
for other fishery and survey fleets. Although more age data were
available, we elected to remove surface age reads from the model due to
known biases in addition to their removal having little effect on model
results of the 2015 assessment. Sensitivities to assumptions around data
choices are described in Section \@ref(sensitivities).

In addition to updated data, the process in which data contributes to
the likelihood was updated. The previous assessment applied equal data
weights to each fleet type across areas, and preferentially downweighted
age data based on the relative sample size compared to the number of
length samples by applying impact factors (i.e. lambdas) to composition
data less than one. Furthermore, the previous assessment did not apply
data weighting to conditional-age-at-length data data from the surveys.
In whole, these steps are not currently standard practice. For this
assessment we do not adjust lambda values. Rather we allow the data
weighting procedure to offset the contributions of age and length data,
including conditional-age-at-length data in the data weighting, while
checking that the sample sizes of composition data do not exceed the number
of fish actually sampled.

Lastly, a number of changes due to updating fixed parameter estimates
and prior values were made for this assessment compared to the 2015
assessment. These changes include updates to the steepness prior,
natural mortality prior, the fecundity relationship, and a change in
maturity from length-at-biological maturity to
age-at-functional-maturity based on additional work-up of maturity
samples by Melissa Head at \gls{nwfsc}. Changes to biological parameters
are more completely described in Section \@ref(biology). The effect of
these changes on model results in described below in the bridging
analysis.

### Bridging Analysis from the 2015 Benchmark Assessment

The exploration of models began by bridging from the 2015 benchmark
assessment model to the newest version of Stock Synthesis, version
3.30.21. Using the newest Stock Synthesis version resulted in a slightly
lower spawning output starting around 1995 (Figures
\ref{fig:bridge-exe-bio} and \ref{fig:bridge-exe-relbio}) due to a
higher value of catchability for the Washington late triennial survey.
From there, bridging from the 2015 benchmark assessment model to the
current base model followed five general steps:

1.  Update data inputs to reflect best information currently available.
    Data was updated by source (fishery independent, fishery
    independent) and type (catch, compositions, indices).
2.  Update life history information including natural mortality value
    and pattern, maturity, steepness, fecundity, and weight-length
    relationship.
3.  Update the structure of the modeled population, going from a spatial
    structure for recruitment to a single-area structure for
    recruitment.
4.  Reapply current data weighting practices.
5.  Update structure of selectivity.

To arrive at a final base model additional revisions were made after these five steps
to determine the best fit to the data. These include correcting an error in the generation of the triennial index of abundance, which was found late in the bridging process, and revisions to the fleet
structure, weightings, selectivity blocks, selectivity
parameterizations, and extending the period of early recruitment deviations.
<!-- These include fleet structure: mirror WA/OR twl, unmirror WA TWL/NTWL -->
<!-- Weightings: self explanatory -->
<!-- Blocks: Updating from Jim's simpler blocks -->
<!-- Selectivity parameterization: mirroring triennial selex and q, removing some sex selectivity for fleets, lowering some bounds on some selex parameters -->

A thorough description of the current base model is presented separately
below. This section is intended only to more clearly identify where
substantive changes were made from the previous benchmark assessment.
Sensitivities to many of the components within the steps above are
included in the Sensitivities (Section \@ref(sensitivities)).

Changes due to updating data streams are shown in Figures
\ref{fig:bridge-data-bio} and \ref{fig:bridge-data-relbio}. Updating the
fishery catch and composition data increases initial spawning output and
produces a steady increase in recent spawning output. Updating survey
indices and composition data results in a decreasing trend in spawning
output in the most recent years. Changes in life history parameter
values are shown in Figures \ref{fig:bridge-bio-bio} and
\ref{fig:bridge-bio-relbio}. Individually these changes produce
different estimates for initial spawning output, but collectively offset
and result in continuing the trajectory from the 2015 benchmark
assessment.

Changes due to altering the structure of natural mortality are more
substantial than changes to data and biology (Figures \ref{fig:bridge-Mcons-bio} and
\ref{fig:bridge-Mcons-relbio}). Assuming age-invariant natural mortality
results in a female natural mortality estimate of 0.076, which is larger at young ages but smaller at older ages than estimates using a ramp in natural mortality as applied previously. Although assuming age-invariant natural mortality results in similar recent spawning output and trajectory, doing so increases the estimate of $ln(R_0)$ and thus reduces the degree of recovery in spawning output
relative to unfished, as also shown within sensitivities from the 2015
benchmark assessment. Also similar to the findings from the 2015
benchmark assessment, changing the structure of the population from
spatial to non-spatial resulted in small changes in the current model
(Figures \ref{fig:bridge-spatial-bio} and
\ref{fig:bridge-spatial-relbio}). Updating the data weighting process to
current standard weighting practices and to account for the new updated
data however resulted in a decrease in the degree of recovery in
spawning output relative to unfished, due in part to a reduced estimate for female natural mortality to 0.065 in the coastwide model and 0.071 in the spatial model. 

Changes in how selectivity was modeled are shown in Figures
\ref{fig:bridge-selex-bio} and \ref{fig:bridge-selex-relbio}. Allowing
selectivity to be sex-dependent resulted in a large change in the degree of
recovery in spawning output relative to unfished, due to an increase in
the estimated value of female natural mortality. Other changes in
selectivity including unmirroring fleets and using an alternative parameterization of the double normal (three parameter instead of four) resulted in small changes. Various additional changes as described above result in the final base model. 

### Key Assumptions and Structural Choices

#### Definition of Fleets and Areas

To foster comparability between the coastwide base model and a
state-stratified model more similar to the 2015 base model, we retain
state-specific fleets for each fleet type from the 2015 assessment, with
the exception of survey fleets which are coastwide. All fleets are
ordered from south to north. That is, fleet 1 is California trawl, fleet
2 Oregon trawl, and fleet 3 Washington trawl, etc.

Fleets in the base model include:

\begin{enumerate}

\item[1-3] Trawl -- Bottom trawl gears, including shrimp trawl and mid-water
trawl.

\item[4-6] Non-trawl -- The non-trawl fleet includes a variety of sources of
directed and bycatch mortality in commercial fisheries.

\item[7-9] Recreational -- Including both private-rental and party-charter
modes.

\item[10-12] At-sea hake -- The at-sea hake fleet includes both tribal and
non-tribal at-sea hake fisheries.

\item[13-15] Foreign -- The foreign fleet operated 1966-1976, and does not
include any composition data. We assume that the foreign fleets have
selectivity equal to that of their respective trawl fleet.

\item[28] \gls{s-wcgbt}

\item[29] \gls{s-tri} early -- because canary rockfish sampling should be
    minimally impacted by the changes in the triennial survey that
    occurred in 1995, we chose to mirror selectivity and catchability
    between the early (1980--1992) and late triennial (1995--2004)
    fleets, but maintain two fleets to explore sensitivity to this
    assumption.

\item[30] \gls{s-tri} late

\item[31] Pre-recruit survey

\end{enumerate}

Fleets 16 through 27 were holdovers from the previous model structure and were not used.
<!-- The following state-stratified survey fleets were retained from 2015 in the model files and had -->

<!-- data updated to 2022 for comparison between the base model and a current -->

<!-- spatial model, but do not appear in the likelihood in the base model nor elsewhere in this report: -->

<!-- 16-18. State-stratified WCGBTS -->

<!-- 19-21. State-stratified triennial early -->

<!-- 22-24. State-stratified triennial late -->

<!-- 25-27. State-stratified pre-recruit -->

#### Initialization of the Model

We start the model in the first year of reconstructed catch data, 1892.
The population is assumed to experience no fishing mortality prior to
this year, and to start in a stable age-distribution. Early recruitment
deviations are estimated starting in the first model year. Main period
recruitment deviations begin in 1960 and end in 2022.

#### Conditional Age at Length Data {#caal}

Age-frequency data from the \gls{s-wcgbt} and \gls{s-tri} were compiled
as conditional age-at-length distributions by sex and year. The approach
consists of tabulating the sums within rows as the standard
length-frequency distribution and, instead of also tabulating the sums
to the age margin, the distribution of ages in each row of the
age-length key is treated as a separate observation, conditioned on the
row (length) from which it came.

This approach has several benefits for analysis above the standard use
of marginal age compositions. First, age structures are generally
collected as a subset of the fish that have been measured. If the ages
are to be used to create an external age-length key to transform the
lengths to ages, then the uncertainty due to sampling and missing data
in the key are not included in the resulting age-compositions used in
the stock assessment. The second major benefit to using conditional
age-composition observations is that in addition to being able to
estimate the basic growth parameters inside the assessment model, the
distribution of lengths at a given age that is usually controlled by the
CV of length at some young age and the CV at a much older age, are also
more reliably estimated. This information could only be derived from
marginal age-composition observations where very strong and
well-separated cohorts existed, and that are quite accurately aged and
measured; rare conditions at best. By fully estimating the growth
specifications within the stock assessment model, bias due to size-based
selectivity and length-stratified ageing is avoided, and known sources
of variation are included when estimating growth parameters.

### Model Parameters

#### Model Likelihood Components

The model contains four primary likelihood components:

1.  Fit to survey indices of abundance (included for fleets 28-31).
2.  Fit to length composition samples (included for fleets 1-12 with the
    exception of fleet 10, and fleets 28-30, i.e., all fishing fleets
    except the foreign fleets, California at-sea-hake, and the
    pre-recruit survey).
3.  Fit to age composition samples (marginal ages are included for
    fisheries, i.e., fleets 1-6 and 8-9, and 11-12, and conditional
    age-at-length samples are included for surveys, fleets 28-30).
4.  Penalties on recruitment deviations which range from 1892-2022 as
    well as penalties from prior likelihoods for parameters estimated
    with prior distributions.

Indices of abundance are assumed to exhibit lognormal measurement
errors, where the log-standard deviation from the model used to
standardize the relevant survey data is treated as an accurate estimate
of measurement errors. Length, marginal age, and conditional-age-at-
length samples are all assumed to follow a multinomial sampling
distribution, where the sample size is fixed at the input sample size
for the composition data, and where this input sample size is
subsequently weighted to account for additional sources of
overdispersion. Recruitment deviations are assumed to follow a lognormal
distribution, where the standard deviation of this distribution is set
to be 0.5. Priors for select biological parameters are described below.

#### Data Weighting

Length and age composition data for the commercial fleets started with a
sample size determined from the equation listed in Section
\@ref(comm-composition-data). The exception to this was for the
at-sea-hake fishery where input sample sizes were based on the number of
hauls. Input sample size for length and age composition data for the
recreational fishery was determined based on the number of estimated
trips (described in Section \@ref(rec-composition-data)). Length
composition data for the \gls{s-wcgbt} and \gls{s-tri} were based on
input sample sizes calculated as a multiple of the number of tows
(described in Section \@ref(survey-composition-data) and
conditional-age-at-length input sample sizes were set equal to the
number of ages within a given length bin.

The base model was weighted using the "Francis method", which was based
on equation TA1.8 in @francis_data_2011, as this method accounts for
correlation in the data (i.e., the multinomial distribution), and is
widely used among West Coast stock assessments. This formulation looks
at the mean length or age and the variance of the mean to determine if
across years, model explains the variability in the data. If the
variability around the mean does not encompass the model predictions,
then that data source should be weighted, and typically is
down-weighted. We applied four iterations of the Francis method when
data-weighting, which resulted in converged estimates. The weighting of
both the length and age composition was allowed to exceed one, and we
confirmed that data sources that were upweighted did not have a weighted
sample size above the number of fish sampled that would be a cause for concern. Weights for
conditional-age-at-length data, which were a direct count of the number
of available ages, were all less than one.

Sensitivities were performed examining the difference in the model fits
and results due to weighting using the McAllister-Ianelli Harmonic Mean
Weighting [@mcallister_bayesian_1997] method and are described in
Section \@ref(sensitivities). Note however that this method was found to
be inferior to the Francis method
[@punt_weighting_2017]. We also explored the Dirichlet Multinomial
Weighting [@thorson_model-based_2017], which is appealing because it
conducts the data weighting internally by estimating one additional
model parameter per data type and source and does not require additional
iterations. However, Dirichlet-multinomial weighting has not been
thoroughly simulation tested, and nearly all data weights for both
lengths and ages were estimated close to one. This was deemed
implausible and the method was not explored further.

#### Priors and Constraints on Parameters

Priors were used for fixed parameter values for male natural mortality
and steepness in the base model, as well as for the estimated parameter
value for female natural mortality. Details on the choice and value of
priors for these parameters are described in Section \@ref(biology) for
natural mortality and steepness and are not repeated here. We model
recruitment deviations around the stock-recruit relationship which are
penalized towards zero with standard deviation of $\sigma_R = 0.5$ and
constrained to sum to one over the main period. For estimated parameters, we set lower and upper bounds
to keep the minimization algorithms within a reasonable parameter space. We do not include any other
informative priors or structural constraints on parameters. 

#### Selectivity assumptions

Length-based selectivity is allowed to be dome-shaped for all surveys
and fisheries. Selectivity curves were estimated using a double-normal
pattern for every fishery and survey, except where selectivity was
mirrored among fleets. A double-normal selectivity pattern allows
flexibility in the model to estimate either asymptotic or dome-shaped
selectivity.

We specifically estimated three parameters for each selectivity curve,
including:

1.  Parameter 1: the minimum length at which selectivity is one (i.e.
    the "peak").
2.  Parameter 3: the width of the ascending curve for selectivity at
    lengths less than the peak, which controls the slope at which
    selectivity approaches the peak.
3.  Parameter 4: the width of the descending curve for selectivity at
    lengths greater than the peak, which controls the slope at which
    selectivity declines from the peak.

The parameter that controls the width over which selectivity is one
(parameter 2) was fixed at a low value. Parameters 5 and 6 were set to
have selectivity at small sizes start at zero (parameter 5 set to a low
value), and allow selectivity for larger sizes to be non-zero and decay
according to parameter 4 (parameter 6 set to -999). Setting parameter 6
this way simplifies the selectivity parameters and allows a single
parameter to govern the dome-ness of the selectivity shape instead of
two.

The foreign fishery does not have length or age composition samples
available. Therefore, selectivity is mirrored to the domestic trawl fishery for
each state. We also specify that commercial trawl selectivity is
mirrored between Oregon and Washington due to similar composition data
and the fact that many vessels cross the border while fishing and then
return to home ports to land their catch. These landings and,
particularly, composition data that is caught off of the coast of one
state and landed in the other is difficult to disentangle. Finally, we
specify that selectivity for the at-sea hake fleet is mirrored among all
three states.

We additionally allow selectivity to be time-varying for the trawl,
non-trawl, and recreational fleets. Time-varying selectivity in the
trawl fleet was blocked at 2000 (reflecting changes in fishing behavior
following the declaration of overfished status for `r spp` in 2000), and
at 2011 (reflecting a change in fishing behavior following the
implementation of individual transferable quotas). Time-varying
selectivity in the non-trawl fleet was limited by the sparseness of
composition data between the period when `r spp` was declared overfished
and when regulations relaxed in 2017. Based on patterns in the data and
discussion with state partners about regulation changes, we included
selectivity blocks for the Oregon and California non-trawl fleets at
2000 and then again at 2019, to reflect the general period of relaxed
regulations for the fishery initiated by the rebuilt declaration. The
Washington non-trawl fleet had very sparse composition data until 2017,
so for parsimony we did not apply any time blocking for this fleet.
Regulations for the recreational fleets across the coast have been
variable, based on seasonal or depth closures and bag limits. Time
blocks were applied to the California recreational fleet in 2004 and
again in 2016, corresponding to the imposition and lifting of the most
stringent regulations. Time-blocks were applied to the Oregon
recreational fleet in 2004 and again in 2014, and for the Washington
recreational fleet in 2006 and again in 2020, which correspond roughly
to the periods where depth restrictions were imposed (for the first
block) and again lifted (for the second block). For each break-point
change in selectivity, we re-estimate all three parameters.
Sensitivities to selectivity assumptions include the use of a four
parameter parameterization, fixing fleets to have asymptotic
selectivity, and simplified blocking (Section \@ref(sensitivities)).

Early model explorations around structuring natural mortality indicated
the data did not support estimating higher female natural mortality than
fixed male natural mortality when natural mortality was constant across
ages. This was somewhat surprising given the observed male-skewed
sex-ratios at age among trawl and survey landings. There appeared to be
lack of support for young females, in particular, to have higher natural
mortality. When age-varying natural mortality was assumed, as done in
previous stock assessments for `r spp`, higher values for older female
natural mortality were estimated. We found that by allowing sex-dependent
selectivity in parameter 4, which governs how steeply selectivity
declines at larger sizes, the estimate for female natural mortality increased and the fit to the data improved. Sex-dependence
on other selectivity parameters was explored, but parameter 4 had the
largest per-parameter improvement in likelihood, and was large enough to
warrant the additional number of selecitivity parameters. We therefore
estimate sex-dependent selectivity in the base model, modeled as a
logarithmic female offset to parameter 4 for all fleets and blocks with
sex-specific composition data. Sensitivity to excluding sex-dependent
selectivity is described in Section \@ref(sensitivities).

#### Stock Recruitment Function

In this assessment ln(R~0~) (the natural logarithm of unfished recruitment) was estimated, while steepness
was fixed at its prior mean of 0.72. Lognormal deviations from the
standard Beverton-Holt stock-recruit relationship were estimated from
1892--2022 with a fixed $\sigma_R$ value of 0.5. There is limited
information regarding recruitment prior to 1960 but deviations are
estimated in the base model to account for uncertainty around the
unfished condition to a degree consistent with estimated variability in
recruitment. The early deviations are estimated from the beginning of
the model period until 1960 in order to fully propagate uncertainty in
recruitment and allow population age-structure to represent plausible
deviations from the equilibrium at the start of composition data. Main
phase recruitment deviations are estimated beginning in 1960, shortly
before composition data becomes available in 1968.
