## Base Model Results

### Parameter Estimates

*Ensure WL1 for male and female and eggs scalar are sceientific method*
*Set priors of unestimated values to -99 uniformly*
*Remove the triennial late line as its mirrored*

The base model parameter estimates along with approximate asymptotic standard errors (SD column) are shown in Table \@ref{tab:params}. This table enumerates a total of 241 estimated parameters. These include one parameter for $R_0$, one parameter for female natural mortality, 10 parameters describing growth, one parameter for survey catchability in the \gls{s-tri}, one parameter for extra variability for the pre-recruit survey, 71 parameters for length-based selectivity and block along with 25 parameters for sex-dependent selectivity, and 131 recruitment deviations.

#### Biology parameters

The estimates of growth parameters by sex varied relative to the externally estimated starting values (Table \ref{tab:params}).  The length-at-age 1 for both sexes were less than the external estimates using the survey age data while the $L_\infty$ estimates for both sexes were higher than the external estimates. The estimated $k$ for females and males was greater than the values estimated externally, with the value for females being more similar. Although estimated growth differed from external estimates, external estimates were within the 95 percent confidence interval (with males near the lower edge) given the estimated uncertainty from the model (Figure \ref{fig:mod-est-len-age}). The coefficition of variation in in growth was assumed to be function of length at age. Although estimates for the coefficient of variation at $L_\infty$ were approximately half those at length-at-age 1 for males and females, which given the estimates for length at older and younger fish, results in greater variability in length at larger sizes. 

####	Selectivity
Length-based selectivity curves were estimated using a double-normal pattern for every fishery and survey, and time-block, except where selectivity was mirrored among fleets. A double-normal selectivity pattern allows flexibility in the model to estimate either asymptotic or dome-shaped selectivity. Estimated selectivity curves are shown in Figure \ref{fig:comm-selex-female}-\ref{fig:noncomm-selex-female} for females and Figures \ref{fig:comm-selex-male}-\ref{fish:noncomm-selex-male} for males, with selectivity parameters provided in Table \ref{tab:params}. Nearly all fleets show a strong dome-shaped pattern with the execption of the Oregon and Washington trawl fleet from 2000--2011, the Oregon non-trawl fleet prior to 2000, and the \gls{s-tri}. The amount of unavailable biomass for `r spp` is large in the early time period, declines during the period of peak exploitation, and then increases since 2000 (Figure \ref{fig:unavail-bio}). 
**Add statement about sensitvity to having a full asymptotic fleet to teh above**

For the trawl fleets, the length at peak selectivity is greatest prior to 2000, with the California peak at 46 cm and the mirrored Oregon and Washington peak at 49 cm. Selectivity shifts towards smaller fish in recent time periods between 3--6 cm depending on the fleet and time block. The pattern of dome-ness between time periods is stronger in California in recent years whereas for Oregon and Washington the curve tends to shift towards smaller fish, and to an asymptotic pattern between 2000-2011. The foreign fleets are mirrored to the trawl fleets and have the same selectivity curves. 

For the non-trawl fleets, the patterns in selectivity are more variable, reflecting the sparseness of the compositional data. In California, selectivity for smaller fish than in the trawl fleet, with a peak at 36 cm. The range of lengths selected is more compressed but has shifted towards larger fish by 2 cm in the most recent years compared to before 2000. The selectivity curve has changed the most over time in Oregon. Prior to 2000, the peak in selectivity was 55 cm, lowered to 33 cm in the 2000s, and increased to 45 cm in the most recent period. The Washington non-trawl fleet has sparse data so has constant selectivity across time, and has a peak at 47 cm.  

The at-sea-hake fishery has mirrored selectivity across each state given the similarities in the fishery along the coast. The selectivity is more narrow than either the trawl or non-trawl fleets, with a steep increase around 40 cm and peak at 44 cm. No time-varying selectivity is applied to the at-sea-hake fishery.

For the recreational fishery, the length at peak selectivity is shifted towards smaller fish compared to the commercial fleets. Selectivity increases sharply and reaches a peak of 29 cm in California, 30 cm in Oregon and 34 cm in Washington. For all fleets, selectivity in the earlier time periods is shifted towards smaller fish. Selectivity for Washington shifts greatly in 2021-2022 to a peak of 48 cm, which may be due in part to being the last two years whereas the recent block for other fleets includes earlier years. All recreational fleets show strong dome-ness, with the greatest decline during the period of non-rentention. 

Among surveys, the \gls{s-wcgbt} and \gls{s-tri} are estimated to have a slowly increasing selectivity curve across  a wide range of lengths; starting at very small sized and increasing to a peak near 43--44cm. This likely reflects the spatial and bathymetric coverage and non-targeting nature of the survey design compared to the fishery. Selectivity for the \gls{s-wcgbt} declines for larger individuals whereas for the \gls{s-tri} selectivity is nearly asymptotic. No time-varying selectivity is applied for the surveys, and the \gls{s-tri} is mirrored across the early and late period.

For all fleets and surveys, male selectivity shows a greater dome-ness than females. This is likely compensating for a lower availability of large females given that their natural mortality estimate is larger than males, as opposed to females being more unavailability to the fishery. Thus, greater selectivity for females allows them to be selectied for at a larger size prorportional to their occurrence in the population, which is less than males due to greater mortality.



**Possibly move elsewhere to where we describe model structure**
We specifically estimated three parameters for each selectivity curve, including
	1. the minimum length at which selectivity is one (the “peak”), 
	2. the width of the ascending curve for selectivity at lengths less than the peak, 
	3. the width of the descending curve for selectivity at lengths greater than the peak plus the width of the dome.
We additionally estimate a change in selectivity for the trawl and non-trawl fisheries between 1999 and 2000 (reflecting changes in fisher behavior following the declaration of overfished status for canary rockfish in 1999), and another change in selectivity for the trawl fishery between 2010 and 2011 (reflecting a change in fisher behavior following the implementation of individual transferable quotas starting in 2011).  For each break-point change in selectivity, we re-estimate all four parameters.  Hence, there is no information regarding selectivity that is shared among time blocks.





Length-based selectivity curves were estimated for the fishery and survey fleets. The majority of fishery and survey fleets were parameterized using the double normal selectivity parameterization in SS3 except for the commercial dead and `r hkl` fleets that were parameterized as logistic asymptotic selectivity. The estimated selectivities are shown in Figure \ref{fig:est-selex}. The selectivity for the commercial dead fleet was estimated to be asymptotic and constant across the model period. The commercial live fish fishery selects fish at small sizes with dome-shaped selectivity. Both recreational fleets were estimated to have dome-shaped selectivity for each selectivity period with the CPFV fleet selecting a higher portion of large fish in the final time block relative to the PR fleet. The peak in selectivity for both the CPFV and PR fleets in the final time block were estimated at `r round(model$estimated_non_dev_parameters[rownames(model$estimated_non_dev_parameters) == "Size_DblN_peak_Rec_CPFV(3)", "Value"], 1)` and `r round(model$estimated_non_dev_parameters[rownames(model$estimated_non_dev_parameters) == "Size_DblN_peak_Rec_Private(4)", "Value"], 1)`, respectively.  While the recreational fleets selects a wide range of sizes, the estimated peak of selectivity for both fleets were notably less than the size-at-50 percent maturity of 34.1 cm.

The CCFRP Hook and Line estimated peak selectivity around 40 cm with selectivity decreasing for larger fish. The `r hkl` estimated asymptotic selectivity only reaching maximum selectivity for the largest fish. The `r wcgbt` which samples soft bottom via trawl gear had relatively low selectivity for the majority of sizes with only selectivity peaking at the largest sizes. Finally, the estimated length-based selectivity from the CPFV cooperative collection and Pearson Research study was asymptotic with full selectivity for fish of 35 cm and larger.  Both of these last two fleets included only lengths and ages to inform growth estimation. As noted in the Growth Data, Section \ref{growth-data}, that describes these data, the estimated selectivity for the samples collected by the CPFV vessels participating in the cooperative sampling program was distinctly different than that from the CPFV fleet operating `r area` as a whole. This is likely due to the areas accessible and trip type (half-day, three-quarter day, or overnight) between the CRFS districts 1 and 2 within this area where all vessels participating in the collaborative collections operating out of district 2 (see Appendix Section \ref{cpfv-samples} for additional information about the CPFV trip types across California).

The catchability for each of the surveys was analytically solved comparing observed to expected vulnerable biomass across all years. The analytical values for catchability were very small given the survey methodologies and are reported in Table \ref{tab:params} in log-space. Additional fishery and survey index variability, process error added directly to each year's input standard deviation for the were estimated within the model. The model estimated the largest added variance of `r round(model$parameters[model$parameters$Label == "Q_extraSD_Rec_Private(4)", 3], 3)` for the recreational PR fishery index. In contrast the model estimated only limited additional variability in order to fit the recreational CRFS CPFV fishery-dependent index of abundance (`r round(model$parameters[model$parameters$Label == "Q_extraSD_CRFS_CPFV(8)", 3], 3)`). The model fit the trends in the `r hkl` index of abundance relatively well with only a small amount of added variance  being estimated to fit this time series (`r round(model$parameters[model$parameters$Label == "Q_extraSD_NWFSC_HKL(7)", 3], 3)`). The model estimated an added variance of `r round(model$parameters[model$parameters$Label == "Q_extraSD_CCFRP(5)", 3], 3)` to the index from the CCFRP Hook and Line survey.

The time series of estimated recruitments and annual recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. Years with the highest recruitment deviations were estimated to have occurred in 2010 and 2013 with the lowest being estimated in 2018 and 2019. There is limited information regarding recruitment prior to 1980 but are estimated in the base model to account for uncertainty around the unfished condition. The historical age data from the CPFV fleet from 1975 were identified to have a disproportional influence on estimated recruitment in the late 1960s relative to all other data sources in the model. These data resulted in a sharp spike in recruitment during these years that was substantially higher than any other year in the model.  Given that these estimates were extreme and appeared to be informed by limited data, the decision was made to reduce the influence of this one year of limited age data for model stability (lambda value of 0.10 for these data). Sensitivities showed that the overall ending model estimates were not impacted by this decision (show below in Sensitivities Section \ref{sensitivities}). Estimated recruitment deviations during the early years when compositional data began, 1975 - 1995, have relatively high uncertainty intervals indicating lack of support for clear strong or poor recruitment years across data sources. Recruitment deviations after 2017 are relatively uncertain but with large negative recruitment deviations. Recruitment in 2021 and 2022 are not estimated and fixed to be equal to the spawner-recruit curve values (Figure \ref{fig:bh-curve}). The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias-adjust}.






























####	 Stock-recruit parameters
In this assessment the log of R0 was estimated, while steepness was fixed at its prior mean of 0.773.  This prior was estimated using a likelihood profile approximation to a maximum marginal likelihood mixed-effect model for steepness from ten Category-1 rockfish species off the U.S. West Coast (Pacific ocean perch, Boccaccio, canary, chilipepper, black, darkblotched, gopher, splitnose, widow aurora, and yellowtail rockfish).  Both northern and southern assessments of black rockfish were used, although the log-likelihood for each was given a 0.5 weighting, to ensure that the together these two assessments had an equal weighting to the other species. This likelihood profile model is intended to synthesize observation-level data from assessed species, while avoiding the use of model output and thus improving upon previous meta-analyses (Dorn, 2002; Forrest et al., 2010). This methodology has been simulation tested, and has been recommended by the PFMC SSC for use in stock assessments. 

We estimate lognormal deviations from the standard Beverton-Holt stock-recruit relationship for the period between 1870 and 2011. Deviations are penalized in the objective function, and the standard deviation of the penalty (σR) is specified as: 

*INSERT EQUATION HERE*

Where r̂y is the estimated recruitment deviation in year y, v ̂(r ̂_y) is the estimated standard error-squared of r̂y, the first summand on the right-hand side represents the sample variance of the recruitment deviations; the second summand on the right-hand side represents the average standard error-squared of recruitment deviations, as recommended in the “Estimating σR“ subsection of Methot and Taylor (2011) and correcting for their typo. 

‘Main’ recruitment deviations were estimated for modeled years that had information about recruitment (as determined from the bias-correction ramp), i.e., 1960-2014. We additionally estimated ‘early’ deviations between 1933 and 1959 so that age-structure in the year of first compositional data (1968) would deviate from the stable age-structure for all ages with data (i.e., ages 1-35) to a degree that is consistent with estimated variability in recruitment. This resulted in an estimate of B0 that is also consistent with estimated variability in recruitment given the assumption that initial catch was negligible. 

Recruitment deviations are also bias-corrected following Methot and Taylor (2011), by providing a proportion of the total bias correction for year y that varies depending upon how informative the data are about ry. Specifically, we used r4ss (Taylor et al., 2012) to estimate a five-parameter bias-correction ramp (Figure 92).



####	Summary time series of population status and exploitation rate
Summary time series are listed in Table 23, and visualized in Figure 102 through Figure 106.  These summaries indicate that fishing mortality peaked in 1991-1992 when the stock was being overfished (FSPR > 1.7), and that overfishing ceased (FSPR < 1.0) in 2000, after the stock was declared overfished.  Spawning output across all three strata reached its lowest level in 1994 (relative spawning output = 13.7%), and has since steadily recovered (relative spawning output = 0.552 in 2014).  Recovery has been aided by strong recruitment in 2001-2003, 2007, and 2010, and the pattern of reduced recruitment 2003-2006 is consistent with many other groundfishes in the California Current (J. Thorson et al., 2013).  Recovery (defined as the year of lowest spawning output, Figure 101) began earlier in Washington than either Oregon or California, and relative spawning output in Washington (Figure 103) is estimated to be higher than in Oregon or California in 2014.  California is estimated to have experienced the lowest level of relative spawning output during the historical period of any state (occurring in 1999), and is estimated as having the lowest relative spawning output in 2014.

####	Estimated stock-recruit relationship
The time series of stock-recruitment residuals (Figure 107) suggests how little information is available to estimate recruitment deviations for canary rockfish, where few years have a 95% confidence interval that does not overlap zero, and where only one year (1980) has a deviation whose absolute value is greater than one.  The time-series indicates that main recruitment deviations start around the period when there is information to estimate annual variation in recruitment.    

A plot comparing spawning output vs. recruitment (Figure 108) shows that the highest recruitment occurred primarily before intensive fishing (1962, 1968, 1979). It also shows the high degree of compensation that is expected for canary rockfish given the prior on steepness that was estimated for rockfishes in 2015.

Finally, a plot of the fraction of total recruitment among spatial strata (Figure 109) shows considerable spatial variation in recruitment.  This variation is consistent with spatial variation in the center of gravity for pre-recruits seen in the coast-wide pre-recruit survey (J. Field, pers. comm.).  Oregon generally has the largest portion of recruitment (with an expectation approaching 50%), while Washington is expected to have slightly more than 30% of recruitment, and California is expected to receive approximately 20% of recruitment.  

####	Historical Harvest
In 2000, canary rockfish were declared overfished and the annual harvest limits since have been determined by a rebuilding plan.  An update assessment with an updated rebuilding plan was last performed in 2011.  The SPR harvest rate for rebuilding was set equal to 88.7% resulting in ACLs of 102, 107, 116, and 119 metric tons for 2011-2014 respectively.  The total landings including discard have been well below the annual ACLs since 2009.  The total attainment of the ACL between 2009 and 2014 has ranged from a 31 (2011) to 60% (2009).  

The total catch assumed in the model included estimated discards by the trawl and non-trawl fisheries.  The annual discard amount was estimated based upon assumed discard rates (Table 8).   Therefore, all estimates of fishing intensity (FSPR) and yield are based on the treatment of removals as landings and dead discards.  


### Fits to the Data

### Population Trajectory





