## Model Diagnostics

### Convergence status

The base model has a final gradient of \<0.00001 and the hessian is determinant. We therefore conclude that the parameter estimates represent a local minimum and near enough to a global minimum so as not to differ appreciably in results. No parameters are at or within 5 percent of a boundary and one parameter pair has a high correlation coefficient between 0.90 and 0.95.

#### Evidence of search for global convergence

A search for global convergence was conducted multiple times. Model convergence was first determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the estimation routine found a smaller likelihood. Starting parameters were jittered using the jitter function built into Stock Synthesis, using a jitter fraction of 0.05. This was repeated 60 times with no runs returning to the base model likelihood and one returning to a likelihood that was 2 likelihood units lower. The run with improved likelihood had one parameter on a bound which was fixed before an additional 50 runs were conducted jittering from the initial parameter estimates from the improved likelihood model. This second jitter analysis had three runs return to the improved likelihood estimate, four runs just above, and one run that was one likelihood unit lower. A third jittering analysis was repeated 50 times, jittering from the initial parameter estimates from the twice-improved model, with five runs returning to the twice-improved likelihood value and one just above.

Although the base model indicates an overall global minimum can be obtained that is lower than the base model likelihood, we keep with the original base model. The primary reason for this is that the lowest likelihood model after two jitter analyses had near perfect (\> 0.99) correlation among three selectivity parameters, which was concerning. Secondarily, all three models (the current base and the two models with lower likelihood from the first and second jitter analyses) were similar in trajectory (Figure \ref{fig:jitter_compare}). Lastly, profiles of key parameters did not show evidence of instability, suggesting improvements across the likelihood surface did not greatly change model dynamics. The conclusion from the jittering analyses indicates that a lower global minimum is attainable, but that the likelihood surface of the base model (and subsequent jittered models) is flat around the maximum likelihood estimate. Models from the jitter analyses and converge to estimates with similar model behavior that do not greatly change model conclusions. We therefore proceed with the current base model.

### Comparison with similar stocks and species

The recent assessments for canary rockfish in Canada have shown a decline and subsequent rebuilding of the stock in Canadian waters (COSEWIC, 2007; DFO, 2010; Stanley et al., 2005), where the magnitude of decline and the timing of the commencement of rebuilding are generally similar to the current assessment. Canadian assessments have been based upon trends in abundance in the southern portion of the Canadian stock. The Canadian model (COSEWIC 2007) was premised on a maximum age of 84 yr., and available age data clearly showed the decreased prevalence of old females relative to old males, thus supporting the increase in female natural mortality that is also used in our base model. The Alaska assessment (Green et al., 2014) has historical been based upon density estimates from manned or remotely operated vehicles, and therefore contains no information regarding catchability for bottom trawl surveys, natural mortality rates, or sex-specific age structure.

### Sensitivity Analyses {#sensitivities}

The base model contains substantial uncertainty in both how data were processed, and structural assumptions made. We test senstivity to a number of these assumptions. In general, structural assumptions regarding how productive the population is and how the model handles the relative lack of old females in age composition data led to the strongest changes in model outputs (Figure \@ref(fig:sens-summary)). All sensitivities led to relatively similar estimates of growth parameters, indicating growth is well-estimated in the model and we do not discuss it further (Tables \@ref(tab:data-sens)-\@ref(tab:prod-sens)). We divide the sensitivities into four groups: how data are prepared, how data are weighted, selectivity and catchability, and population productivity.

#### Data choices

<!--# Just needs figures and tables -->

Compiling data for the assessment model required a number of choices and assumptions. The following sensitivity models fall under data choices:

-   No sparse comps: exclude all year-fleet combination of length and age composition data with input sample sizes less than five. Complete one iteration of Francis data weighting.

-   Pre-recruit data: include pre-recruit survey index from 2010, 2012, and 2022 which had more limited sampling.

-   Released lengths in: include lengths of released fish in California and Oregon recreational composition data

-   Canada catch: add catches from the West Coast of Vancouver Island to Washington trawl and non-trawl fleets

-   Catch SE 0.1: Increase the uncertainty in input catches from 0.05 to 0.1. This is done in lieu of manually changing catch streams to "low" and "high" scenarios. **could add this to data weighting. I had it here because I wanted the two catch sensitivities together.**

Overall, decisions with respect to input data had a low impact on model outcomes (Table \@ref(tab:data-sens), Figures \@ref(fig:data-ssb-compare), \@ref(fig:data-bratio-compare)). Sensitivities generally led to similar current biomass levels, but varying estimates of unfished biomass, leading to somewhat different depletion estimates. Still, in all cases depletion in 2023 was within the 95% confidence interval of the base model. All models generally produced similar estimates of female natural mortality. Including Canadian catches predictably increased the population scale substantially, outside of the 95% confidence interval. Because Canadian fishing continued during the period `r spp` was declared overfished in the U.S., including Canadian catches also resulted in a more muted recovery and lower depletion in 2023.

#### Data weighting

<!--# Just needs figures and tables -->

The assessment model contains data from a variety of sources, some of which are expected to be more informative than others. Sampling units from these different data sources are not necessarily comparable (e.g., an observation from a survey index versus an observation of a fish length). Data weighting procedures are objective algorithms that can be used to assign weights to different data sources to optimize the fit of the model to the data. The following sensitivity models fall under data weighting:

-   McAllister-Ianelli data weighting: Use the algorithm suggested by McAllister and Ianelli [-@mcallister_bayesian_1997] instead of Francis and Hilborn [-@francis_data_2011]

-   No extra SD: Do not estimate an extra standard deviation for the pre-recruit survey index. This means the pre-recruit survey cannot be down-weighted to allow for better fitting of other data sources.

-   Francis Ages X10: Upweight all age composition samples 10x relative to the weight assumed in the base model

-   Francis Length Weights X10: Upweight all length composition samples 10x relative to the weight assumed in the base model

The choice of data weighting algorithm and the extra standard deviation on the survey index were not influential (Table \@ref(tab:weight-sens), Figures \@ref(fig:weight-ssb-compare), \@ref(fig:weight-bratio-compare)). Data weights for the McAllister-Iannelli method compared to those used in the base model are in Table \@ref(tab:dw-compare) and show the McAllister-Iannelli weights the composition data less relative to the Francis method. Eliminating the survey extra standard deviation did result in a larger survey index negative log-likelihood (worse fit), supporting the choice of its estimation. Increasing the weight of the age data led to a lower population scale (outside of the 95% confidence interval of the base model), lower depletion in 2023, and a trajectory where the population begins declining after fishing effort increases following the lifting of the overfished designation. Increasing the weight of length composition data essentially does the opposite, increasing the unfished biomass and 2023 depletion (both outside of base model 95% confidence interval), and leading to a steep and rapid recovery of the population in recent years. While age and length composition likelihoods are not comparable among these scenarios, the survey index negative log-likelihood increases both when upweighting lengths and when upweighting ages, indicating worse fits in both cases. Upweighting the length and age data by a factor of ten is not meant to be a realistic scenario, but rather to illustrate how different data sources influence model results. All data weighting scenarios generally produced similar estimates of female natural mortality were generally similar.

#### Selectivity and catchability

<!--# Just needs figures and tables -->

There are numerous possible ways to parameterize selectivity in a stock assessment model, and its correct parameterization is generally a major source of structural uncertainty. Selectivity is of particular importance for `r spp` because it is unknown whether the absence of old females in composition data is due to a lack of availability, old females are available but experience higher natural mortality rates than their male counterparts, or some combination of the two. Catchability represents the fraction of the population that is available to a survey. It can either be estimated as a model parameter with uncertainty, or analytically calculated within the model. Because the base model mirrors catchability between the early and late triennial periods, catchability for the triennial survey had to be estimated. The following sensitivity models fall under selectivity and catchability:

-   No sex selectivity: Assume males and females have the same three-parameter double-normal selectivity curve (applies to all fleets)

-   Simpler blocks: Remove all selectivity blocks for California trawl, California non-trawl, California recreational, and Oregon recreational. Retain only one block for Oregon non-trawl (2000-2019) and one block for Washington recreational (2021-2022). MORE RATIONALE?

-   WA NTWL asymptotic: Assume the Washington non-trawl fleet has asymptotic selectivity. The base model assumes all fleets have dome-shaped selectivity, which allows for a significant amount of cryptic biomass. The Washington non-trawl fleet was deemed most likely to have asymptotic selectivity because 1) it fishes in untrawlable habitat where larger fish likely reside, and 2) the average size of canary rockfish tends to increase northward along the coast

-   Float Q: Move all triennial data into the early triennial period and float Q (i.e., calculate it analytically). Complete one iteration of Francis data weighting.

-   Unmirror tri: Estimate separate selectivity for early and late triennial. Calculate two Q values analytically, one for each period.

Eliminating sex-specific selectivity was one of the most influential sensitivities tested, across all groups of sensitivity analyses (Table \@ref(tab:selec-sens), Figures \@ref(fig:selec-ssb-compare), \@ref(fig:selec-bratio-compare)). Eliminating sex-specific selectivity resulted in a higher unfished biomass and lower depletion in 2023 (below the minimum stock size threshold), both outside the 95% confidence interval of the base model. The estimate of female natural mortality goes down substantially to a value close to the fixed value of males. Fits to age and length composition data deteriorate, as expected, but the survey negative log-likelihood also increases by approximately 20 units, indicating a worse fit to survey indices, particularly the \gls{s-wcgbt}.

Treatment of the \gls{s-tri} was generally not influential on model estimates, while simpler selectivity blocks and including an asymptotic selectivity curve for the Washington non-trawl fleet were moderately influential (Table \@ref(tab:selec-sens), Figures \@ref(fig:selec-ssb-compare), \@ref(fig:selec-bratio-compare)). Both of the latter two scenarios resulted in higher estimates of unfished biomass. Simplifying selectivity blocking led to a more rapid recovery over the past two decades, and a 2023 depletion near the target of 40%. Assuming the Washington non-trawl fleet has asymptotic selectivity led to a depletion closer to that estimated in the base model, but the population trend increased at a consistent rate in recent years, rather than leveling off as in the base model. Other than eliminating sex-specific selectivity, all sensitivities in this group led to similar estimates of female natural mortality. Simplified blocking and an asymptotic non-trawl fleet both increased the negative log-likelihood. Unmirroring the triennial, which is associated with estimating three additional parameters, only decreased the negative log-likelihood by 3 units, supporting mirroring the two time periods. Fully combining the triennial and floating catchability does not have a comparable likelihood to the base model because it was re-weighted.

#### Population productivity

The base model makes a number of structural assumptions related to population productivity. These assumptions are known to be influential and drive how quickly a population will recover from an overfished state. The following sensitivity models fall under population productivity:

-   Estimate h: Estimate steepness of the stock-recruit relationship

-   Estimate male M: Estimate male natural mortality

-   Single M: Fix female natural mortality to the median of the prior distribution, similar to males.

-   M ramp: Fix female natural mortality at young ages to the median of the prior distribution, similar to males. Assume, similar to recent assessments, natural mortality increases linearly from age 6 to 14, and estimate female natural mortality for ages 14 and higher. This ramp roughly follows the maturity curve, thus presuming that higher female natural mortality rates are associated with maturation and spawning.

Structural assumptions in the model that determine population productivity were strongly influential on derived model outputs (Table \@ref(tab:prod-sens), Figures \@ref(fig:prod-ssb-compare), \@ref(fig:prod-bratio-compare)). The model estimates internally steepness to be 0.835. This indicates expected recruitment of the population remains high even at low spawning outputs, and led to a similar estimate of unfished biomass, but a more rapid recovery in the 2000s and 2010s, leading to a depletion near the target of 40%. Female natural mortality was similar to the base model. The likelihood increased by two units despite estimating one additional parameter, indicating that the model was likely close to, but quite at, the global optimum for this scenario.

The model internally estimated male natural mortality to be 0.0889 yr^-1^, much higher than the fixed value of 0.0643 yr^-1^ (Table \@ref(tab:prod-sens), Figures \@ref(fig:prod-ssb-compare), \@ref(fig:prod-bratio-compare)). When the model freely estimated male natural mortality, the estimate of female natural mortality also increased to 0.0975 yr^-1^. These are associated with maximum ages of 61 and 55 according to the natural mortality prior used [@hamel2022development]. This increase in natural mortality for both sexes resulted in a similar estimate of unfished biomass, but as with the estimation of steepness, a much steeper and more consistent increase in population size in recent years and a depletion in 2023 well above the management target (51%). Although the gradient for this sensitivity was on the order of 10^-5^, the negative log-likelihood increased by over 40 units relative to the base model, despite the flexibility of estimating an additional parameter. Thus, the model may not have reached a global optimum, possibly because there is not sufficient information in the data to estimate two natural mortality rates.

Assuming that female natural mortality increases as they reach sexual maturity rather than remaining constant throughout their lives led to a slightly lower unfished biomass than the base model (still within the 95% confidence interval) and a higher depletion in 2023 (close to the management target; Table \@ref(tab:prod-sens), Figures \@ref(fig:prod-ssb-compare), \@ref(fig:prod-bratio-compare)). The estimate of natural mortality for only old females was higher than the estimate of natural mortality for all females (0.0904 versus 0.0756 yr^-1^, respectively). The total likelihood was identical between this senstivity and the base model. They also estimate the same number of parameters. Together, this indicates little support within the data to differentiate between the two biological hypotheses.

Finally, fixing female natural mortality at the median of the prior used for males resulted in a substantially higher estimate of unfished biomass (outside the 95% confidence interval of the base model), and a much more muted recovery, leading to a lower spawning output in 2023, and a significantly lower depletion (outside the base model 95% confidence interval and below the minimum stock size threshold; Figures \@ref(fig:prod-ssb-compare), \@ref(fig:prod-bratio-compare)). The direction of these results is expected, as the fixed rate is 15% lower than the rate estimated in the base model, indicating a less productive population.

#### Sensitivities not included in document

Excluding all length composition samples from the Deb Wilson-Vandenberg data and assuming the pre-recruit survey occurs after density-dependence instead of before had minimal impacts on model outputs. Dirichlet-multinomial data weighting, assuming \gls{s-wcgbt} has asymptotic selectivity, and estimating a fourth parameter of the double-normal selectivity curve for all fleets led to models that did not converge (final gradient \>0.01 for Dirichlet-multinomial, gradient \>100 for remainder).

### Retrospective Analysis

<!-- Brian has updated this section -->

A five-year retrospective was done by successively removing years of data to obtain models with ending years ranging from 2017 to 2021. The retrospective analysis shows a slight negative retrospective bias in that initial spawning output and recent spawning output generally decline as more years of data are removed, but changes are within the uncertainty intervals of the base model (Figure \ref{fig:retro_bio}). The magnitude of change in initial and recent spawning output differs; the removal of two years of data causes an increase in spawning output relative to unfished, with all other runs similar in pattern to the base model (Figure \ref{fig:retro_relbio}). Estimates of Mohn's $\rho$ [@mohn_rho_1999], which measure the magnitude of retrospective bias are -0.25 over all years (average of -0.05 per year) for spawning output and -0.04 over all years (average of -0.008 per year) for spawning output relative to unfished. According to [@hurtado-ferro_looking_2015], Mohn's $\rho$ values on a per-year basis of less than -0.15 are not cause for concern, but should not be taken as lack of true bias.

### Likelihood Profiles

We use likelihood profiles to assess the support of the data for the estimation of different key parameters (steepness, average unfished recruitment, and female and male natural mortality rates). A likelihood profile over a parameter fixes that parameter to a range of values, and then freely estimates the rest of the base model at each fixed value. We separate the likelihood profile into contributions from different data sources to assess the degree to which different data sources agree or conflict. Across all profiles, there is a common conflict within the length composition data where composition data from trawl gears generally supports a more productive population (high ln(R0), high steepness, high natural mortality), and composition data from non-trawl gears, both commercial and recreational, generally supports a less productive population.

Low values of ln(R0) (the natural logarithm of unfished recruitment) maximize the age composition likelihood, the recruitment penalties are minimized by slightly higher values of ln(R0) than the full model estimates, and the indices support a value of ln(R0) close to the full model estimate (Figure \ref{fig:r0-profile}). The Oregon recreational fleet most strongly drives the age composition likelihood, but age composition data from many fleets support lower population scales. The length composition data are relatively uninformative in determining population scale because of conflicts within the length composition data between non-trawl gears (especially Oregon non-trawl and Washington recreational) which favor low values, and trawl gears (especially California trawl, Oregon trawl, and Washington at-sea hake) which favor larger values. The survey index likelihood is mainly informed by the early and late triennial index, which show the most contrast over their survey period.

The likelihood profile over steepness indicates that a value higher than that fixed in the model, around 0.85, maximizes the full likelihood (Figure \ref{fig:h-profile}). This similar to the internally estimated value of steepness (0.835) found in section \@ref(population-productivity). We do not consider that to be plausible for a long-lived species such as canary rockfish and therefore fix steepness at the mean of the prior distribution for rockfishes ($h=0.72$). The profile is most strongly informed by recruitment penalties. There is some conflict between length data, which favor low steepness, and age data, which favor high steepness. Again, length data show a conflict between trawl fleets, which in this case favor higher steepness values, and non-trawl gears that favor lower steepness values. The survey index favors steepness relatively close to the fixed value, around 0.7, and this is generally informed by all surveys.

The female natural mortality likelihood profile is most strongly driven by length data, with some influence of age data and recruitment penalties (Figure \ref{fig:female-m-profile}). Survey indices contain little information to inform female natural mortality estimation. The length composition data once again shows a conflict between trawl gears supporting higher natural mortality and non-trawl gears supporting lower natural mortality. However, notably, Oregon recreational length compositions also support higher female natural mortality.

The likelihood profile over male natural mortality shows relatively little information from the data to support its estimation, confirming the choice to fix it to the median of the prior distribution (Figure \ref{fig:male-m-profile}). The profile is also minimized at a lower value (around 0.065-0.070 yr^-1^) than the sensitivity that estimates male natural mortality (section \@(population-productivity)) , providing further evidence that the sensitivity may not have reached a global optimum. The profile is minimized close to the fixed value in the base model. Unlike females, recruitment penalties are most influential on the male natural mortality profile. There is a conflict between age data, which supports lower natural mortality values, and length data, which supports higher values. Similar to females, survey indices contain very little information to estimate male natural mortality.

### Comparison of base model to previous assessments

**Brian has updated this section** *Need to add comparison figure*

We plot summary biomass and recruits from eight past benchmark and update assessments conducted for canary rockfish (Figure \ref{fig:hist_compare})), starting in 1994, and compare to current estimates. Summary biomass is used because fecundity relationships have changed over time between biomass and egg production. Summary biomass has most often been modeled as biomass of age 5 and above `r spp`, with the exception of the 2001 assessment, which used age 3 and above. A metric of summary biomass was not readily obtainable for the 1999 assessment, so is excluded from the figure. The plot of summary biomass indicates that the equilibrium scale of the current base model is very similar to that of the last three assessment models, and is lower than other assessment models. Summary biomass around 1990 is similar for all models from 1999 onward. The current base model indicates a slower rate of increase than either the 2007 or 2015 assessment models, and faster rate of increase than the other assessment models since 1990. Age-0 recruits are estimated to be slightly higher for the current base model compared to the 2015 assessment model and similar to the2009/2011 update assessments. Recruitment in recent years for the current base model is similar in scale and general pattern to past assessments, although the individual trajectories are variable.

### Unresolved Problems and Major Uncertainties
