# Management

## Reference Points

Average unfished spawning output is estimated to be `r model$SBzero` million eggs (ARE THOSE UNITS RIGHT?) and unfished total summary biomass is estimated to be `r model$derived_quants['SmryBio_unfished','Value']` metric tons. A population at equilibrium at a target of $B_{40\%}$ is associated with a total dead catch of `r model$derived_quants['Dead_Catch_Btgt', 'Value']` metric tons and spawning output of `r model$derived_quants['SSB_Btgt', 'Value']` million eggs. A population at equilibrium at an SPR target of 50% is associated with a total dead catch of `r model$derived_quants['Dead_Catch_SPR', 'Value']` metric tons and spawning output of `r model$derived_quants['SSB_SPR', 'Value']` million eggs.  A population at equilibrium at model-estimated maximum sustainable yield is associated with a total dead catch of `r model$derived_quants['Dead_Catch_MSY', 'Value']` metric tons and spawning output of `r model$derived_quants['SSB_MSY', 'Value']` million eggs. The yield curve indicates current yield is below MSY estimated in the model, but above yield based on proxy targets (Figure \ref{fig:yield}). 

```{r}
# maybe use this table?
# labels <- expand.grid(c('SSB', 'SPR', 'annF', 'Dead_Catch'), 
#             c('Btgt', 'SPR', 'MSY')) |> 
#   dplyr::mutate(label = paste(Var1, Var2, sep = '_'))
# 
# ref.tab <- dplyr::filter(model$derived_quants, Label %in% labels$label) |>
#   dplyr::mutate(ref = sapply(stringr::str_split(Label, pattern = '_'), tail, 1),
#                 met = stringr::str_remove(Label, paste0('_', ref))) |>
#   dplyr::mutate(value.fmt = glue::glue('${x}\\pm {sd}$', 
#                                        x = sapply(Value, format, scientific = FALSE, 
#                                                   digits = 3), 
#                                        sd = sapply(StdDev, format, scientific = FALSE,
#                                                    digits = 2))) |>
#   dplyr::select(value.fmt, ref, met) |>
#   tidyr::pivot_wider(names_from = ref, values_from = value.fmt) |>
#   dplyr::mutate(met = c('Spawning output \\n ($10^6$ eggs)', 'SPR', 'F (1/yr)', 'Dead Catch (mt)'))
# 
# 
# names(ref.tab) <- c('', '$B_{40\\%}$', 'SPR$_{0.5}$', 'MSY')
# 
# knitr::kable(ref.tab)

```

## Unresolved Problems and Major Uncertainties

To be completed following the STAR panel.

## Harvest Projections and Decision Tables

To be completed following the STAR panel.

<!-- We have shown a decision table forecasting spawning biomass given two alternative harvest control rules (i.e., harvest at the annual catch limit, ACL, or the rebuilding target of 88.7 spawning potential ratio), using states-of-nature involving either alternative values for steepness or natural mortality rate (Tables h.1 and h.2). In each table, we set total catch in 2015/2016 equal to the previous estimates of annual biological catch (ABC). Projecting catches for 2017-2026 using the estimated ACL given the lower state-of-nature for either natural mortality (Table h.1) or steepness (Table h.2) results in declining spawning biomass over these 10 years (i.e., a 2026 spawning biomass relative to average unfished levels of 20.8% for the lower natural mortality rate, or 32.5% for the lower steepness level). By contrast, projecting catches using a target SPR of 88.7% given the lower natural mortality or steepness values results in a small increase in spawning output over time (i.e., a 2026 relative spawning biomass of 37.4% and 47.6% respectively). Projecting catches using the estimated ACL and either the base-model values or the upper states of nature for steepness and natural mortality rate results in a steady decline in spawning output towards the target level of 40%. Finally, projecting catches using a target SPR of 88.7%, given either the base values or upper state-of-nature for steepness or natural mortality, results in a gradual increase in spawning output over ten years. -->

<!--     Given that this assessment estimates the canary stock to have rebuilt, we do not envision providing forecasts using the rebuilder software for West Coast groundfishes.  We therefore envision that the decision tables presented here would be used as the basis for informing decisions regarding future, short-term harvest levels.  -->

## Regional management considerations

We have chosen to adopt a spatially stratified assessment model for the following reasons: • In cases where there are large differences in exploitation rate in different spatial areas, the proportion of the stock in different areas will change as a function of age. This will result in a highly irregular, and potentially time-varying form for selectivity for the fishery when analyzed using a nonspatial model (Sampson and Scott, 2012, 2011).\
• Given spatial variation in exploitation history, compositional data may exhibit systematic differences among spatial areas, e.g., by reflecting spatial differences in average age. A spatially stratified model may be able to explain these differences without otherwise attributing them to overdispersion (which would otherwise require extensive downweighting of available compositional data), and will generally provide information to diagnose model misspecification that is attributable to spatial variation in population dynamics, growth, or exploitation history (Punt et al., 2015).\
• One alternative approach to dealing with spatial variation in stock availability is to include spatial areas for a single fishery as separate fleets. However, previous research suggests that this "fleets as areas" in some cases will not properly account for spatial variation when it is caused by spatial differences in exploitation history (Cope and Punt, 2011).\
• We have also demonstrated that a nonspatial model generates similar estimates of stock-wide depletion, and that low rates of movement among spatial strata will not cause the estimated depletion to be below the management target (i.e., 40% of average unfished spawning output). We are therefore comfortable with plausible alternative treatments of spatial variation.

This spatial base model estimates substantial variation among spatial strata in spawning output relative to average unfished levels. However, determination of whether canary has completed its rebuilding is appropriately evaluated at a coast-wide level, and we interpret spatial variation as a tool to visualize and explore model residuals (Punt et al., 2015) and a method to identify time-varying selectivity at the stock-wide level (Sampson and Scott, 2011), rather than as a basis for spatially varying fisheries management.

## Evaluation of Scientific Uncertainty

Based upon the considerations, sensitivities, and retrospective analyses listed previously, we conclude that different treatments and assumptions regarding selectivity, spatial structure, ageing error estimates, and the inclusion of surface reads for otoliths have little impact on estimates of stock status for canary rockfish. However, we note that estimates of stock status are highly sensitive to assumptions regarding biological parameters that govern productivity and the yield curve, i.e., steepness, base natural mortality rate, and the assumption that female natural mortality is allowed to change for sexually mature individuals relative to immature females or males of any age. We therefore recommend that biological parameters form the basis for a decision table, and are prioritized as a subject for future research.

## Comparison among alternative states of nature

**Suggest deleting this section, it covered above under decision tables**

We chose to vary the strength of recruitment compensation to represent alternative plausible states of nature. We use steepness for the following three reasons: Recruitment compensation has been used to generate alternative states of nature in the 2007, 2009, and 2011 assessments, and represents a current topic of discussion in the Scientific and Statistical Committee of the PFMC. Values for alternative states of nature can be justified by previous meta-analytic research generating a prior distribution for steepness for Pacific rockfishes (Dorn, 2002; Punt and Dorn, 2013) The value of steepness has a large impact on the rate of stock rebuilding after the declaration of overfished status, and hence is highly influential in determining the degree to which the stock can be considered to be rebuilt (Figure 111). It also accounts for a large portion of the difference between the 2011 update and proposed base model (Figure 120).

To select values of steepness to use as the upper and lower states of nature, we use a normal approximation to the prior distribution for steepness with an identical mean and standard deviation to the predictive distribution from that analysis (mean=0.773, SD=0.147). We then identify the value of a normal distribution with that mean and standard deviation that is half as likely as the mode. This value is

h=0.773±0.147(1.18)=(0.600,0.946)

where 0.600 represents the lower and 0.946 the upper state of nature.

This comparison confirms that varying the values of steepness has relatively little impact on spawning output estimates prior to the 1990s, but has a substantial impact on the estimated rate of rebuilding after 1990 (Figure 121). The high-steepness state of nature (h=0.946) results in an estimate of relative spawning output of 67.1% in 2014, while the low-steepness alternative results in 39.4% in 2014. Consequently, the low-steepness alternative has a 95% confidence interval almost exactly centered on the management target, while the base and high-steepness alternative have 95% CIs that entirely exceed the management target. Contrasting the levels of recruitment from these three models (Figure 122), we see that the high-steepness model has elevated estimates of recruitment from the 1990s onward, which explains its faster rate of rebuilding. However, there is little difference in estimated recruitment deviations otherwise, such that all three models identify a similar set of strong and poor-recruitment years.

We also represent the uncertainty in our assessment results using two alternative values for the natural mortality rate of juvenile female and adult individuals. In each state of nature, we freely estimate the natural mortality rate for adult females. To generate values for upper and lower states of nature for natural mortality rate, we first note that the upper bound generated using the probabilistic method outlined above for steepness results in an estimated population trajectory that is entirely implausible (i.e., ln_R0 goes to \>11, and the fisheries is estimated to have never substantially impacted the canary population). Therefore, we instead generate upper and lower values by identifying values for natural mortality that match the final spawning output relative to average unfished levels for the states of nature identified for steepness. This results in lower and upper natural mortality rates of M=0.025, and M=0.06.

Using these values, we find that changes in natural mortality rate have a substantial impact on both the rate of population rebuilding after decreases in fishing intensity in the 1990s, and also upon the absolute scale of the population during the entire time series. In particular, an elevated rate of natural mortality increases the total spawning output nearly 10% relative to the base model. These scenarios in particular have a large impact on the scale of recruitment. This is expected, given that changes in natural mortality rate have a large impact on yield per recruit, and we conclude that the model is compensating for decreased yield per recruit in the high-M state of nature by increasing recruitment overall (where this impact is inverted for the low-M state of nature).

## Research and Data Needs

### Responses to previous assessment research and data needs

Recommendations are summarized for brevity:

1.  A historical catch reconstruction be initiated with the intent of estimating spatial location of catches. Such a process has been initiated in other regions (e.g., the Northwest Atlantic, M. Pinsky, pers. comm.), and will be important to validate the assumptions that are necessary when developing spatial models.

**Response**: This assessment includes a new reconstruction of `r spp` landings in Oregon within unspecified PacFIN categories from 1987-1999. A formal Washington reconstruction is nearing completion, but was not yet ready for use in this assessment. Some work was begun on separating canary rockfish landings in Oregon into those caught in Oregon and Washington waters while compiling data for this assessment. While logbook information may be sufficient to eventually approximate state of catch, the composition data is much more challenging to separate and could not be done within the time available. A comprehensive approach to account for trawl-caught fish across state boundaries is underway as a result of this analysis. Because this assessment model returned to a coast-wide configuration, this recommendation was given lower priority.

2.  We endorse a systematic (rather than ad hoc and species-specific) exploration and analysis of Canadian data sources (length and age-composition, indices of abundance, landings, and discards) for several rockfishes.

**Response:** Progress remains species-specific. However, progress for some groundfish species (sablefish, petrale sole) is occurring outside of regular stock assessment cycles so that it can be completed in a more intentional and less ad hoc fashion. Canary rockfish has not been prioritized for these activities by NMFS or DFO. We explored Canadian `r spp` landings and estimates of recruitment deviations from an assessment conducted one year prior to this one.

3.  We therefore recommend that future research explore methods to stitch these time series back together (i.e., using covariates and a meta-analytic information regarding the ratio of catchability in the two periods).

**Response:** Changes in the spatial (latitudinal and depth) extent of the triennial survey should not impact `r spp`, which are generally not found in the areas the survey expanded into. Canary rockfish are also not known to undertake seasonal migrations, so the change in timing should similarly not be influential. Therefore, this assessment estimates the triennial index using a single spatial GLMM. Both composition data and catch data are truncated so as not to include areas of survey expansion. The index is entered into the assessment model as two different fleets to maintain the ability to test for sensitivity to combining the periods, but catchability and selectivity are mirrored between these two fleets. Thus, they are treated as a single time series with different age and length composition data weights. 

4.  We suggest that basic life history research be highly prioritized for future research.

**Response:** This assessment includes updated data and relationships on growth, condition (weight-length), fecundity, and maturity. A number of studies on canary rockfish life history and population structure have been published since the previous assessment [@budrick2016evolutionary; @keller2018canary; @Brooks_thesis_2021]. Unfortunately, these have not resulted in a better understanding of natural mortality and the apparent loss of older females. This remains a research priority. In absence of better understanding of canary rockfish natural mortality, we use natural mortality rates from a recently updated prior [@hamel2022development].

### Response to STAR panel research recommendations {#star-recs}

Recommendation: Catch and discard history for this stock in US waters is highly uncertain. While the STAT was able to construct alternative upper and lower bounds for catch using simple multipliers on certain years of historical catch, this is arbitrary. Work to assess the uncertainty related to each individual data source would allow a better investigation of the overall combined uncertainty and its effect on 10 stock assessments.

Response: This assessment includes a new reconstruction of `r spp` landings in Oregon within unspecified PacFIN categories from 1987-1999. A formal Washington reconstruction is nearing completion, but was not yet ready for use in this assessment. 

Recommendation: Improved documentation is required to clearly outline the process used to construct the historical catch and discard time series from the various data sources. Such documentation should also include the process for construction of alternative catch histories that are used to propagate such uncertainty into the stock assessment.

Response: This assessment report has attempted to more clearly document the process used to construct the historical catch and discard time series. In addition, the use of github for this assessment (https://github.com/pfmc-assessments/canary_2023) means that the code used to construct the time series, and many of the decisions involved, is publicly available and the process is reproducible. Finally, the STAT has communicated repeatedly with state partners and the GMT to ensure that catch time series are appropriate, per the TOR. This communication did result in changes to the catch history during model development.

Recommendation: Additional work on the geospatial index is required to better resolve differences in abundance trends among areas.

Response: This assessment did not use a spatially stratified abundance index.

Recommendation: Work towards a combined US/Canadian stock assessment would greatly aid our overall understanding of stock status.

Response: Little progress has been made on a combined US/Canadian stock assessment. The STAT did obtain catches and estimated recruitment and recruitment deviations from a recent British Columbia assessment. We have conducted a sensitivity with these catches added to Washington fleets, and compared the recruitment deviations estimated within our base model and the Canadian model to look for synchrony.

Recommendation: If data permit, the trawl fleet should be divided into separate components so that bycatches in the shrimp and pelagic trawls are separated from catches in the main bottom trawl fleet. In the current assessment, composition data for the trawl fleet have a major influence on the estimated stock trends, so it would be desirable to use data that are more representative of the main fleet in order to improve estimated selectivity of the fleet.

Response: Due to the already extremely complex fleet structure in this model, the shrimp and pelagic trawls were maintained with the main trawl fleet. Analysis indicated **Brian I remember a ? from John F. during the pre-assessment workshop about the appropriateness of including shrimp trawls with the main trawl, and you had a great answer from him, feel free to fill in here.**

Recommendation: Basic life history research may help to resolve assessment uncertainties regarding appropriate values for natural mortality and steepness, and how to best account for the apparent loss of older females in the population.

Response: This assessment includes fecundity and maturity curves based on new data made available since the last benchmark assessment. While efforts have been undertaken to understand the apparent loss of older females, this has not resulted in any clear resolution. A research study sampling in non-trawlable habitat along the U.S. West Coast found a similar lack of old females in the data [@Brooks_thesis_2021]. Examination of data from the Oregon trawl fleet indicates that sex ratios have been more constant across ages in the last decade than they had been previously (L. Rasmuson, pers. comm.).

### Current research and data neds

1.  The \gls{s-wcgbt} has low encounter rates with `r spp` in part because it has limited access to rocky habitat. We recommend exploration of non-trawl coast-wide fishery-independent indices. This could mean an expansion of the \gls{s-hl} into more northern waters, or taking advantage of developments in model-based index standardization to stitch together multiple similar overlapping fishery-independent non-trawl sampling programs that have occurred over smaller spatial and temporal scales than the \gls{s-wcgbt}.