# Acknowledgments

Many people were instrumental in the successful completion of this assessment and their contribution is greatly appreciated. We gratefully acknowledge substantial input and helpful review from the STAR panel reviewers: **LIST REVIEWERS HERE**. We are very grateful to all the agers at \gls{wdfw}, \gls{odfw}, and to Patrick McDonald, Betty Kamikawa, and others at the CAP lab for their hard work reading numerous otoliths and availability to answer questions when needed. Kayleigh Sommers assisted with data from the WCGOP. We thank Tanya Rogers and John Field for processing data and developing the index for the pre-recruit survey, Kelli Johson for provided extensive analysis and development of the indices of abundance for all assessments this cycle, John Wallace for pre-processing data from the Pikitch historical discard study and answering questions about it, Vanessa Tuttle for assistance in providing and understanding data from the at-sea-hake fishery, and Kayleigh Somers for providing data from \gls{wcgop} and answering qeustions about its use. We would like to acknowledge Brenda Erwin and Jason Edwards so helping understand the available data from \gls{pacfin} and \gls{recfin} and resolving questions and issues about its interpretation and use. Members of the \gls{nwfsc} stock assessment program and assessors at \gls{swfsc}, and in particular, Owen Hamel, Ian Taylor, Jason Cope, E.J. Dick were instrumental in helping to identify and navigate important issues during model design and interpretation. We also thank Chantel Wetzel, Kelli Johnson, and Ian Taylor for providing extensive help in understanding the various data software packages available for data processing, model interpretation, and report writing. Lastly, we appreciate the contributions of the numerous individuals who took the time to participate in the pre-assessment data webinar.