\clearpage
\floatplacement{table}{H}

# Tables

<!-- ======================================================= -->
<!-- ********  Catch tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/canary_total_removals.csv')) |> 
  dplyr::select(Year,
                 TWL.C, TWL.O, TWL.W,
                 NTWL.C, NTWL.O, NTWL.W,
                 rec.C, rec.O, rec.W.mt.2) |>
  knitr::kable(caption = 'Total removals (mt) of canary rockfish for the trawl (TWL), non-trawl (NTWL), and the recreational (Rec) fleets used in the assessment model. See text for description of sources',
               label = 'catches1', 
               format = 'latex',
               col.names = c("Year", 
                             "TWL CA", "TWL OR", "TWL WA",
                             "NTWL CA", "NTWL OR", "NTWL WA",
                             "Rec CA", "Rec OR", "Rec WA"),
               booktabs = TRUE,
               longtable = TRUE,
               linesep = "",
               digits = 1) |>
  kableExtra::kable_styling(
      latex_options = c("repeat_header"),
      font_size = 8)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/canary_total_removals.csv')) |> 
  dplyr::select(Year,
                 FOR.C, FOR.O, FOR.W,
                 ASHOP.C, ASHOP.O, ASHOP.W) |>
  dplyr::filter(Year > 1965) |>
  knitr::kable(caption = 'Total removals (mt) of canary rockfish for the foreign (FOR) and at-sea-hake (ASH) fleets used in the assessment model. Removals before 1966 are zero. See text for description of sources',
               label = 'catches2', 
               format = 'latex',
               col.names = c("Year",
                             "FOR CA", "FOR OR", "FOR WA",
                             "ASH CA", "ASH OR", "ASH WA"),
               booktabs = TRUE,
               longtable = TRUE,
               digits = 1)
```

\newpage

<!-- ======================================================= -->
<!-- ********  ACL tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/ACL_history.csv')) |>
  knitr::kable(caption = 'The OFL, ABC, ACL, and total mortality (landings + dead discards) in metric tons',
               label = 'acls', 
               format = 'latex',
               booktabs = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Commercial sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results = 'asis', message=FALSE}
readr::read_csv(here('documents/tables/pacfin_lengths.csv')) |>
  dplyr::select(Year, 
         Trips_TWL.C, Lengths_TWL.C, Trips_NTWL.C, Lengths_NTWL.C,
         Trips_TWL.O, Lengths_TWL.O, Trips_NTWL.O, Lengths_NTWL.O,
         Trips_TWL.W, Lengths_TWL.W, Trips_NTWL.W, Lengths_NTWL.W) |>
  as.data.frame() |>
  sa4ss::table_format(caption = "Summary of the number of trips and length samples for commercial trawl (TWL) and non-trawl (NTWL) fleets",
                      label = "comm-sample-lengths",
                      align = 'l',
                      col.names = c("Year",
                            "Trips CA TWL", "Lengths CA TWL", "Trips CA NTWL", "Lengths CA NTWL", 
                            "Trips OR TWL", "Lengths OR TWL", "Trips OR NTWL", "Lengths OR TWL", 
                            "Trips WA TWL", "Lengths WA TWL", "Trips WA NTWL", "Lengths WA TWL"),
                      longtable = TRUE,
                      landscape = TRUE)
```

\newpage

```{r, results = 'asis', message=FALSE}
readr::read_csv(here('documents/tables/pacfin_ages.csv')) |>
  dplyr::select(Year, 
         Trips_TWL.C, Ages_TWL.C, Trips_NTWL.C, Ages_NTWL.C,
         Trips_TWL.O, Ages_TWL.O, Trips_NTWL.O, Ages_NTWL.O,
         Trips_TWL.W, Ages_TWL.W, Trips_NTWL.W, Ages_NTWL.W) |>
  as.data.frame() |>
  sa4ss::table_format(caption = "Summary of the number of trips and aged samples for commercial trawl (TWL) and non-trawl (NTWL) fleets",
                      label = "comm-sample-age",
                      align = 'l',
                      col.names = c("Year",
                            "Trips CA TWL", "Ages CA TWL", "Trips CA NTWL", "Ages CA NTWL", 
                            "Trips OR TWL", "Ages OR TWL", "Trips OR NTWL", "Ages OR TWL", 
                            "Trips WA TWL", "Ages WA TWL", "Trips WA NTWL", "Ages WA TWL"),
                      longtable = TRUE,
                      landscape = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  ASHOP sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/Canary_ashop_LengthComps_hauls_and_samples.csv')) |> 
  dplyr::select(Year, OR_nhaul, OR_N, WA_nhaul, WA_N) |>
  knitr::kable(caption = 'Summary of the number of hauls and length samples for the at-sea-hake fleets. No samples were collected in California',
               label = 'ashop-sample-lengths', 
               format = 'latex',
               col.names = c("Year", "Hauls OR", "Lengths OR", "Hauls WA", "Lengths WA"),
               booktabs = TRUE)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/Canary_ashop_AgeComps_hauls_and_samples.csv')) |>
  dplyr::select(Year, OR_nhaul, OR_N, WA_nhaul, WA_N) |>
  knitr::kable(caption = 'Summary of the number of trips and aged samples for the at-sea-hake fleets. No samples were collected in California',
               label = 'ashop-sample-age', 
               format = 'latex',
               col.names = c("Year", "Hauls OR", "Ages OR", "Hauls WA", "Ages WA"),
               booktabs = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Recreational sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/rec_lengths.csv')) |>
  dplyr::select(year, N_CA, ntrip_CA, N_OR, ntrip_OR, N_WA, ntrip_WA) |>
  knitr::kable(caption = 'Summary of the number of trips and length samples for recreational fleets',
               label = 'rec-sample-lengths', 
               format = 'latex',
               col.names = c("Year", "Lengths CA", "Trips CA", "Lengths OR", "Trips OR", "Lengths WA", "Trips WA"),
               booktabs = TRUE,
               longtable = TRUE,
               escape = TRUE) #%>%
  #kable_styling(font_size = 7) Need to install this package though to have this work
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/rec_ages.csv')) |>
  dplyr::select(year, O_or_ora_N, O_or_ora_ntrip, W_wa_sport_N, W_wa_sport_ntrip) |>
  knitr::kable(caption = 'Summary of the number of trips and aged samples for recreational fleets. No aged samples are available for the California recreational fleet',
               label = 'rec-sample-age', 
               format = 'latex',
               col.names = c("Year", "Ages OR", "Trips OR", "Ages WA", "Trips WA"),
               booktabs = TRUE,
               longtable = TRUE)  #%>%
  #kable_styling(font_size = 7) Need to install this package though to have this work
```

\newpage

<!-- ======================================================= -->
<!-- ********  Survey sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/wcgbts_summary.csv')) |>
  knitr::kable(caption = 'Summary of canary rockfish samples in the West Coast Groundfish Bottomtrawl Survey (WCGBTS)',
               label = 'wcgbts', 
               format = 'latex',
               booktabs = TRUE)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/triennial_summary.csv')) |>
  knitr::kable(caption = 'Summary of canary rockfish samples in the AFSC/NWFSC West Coast Triennial Shelf Survey (Triennial)',
               label = 'triennial', 
               format = 'latex',
               booktabs = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Model results *************** --> 
<!-- ======================================================= -->


```{r, results = 'asis', message=FALSE}
readr::read_csv(here('documents/tables/parameters.csv')) |>
  as.data.frame() |>
  sa4ss::table_format(caption = "List of parameters used in the base model, including estimated values and standard deviations (SD), bounds (minimum and maximum), estimation phase (negative values not estimated), status (indicates if parameters are near bounds), and prior type information (mean and SD).",
                      label = "params",
                      align = 'l',
                      # col_names = col_names,
                      longtable = TRUE,
                      font_size = 9,
                      digits = 3,
                      landscape = TRUE,
                      custom_width = TRUE,
                      col_to_adjust = c(1,7),
                      width = c("7.5cm", "3.5cm")
                      )
```


\newpage

```{r like, results='asis', message=FALSE}
readr::read_csv(file.path(model_dir, "tables", "likelihoods.csv")) |>
  knitr::kable(caption = 'Likelihood components by source',
               label = 'like',
               format = 'latex',
               col.names = c("Data type", "Total"),
               booktabs = TRUE,
               escape = TRUE,
               digits = 2) #%>%
  #kable_styling(font_size = 7) Need to install this package though to have this work
```

\newpage

```{r tables-weights, results = "asis"}
source(here('code/table_compweight.R'))
table_compweight(model,
  caption_extra = paste("The WCGBTS age comps are conditioned on length,",
   "so there are more observations with fewer samples per observation."),
   label = "data-weights") %>%
  kableExtra::kable_styling(font_size = 10)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Timeseries *************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
timeseries = read.csv(file.path(dir, "models", paste0(model_name), "tables", "TimeSeries.csv"))
col_names = c("Year", "Total Biomass (mt)", "Spawning Output", "Total Biomass 5+ (mt)", "Fraction Unfished", "Age-0 Recruits", "Total Mortality (mt)", "1-SPR", "Exploitation Rate")

table_format(x = round(timeseries,2),
                 caption = "Time series of population estimates from the base model. Spawning output is in millions of eggs and age-0 recruits is in numbers of 1000s.",
                 label = "timeseries",
                 longtable = TRUE,
                 col_names = col_names,
                 row.names = FALSE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Sensitivities *************** --> 
<!-- ======================================================= -->
```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/data_table.csv')) |>
  knitr::kable(caption = 'Estimates of likelihood components and major model parameters for data sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, not all likelihoods are comparable.',
               label = 'data-sens',
               format = 'latex',
               booktabs = TRUE)
```

```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/weighting_table.csv')) |>
  knitr::kable(caption = 'Estimates of likelihood components and major model parameters for data weighting sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, not all likelihoods are comparable.',
               label = 'weight-sens',
               format = 'latex',
               booktabs = TRUE)
```

```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/selectivity_table.csv')) |>
  knitr::kable(caption = 'Estimates of likelihood components and major model parameters for selectivity sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, not all likelihoods are comparable.',
               label = 'selec-sens',
               format = 'latex',
               booktabs = TRUE)
```

```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/productivity_table.csv')) |>
  knitr::kable(caption = 'Estimates of likelihood components and major model parameters for productivity sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, not all likelihoods are comparable.',
               label = 'prod-sens',
               format = 'latex',
               booktabs = TRUE)
```

<!-- ======================================================= -->
<!-- ********  Reference points *************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
readr::read_csv(here('documents/tables/ref_points.csv')) |>
  knitr::kable(caption = 'Various reference points for three different management targets', 
               label = 'ref-pts', 
               format = 'latex', 
               booktabs = TRUE)
```

\newpage
