## Fishery-Dedependent Data

### Total Removals {#removals}

Removals (1892-2022) for canary rockfish were compiled from multiple data sources. This assessment includes total removals (landings plus dead discards) by state for the following fleets: trawl, non-trawl, recreational, foreign trawl, and at-sea hake. A summary of total removals are provided in Table \ref{tab:catches1} and Table \ref{tab:catches2}, and Figure \ref{fig:catches}.

#### Commercial Landings by State

##### Washington

Commercial landings data in Washington were available from 1935--2022. Historical landings (1935--1980) were retained from the last full assessment where they were assumed to be for trawl gears [@stewart2007canary; @thorson_status_2016]. Recent landings (1981--2022) for the trawl and non-trawl (mainly hook and line) gears were obtained from \gls{pacfin}, the central repository for West coast commercial landings (extracted on 03/23/2023, \gls{psmfc}, Portland, Oregon). A small update to 2022 landings from \gls{pacfin} values was provided by \gls{wdfw} on 06/18/2023.

##### Oregon

Commercial landings data in Oregon were available from 1892--2022. Historical landings from 1892 to 1986 were provided by \gls{odfw} [@karnowski_historical_2014]. Landings in 1987--1999 were compiled from a combination of \gls{pacfin}, (extracted on 03/23/2023), and a separate \gls{odfw} reconstruction that delineated canary rockfish-specific landings among unspecified species categories within \gls{pacfin} [e.g. URCK and POP1, @odfw2017informational]. Canary rockfish landings from this reconstruction were substituted for the URCK and POP1 landings available from \gls{pacfin} and added to \gls{pacfin} landings from other categories for a complete time series of canary rockfish during this time period. Commercial landings in 2000--2022 were available on \gls{pacfin} (extracted on 03/23/2023).

##### California

Commercial landings data in California were available from 1916--2022. Historical landings from 1916 to 1980 were obtained following the process described in the southern California vermilion rockfish (*Sebastes miniatus*) assessment [see @dick2021vermillion for complete details]. Briefly, landings 1916--1968 came from a state reconstruction [@ralston_documentation_2010]. Landings from unknown gears in known regions were allocated proportional to landings from known gears within the same region for each year. Landings from unknown locations (Region 0) and unknown gears were allocated proportional to the landings from known gears across all known locations for each year. Landings from 1969--1980 came from \gls{calcom}, which for 1969--1977 incorporates fish ticket data including mixed species categories for rockfish that were assigned to individual species using the earliest species composition samples (from the late 1970s and ealy 1980s). Recent (1981--2022) landings by trawl and non-trawl gears were obtained from \gls{pacfin} (extracted on 03/23/2023).

Additional catches caught off the coast of Oregon or Washington but landed in California from 1948-1968 were included, as these were not incorporated within the Ralston et al. [-@ralston_documentation_2010] reconstruction (E. Dick, \gls{swfsc}, personal communication, 3/16/23). These final landings are in the California landings history for consistency with treatment for other states, because historical catches landed in Oregon or Washington but caught in the other state's waters are similarly attributed to the state where they were landed.

#### Commercial Discards

Discarding was not estimated in the model. Estimates of dead discards were combined with landed catch to provide estimates of total removals that were used as input within the assessment model. In recent years (2000--2022), estimates of dead discards were calculated from discard data, but in earlier years (before 2000), estimates of dead discards were calculated based on assumed discard ratios.

The ratio of discarded weight to landed weight (hereafter termed the "discard ratio") for the domestic trawl and non-trawl fisheries was assumed at the following values: 1% discard ratio for 1892--1980, based on the assumption that discard rates were low prior to management actions due to the high-value nature of the fishery [and consistent with the previous assessment, @thorson_status_2016]; 5% discard ratio for 1981--1994 which is approximately the value calculated by J. Wallace, NMFS using data from @pikitch_evaluation_1988; 20% discard ratio for 1995--1999, based on the assumption that discard ratios would be higher than previous years but less than years when discard data was present due to the period of non-retention [and consistent with the previous assessment, @thorson_status_2016].

Onboard observers were deployed on fishing vessels starting in 2002 to collect data on discarding practices. Discard amounts for the domestic trawl and non-trawl fleets from 2002--2021 were determined based on \gls{wcgop} data provided in the \gls{gemm} product, [available publicly](https://www.pcouncil.org/documents/2022/08/g-1-b-nwfsc-report-1-estimated-discard-and-catch-of-groundfish-species-in-the-2021-west-coast-fisheries.pdf). The \gls{gemm} provides estimates of dead discards coastwide. Therefore, the total coastwide estimates of dead discards in trawl and fixed gears as provided in the \gls{gemm} were allocated by state based on the total observed landings and discards for each state as observed by \gls{wcgop}. Dead discards were added to landings to obtain total removals for 2002--2021. Total removals in 2000, 2001, and 2022 where no \gls{wcgop} data were available were calculated by applying the average discard ratios from 2002--2004 (for estimates in 2000 and 2001) and 2019--2021 (for estimates in 2022) for each gear to landings for that gear.

#### Recreational Landings and Discards by state

##### Washington

Washington recreational landings, in number of fish retained, were provided by \gls{wdfw} for 1967 and 1975--2022. Landings estimates starting in 1990 were reworked by the \gls{wdfw} sport sampling unit since the previous assessment. For 1968--1974, a linear ramp between the values in 1967 and 1975 was used to approximate landings. Recreational landings were assumed to be zero prior to 1967. Documentation for landing estimates compiled for 1987--1989 could not be located by \gls{wdfw}, but were used in lieu of linear interpolation between estimates in 1986 and 1990.

Discard estimates for 2002--2022, in number of fish released, were also provided by \gls{wdfw}. Numbers released in specific depth categories were available from 2005--2022, and estimates of the proportion of releases that occurred using descender devices were available from 2016--2022. Released fish at unknown depths were allocated proportional to released fish at known depths in years with depth-specific values. For 2002--2004, which had no depth-specific information, the average total release mortality rate in 2005--2007 was used to calculate the number of dead discards. Depth-specific release-mortality rates were based on agreed upon values for canary rockfish for surface releases [Table 1-10, @pfmc2014status] and releases with descender devices [Table 1-13, @pfmc2014status]. The release mortality rates using descender devices in deep waters (30+ fathoms) in Pacific Fishery Management Council @pfmc2014status were binned at a finer scale than in the provided data on descender device usage. Number of releases decreased with water depth, so the release morality in 30+ fathoms when using descender devices was assumed as the average of release mortality rates for 30--50 fathoms and 50-100 fathoms from @pfmc2014status.

The total discard mortality rate (release rate multiplied by release mortality rate) for 2002 was also applied to 2000--2001 landings. All three years shared a two canary daily bag limit, and were assumed to have similar discarding practices. We assumed zero recreational releases prior to 2000 when canary rockfish was included as part of a ten rockfish daily limit, and release rates were generally low (P. Anderson, personal communication, 03/20/23).

Total removals in the Washington recreational fleet were converted from numbers to weight to maintain consistency with units from other fleets. Length data for sport catches were provided by \gls{wdfw} for 1979--2022. The average length of canary rockfish by year was calculated and converted to average weight based on parameters of the length-weight relationship ($\alpha$ = 1.040E-05 and $\beta$ = 3.084 for length in cm and weight in kg) as used in \gls{recfin}. In years where the number of length samples was fewer than 25, lengths were borrowed from the nearest neighboring years to calculate a three year weighted-average. A value of 25 was used because it was the 'small sample size' threshold used by @dick_lengthborrow_2021 and had increased percent standard error compared to other sample sizes. Borrowing lengths from neighboring years was only applied from years with roughly similar fishing regulations. Thus, lengths were only calculated from neighboring years in the periods \<1999 (canary rockfish part of group daily bag limits), 2000--2003 (canary rockfish with individual daily bag limits), 2004--2016 (period of no retention), and 2017--2022 (post non-retention). Any years without lengths were assigned the non-weighted-average length across years within a period. A non-weighted length was applied to give each year equal weight in calculating an overall average for each period.

##### Oregon

###### Historic Ocean Boat Landings and Discards (1979--2000)

Recently, \gls{odfw} undertook an effort to comprehensively reconstruct all marine fish recreational ocean boat landings prior to 2001 [@whitman2023, in review]. Reconstructed catch estimates from the \gls{orbs} improve upon estimates from the federal \gls{mrfss}, which have known biases related to effort estimation and sampling [@vanvoorhees2000] that resulted in catch estimates considered implausible by \gls{odfw}. However, the \gls{orbs} sample estimates are known to lack the comprehensive spatial and temporal coverage of \gls{mrfss}. Addressing this coverage issue is a major part of this reconstruction. In general, the base data and methodology for these reconstructed estimates are consistent with recent assessments for other nearshore species [@cope2021vermillion_or; @langseth2021quillback_or; @taylor2021lingcod_n; @wetzel2021copper_or].

Prior to 2001, \gls{orbs} monitored marine species in both multi-species categories, such as rockfish, flatfish, and other miscellaneous fishes, and individual species, such as lingcod or halibut. For this comprehensive reconstruction, four species categories were selected to reconstruct, including rockfish, lingcod, flatfish and miscellaneous, which constitute the bulk of the managed marine fish species. Canary rockfish are a component of the rockfish species category.

Category-level estimates were expanded to account for gaps in sampling coverage in two separate pathways. First, estimates from five major ports were expanded to include unsampled winter months in years lacking complete coverage. Expansions were based on available year-round sampling data and excluded years where regulations may have impacted the temporal distribution of catch. Second, all other minor port estimates were expanded to include seasonal estimates in years lacking any sampling based on the amount of minor port catch as compared to all major port estimates. A subset of landings were sampled by ORBS for species compositions within these categories. Once category-level landings were comprehensive in space and time, species compositions were applied for the three multi-species categories, including rockfish, flatfish and miscellaneous fish. Borrowing rules for species compositions were specific to the category and determined based on a series of regression tree analyses that detailed the importance of each domain (year, month, port and fishing mode) to variability in compositions.

Ocean boat estimates 1979--2000 in numbers of fish of canary rockfish from the above described methods were converted to biomass using biological samples from MRFSS (A. Whitman, ODFW, personal communication, 2023). \Gls{mrfss} biological data are available 1980--1989 and 1993--2000. An annual average weight was applied to the total annual number of fish to obtain an annual biomass estimate of the landings. Several years of missing biological data (1979, 1990--1992) were filled in using neighboring years or interpolation. Landings from 1979 to 2000 averaged 29.9 mt and are of similar magnitude to the previous assessment, though landings appear to have less interannual variability than the previous assessment [@thorson_status_2016]. Landings were relatively high in the first year of available data (1979) and so landings from 1972 to 1978 were initiated at zero in 1972 and linearly ramped up to the value in 1979. The provided landings do not include an estimate of discarded fish, and thus are assumed as total removals. Bag limits in the recreational fishery during this time period (prior to 2001) were generally liberal and \gls{odfw} staff recommended that no additional mortality of discarded fish be included prior to 2001.

###### Modern Ocean Boat Landings and Discards (2001 -- 2022)

Recreational landings for ocean boat modes from 2001--2022 are available from \gls{recfin}. Both retained and released estimates of mortality are included, though retained mortality contributes the vast majority to total mortality in years outside the overfished designation for canary rockfish. Release mortality is estimated from angler-reported release rates and the application of discard mortality rates from the PFMC [@pfmc2014status]. The average proportion of canary rockfish discarded averaged 4.5% in 2001--2003 and 2017--2022. During years where canary rockfish retention was prohibited, discard rates increased to 96.1% on average (2004--2016). From 2001 to 2022, total landings averaged 16.0 mt, ranging from 1.7 to 60.6 mt. In 2022, estimated ocean boat landings were 55.7 mt.

##### California

Recreational landings in California were available from 1928--2022. Historical estimates of recreational landings 1928--1979 were obtained from the previous assessment [@thorson_status_2016], which were in turn were obtained from \gls{calcom}. For years since 1979, recreational landings along with estimates of dead discards came from \gls{recfin} via the \gls{mrfss} (1980--2003) and \gls{crfs} (2005--2022) sampling programs. Landings and dead discards were added together to obtain estimates of total removals. Discards prior to 1980 were assumed to be zero.

A number of years with missing or incomplete estimates for recreational removals were filled in. The removals in 1980 from \gls{mrfss} were not used due to survey quality problems related to 1980 being the first year of \gls{mrfss} [@Karpov1995; @cope_status_2009]. Removals for this year were averaged across removals in 1979 and 1981. No or minimal party/charter (PC) estimates were available from 1993--1995, so PC mode removals for these years were calculated assuming an average ratio of private/rental (PR) to PC modes across all years with data within \gls{mrfss} and added to PR values to obtain total recreational estimates. The \gls{mrfss} sampling program did not sample from 1990--1992, and so estimates during these three years were obtained as averages from neighboring years. Estimates in 1990 were the average from 1987--1989, estimates in 1991 were the average from 1987--1989 and 1993--1995, and estimates in 1992 were the average from 1993-1995. Because of the transition from \gls{mrfss} to \gls{crfs}, no estimate was available in either database in 2004 for this assessment cycle. \Gls{cdfw} provided a value of 10.59 mt for 2004 (J. Budrick, CDFW, personal communication, 3/20/23), based on an available previous pull of \gls{mrfss} data for the gopher rockfish (*Sebastes carnatus*) assessment. Estimates for California recreational removals from the previous canary rockfish assessment were not used because these appeared to only reflect estimates of landings, and not total removals.

###### CA Recreational Data Impacted by COVID-19 Pandemic

The COVID-19 pandemic impacted recreational port sampling in 2020 and 2021. No sampling occurred at all in April-June, 2020. \Gls{cdfw} provided proxy values for these months (M. Parker, CDFW, personal communication, 2/22/23). Total proxy values for canary rockfish weight were summed across district and added to the existing estimate for 2020 from \gls{recfin}. In addition, California recreational total mortality estimates in the "rockfish genus" were inflated due to \gls{crfs} samplers being unable to closely examine catch and identify catch to species. This was a problem for both PR and PC modes in 2020 and primarily for the PC mode in 2021. An effort was made to allocate some of the rockfish genus mortality to other rockfish species for these modes and years (J. Coates, CDFW, personal communication, 2/10/23). An expected value of rockfish genus mortality in 2020 and 2021 was generated by mode and year according to the average proportion to the total rockfish mortality that this category represented in 2018 and 2019, when regulations were consistent with 2020 and 2021. Mortality above this expected value was attributed to the other species also based on proportions each species represented to the total from 2018 and 2019. Calculations were made by year, mode, and district. The shore-based modes were grouped in with the PR mode. Calculations were initially made in numbers of fish because rockfish genus mortality is only recorded this way. Numbers of fish by species were then converted to weight in kilograms based on average weights of fish recorded by the \gls{crfs} program by district in 2019. Total reallocated values for canary rockfish weight were summed across modes and districts and added to existing estimates for 2020 from the sum of the proxy value and \gls{recfin} and for 2021 from \gls{recfin}.

#### At Sea Hake Fishery

Catches of canary rockfish are monitored aboard the vessel by observers in the \gls{ashop} and were provided for the years 1975--2022 (V. Tuttle, NOAA, personal communication, 4/3/23). Observers use a spatial sample design, based on weight, to randomly choose a portion of the haul to sample for species composition. For the last decade, this is typically 30-50% of the total weight. The total weight of the sample is determined by all catch passing over a flow scale. All species other than hake are removed and weighed, by species, on a motion compensated flatbed scale. Observers record the weights of all non-hake species. Non-hake species total weights are expanded in the database by using the proportion of the haul sampled to the total weight of the haul. The catches of non-hake species in unsampled hauls is determined using bycatch rates determined from sampled hauls. Since 2001, more than 97% of the hauls have been observed and sampled.

Values for percentages of the catch that was retained were available in the data starting in 1997. When not provided, we assumed percent retained was 100 percent. We also assumed that any canary rockfish not retained were dead. We therefore added the retained landings to the amount of landings not retained to obtained total removals.

Total removals were partitioned to state based on latitude, with retrieved hauls from 46.25$^{\circ}$N to 49$^{\circ}$N assigned to Washington, 42$^{\circ}$N to 46.25$^{\circ}$N assigned to Oregon, and \< 42$^{\circ}$N assigned to California. Starting in 1992, processing of at-sea hake was restricted to north of 42$^{\circ}$N [@fed_registry_1992]. Very small catches from south of 42$^{\circ}$N during this time were assigned to Oregon. Due to confidentiality, catches in 1975 were not reported or used within the model, and catches in 1976 were combined and assigned to Oregon.

#### Foreign Catches

From the 1960s through the early 1970s, foreign trawling enterprises harvested considerable amounts of rockfish off Washington and Oregon, including large quantities of canary rockfish. Foreign catches of individual species were estimated by @rogers_species_2003 and attributed to \gls{inpfc} areas from 1966-1976 for canary rockfish. \Gls{inpfc} areas do not coincide with the fleet areas defined in this assessment. Therefore, INPFC catches were translated to states in the following manner: catches from the US Vancouver INPFC area were designated to Washington, catches in the Columbia INPFC area were allocated to Oregon, and catches from the Eureka and Monterey INPFC areas were assigned to California. These definitions match where the majority of commercial trawl landings occur by state for each INPFC area within \gls{pacfin}.
