# Introduction

## Basic Information

Canary rockfish (*Sebastes pinniger*) are distributed in the northeastern Pacific Ocean from the western Gulf of Alaska to northern Baja California; however, the species is most abundant from British Columbia to central California [@miller1972guide; @hart1973pacific; @love2002rockfishes]. Adults are primarily found along the continental shelf shallower than 300 m, although they are occasionally observed in deeper waters. Juvenile canary rockfish are found in shallow and intertidal areas [@love2002rockfishes].

From 2001 to 2011, the canary rockfish stock assessment models structured the population as a single coastwide stock, but used an areas-as-fleets approach to varying degrees to account for spatial differences in sizes and ages observed in fisheries along the coast. The most recent assessment in 2015 instead modeled three distinct areas along the coast, but assumed biological relationships and fishery selectivity were constant across latitudes [@thorson_status_2016]. Research since the previous assessment indicates that canary rockfish are genetically well-mixed along the U.S. west coast [@budrick2016evolutionary], that the previous assessment model had poor numerical stability, and that the spatially explicit parameters that the model attempted to estimate were not in fact identifiable [@monnahan2019overcoming].

Spatial models have commonly been utilized for populations where spatial differences in growth and/or movement exist [@punt_spatial_2019], but have also been applied for populations with regional differences in catch histories [@cope2011reconciling]. In these situations spatial models have generally performed well. However, research has also argued for parsimony [@goethel_awareness_2023], and identified that there are tradeoffs in model stability [@punt_spatial_2019] and performance [@punt_pinkling_2015]. There is limited evidence suggesting biological differences among regions and little information to inform movement dynamics for spatial models of `r spp`. The 2015 assessment also found results from a spatial model and single-area (coastwide) model were similar [@thorson_status_2016]. For these reasons, and because early attempts to maintain the spatial structure applied in the 2015 assessment to the 2023 base model indicated model instability, we return to the historical single-area (coastwide) model for this assessment with fishery selectivity generally estimated by state (Figure \ref{fig:map}).

## Life History

Canary rockfish are a medium to large-bodied rockfish and achieve a maximum size of around 70 cm. Female canary rockfish reach larger sizes than males. Canary rockfish are relatively long-lived, with a maximum observed age in the literature of 84 years. However, in both the California Current and the coastal waters off British Columbia, only males are commonly observed above the age of 50, while females tend to be rare above age 30. The degree to which this pattern reflects behavioral differences translating to reduced availability to fishery and survey fishing gear, or an increase in relative mortality for older females has been the focus of much discussion and remains unclear. A similar pattern has been observed for yellowtail rockfish (*Sebastes flavidus*) and black rockfish (*Sebastes melanops*), two closely related species [@wallace2004yellowtail; @cope_assessments_2016; @rasmuson2023finding]. Since the 2002 assessment, this pattern has been accommodated within the stock assessment model by allowing female natural mortality to increase at approximately the age of first sexual maturity, as justified by an increase in behavioral risk or physiological stress resulting from female spawning.

Adult canary rockfish primarily inhabit areas in and around rocky habitat. They form very dense schools, leading to an extremely patchy population distribution that is reflected in both fishery and survey encounter rates, and this distribution strongly affects the calculation and interpretation of population indices and age- or size-composition data. Juvenile canary rockfish are found in shallow and intertidal areas [@love2002rockfishes]. Canary rockfish spawn in the winter, producing pelagic larvae and juveniles that remain in the upper water column for 3-4 months [@love2002rockfishes]. These juveniles settle in shallow water around nearshore rocky reefs, where they may congregate for up to three years [@sampson1996canary; @boehlert1984variability] before moving into deeper water. The mean size of individuals captured in the trawl survey shows a characteristic ontogenetic shift to deeper water with increasing body size. In addition, the age and size of canary rockfish appears to vary by latitude, with the oldest largest fish occurring in more northerly latitudes and declining southward along the coast, with some evidence of breakpoints in size occurring along central California or southern Oregon [@keller2018canary; @Brooks_thesis_2021].

The most recent research indicates limited stock structure of `r spp` along the U.S. west coast. Limited tagging research conducted off Oregon found that of 10 canary rockfish recovered, 4 moved over 25 km, and 3 moved more than 100 km over a period of several years [@demott1982movement]. A single canary from that study moved 326 km to the south, and those that moved the farthest also moved to much greater depths than the shallow reefs at which they had been tagged. Another study in central and southern California tagged 13 `r spp` but recaptured none [@hanan_tag_2012]. Early genetic research found patterns suggestive of some population structuring between the northern California/southern Oregon and northern Oregon/southern Washington, but this work was based on limited sampling and also found evidence of reduced gene flow between shallow and deeper areas [@wishard1980stock]. Using modern population genetic methods [@gomez2003microsatellite], Budrick [-@budrick2016evolutionary] found little support for population structure of canary rockfish within the California Current. Supporting the genetic analysis, otolith microchemistry indicates no differentiation in natal or juvenile habitat between `r spp` collected in Oregon and Washington waters [@gao2013isotopic].

There are few biogeographic boundaries clearly applicable to rockfish on the U.S. and Canadian west coasts. However, canary rockfish are not found in large numbers south of Point Conception. The divergence zone at the northern edge of Vancouver Island likely creates a barrier for pelagic dispersal and productivity for many species [@ware1989fisheries]; therefore it is the southern portion of the B.C. canary resource that is most likely to have dynamics linked to the U.S. resource. It is likely that canary rockfish cross the U.S. Canadian border as pelagic larvae, juveniles, and possibly adults making their ontogenetic shift to deeper water or moving between areas of rocky habitat.

The 2002 assessment integrated what had previously been separate north-south assessments based on the observations of highest density occurring near headlands and \gls{inpfc} boundaries commonly used to delineate management and assessment areas [@methot2002canary]. They reasoned that splitting stocks or assessments at any \gls{inpfc} boundaries would divide high-density areas that most likely are biologically linked. This logic was followed in the 2005 benchmark assessment and subsequent 2007 and 2009 update assessments, separating fishing fleets geographically to account for potential spatial patterns while retaining a coast-wide assessment area. All U.S. assessments have used the U.S.-Canadian border as the northern boundary for the stock, although the basis for this choice appears to be largely based on both (1) consistency with current management needs, and (2) data availability and feasibility of expanding data from multiple jurisdictions within a single stock assessment.

## Ecosystem Considerations

Canary rockfish are reported to have a diverse diet. Pelagic juveniles consume copepods, amphipods and krill, while adults consume krill and many species of small fish [@love2002rockfishes]. The California Current Trophic Database includes records of `r spp` consuming amphipods, copepods, euphausiids, isopods, mysids, pandalid shrimp, myctophids, herring, and chaetognaths, as well as unidentified bony fish and crustaceans [@bizzarro_etal_2023]. The degree to which variability in food supply may affect body condition, spawning success or annual growth is unknown. Young-of-the-year `r spp` have been reported in stomachs of Chinook and coho salmon [*Oncorhynchus tshawytscha* and *Oncorhynchus kisutch*, @thayer2014changes; @bizzarro_etal_2023], and they are also consumed by seabirds [@warzybok2018prey]. Although `r spp` are difficult to identify to the species level in stomach contents, they are likely preyed upon by other large fish such as lingcod (*Ophiodon elongatus*). A 47 cm `r spp` was once reported in the stomach of a 24 kg Lingcod off the coast of Monterey, California [@phillips1959review]. According to a recent California Current climate vulnerability analysis that ranked species on a scale of low, moderate, high, and very high, `r spp` have high exposure and high sensitivity to climate change, similar to most rockfish [@mcclure2023vulnerability].

Although ecosystem factors have not been explicitly modeled in this assessment, there are several important aspects of the recent California current ecosystem that appear to warrant consideration. Lingcod, a potentially important predator of small canary, have rebuilt over the last two decades [@johnson2021lingcod_s; @taylor2021lingcod_n]. To the extent that the component of natural mortality of canary rockfish added by predation from Lingcod and other predators has been increasing over recent years, recruitment may be underestimated. This effect could also lead to longer than predicted recovery times for canary rockfish [@oken2016evaluating]. Conversely, Pacific salmon are known to consume young canary rockfish, and their populations have generally declined in recent years [@bizzarro_etal_2023]. Canary rockfish productivity as estimated in the last assessment is significantly associated with the \gls{pdo} [@mantua_pacific_1997; @bell2023changes], and growth and condition were also found to be associated with the \gls{pdo} and other basin-scale indices [@keller2018canary]. However, relationships between productivity of fish populations with non-mechanistic basin-scale indicators such as the \gls{pdo} have been degrading in recent years due to climate change [@litzow2020changing; @werb2023remarkable], so these relationships may not be reliable predictors moving forward. In contrast to predictions from the climate vulnerability analysis, there is evidence that canary rockfish productivity has been trending upward recently [@bell2023changes]. The prevalence of a strong 1999 year-class for many west coast groundfish species suggest that environmentally driven recruitment variation may be correlated among species with relatively diverse life-history strategies [@stachura2014linking; @thorson2013using]. Much research is currently underway to explore these phenomena, and it appears likely that more explicit exploration of ecosystem processes and influences may be able to be incorporated into management both within and outside of future canary rockfish stock assessments.

## Historical and Current Fishery Information

`r Spp` is caught in both commercial and recreational fisheries off the U.S. West Coast, with the majority of catches coming from commercial sources (Tables \ref{tab:catches1}--\ref{tab:catches2}, and Figure \ref{fig:catches}). The rockfish fishery off the U.S. West Coast developed off California late in the 19th century and was catching an average of almost 2,500 metric tons per year over the period 1916-1940 (with an increase in catches in 1916, during World War I). To the north, the rockfish fishery developed slowly and became established during the early 1940s, when the United States became involved in World War II and wartime shortages of red meat created an increased demand for other sources of protein [@alverson1964study; @harry_history_1961]. Rockfish catches dropped somewhat following the war, and were generally stable from the 1950s to the 1960s.

Historically, the vast majority of canary rockfish off the U.S. West Coast have been harvested by commercial trawling vessels, followed by hook-and-line (primarily vertical longline), shrimp trawls, and various miscellaneous gears (e.g., nets and pots). In 1977, when the \gls{msfcma} was enacted, the large foreign-dominated rockfish fishery that had developed since the late 1960s had its catches eliminated, and the domestic trawl fishery subsequently increased its catches. Canary rockfish were also sought by recreational anglers and considered to be a moderately important species caught in the private vessel and charter boat fisheries off Washington, Oregon, and northern California.

Inspection of the historical catch reconstructions for canary rockfish (see Section \@ref(removals) for details) shows that reconstructed catches from 1892 to 2022 were highest historically in the trawl and foreign fisheries (Figure \ref{fig:catches}). The trawl (TWL) fishery was high around the end of World War II (1945: 3,724 mt), but decreased during the 1950s-1960s. A foreign fleet (FOR) operated 1966-1976, and nearly exceeded the domestic trawl landings in 1966 (TWL: 1,658 mt, FOR: 1,599 mt). The foreign fleet was replaced by the domestic bottom trawl fleet following the \gls{msfcma} (1978 TWL: 3,945 mt). The trawl fishery reached a peak in the early 1980s (1982: 5,155 mt) and subsequently decreased after the establishment of strict management restrictions starting in the mid-1990s. The decrease in the trawl fishery allowed the recreational and non-trawl fisheries to take a larger proportion of total catch beginning in the 2000s. Following the removal of the overfished designation due to findings from the 2015 assessment [@thorson_status_2016], catches increased considerably, though to levels well below those seen during much of the period of industrial fishing. Today, most catch still occurs in the trawl fishery (particularly in a growing midwater trawl fleet), though there is a sizable recreational (REC) component of landings as well (2022 TWL: 507 mt, REC: 152 mt). Trawl catches are highest in Oregon, whereas non-trawl and recreational catches are highest in California.

## Summary of Management History and Performance

The first regulations established on the canary rockfish fishery off the U.S. West Coast were implemented in 1983 as trip limits (40,000 lb. per trip) on the entire *Sebastes* complex (a market category that included all rockfish species except Pacific Ocean perch *Sebastes alutus* and widow rockfish *Sebastes entomelas*) harvested from the U.S. Vancouver and Columbia \gls{inpfc} areas [@pfmc2002status]. Commercial vessels were not required to separate most rockfish catches into individual species, but rather, only into mixed-species categories, such as the *Sebastes* complex. Port biologists in each state routinely sample market categories (e.g., *Sebastes* complex) to determine the actual species composition of these mixed-species categories. Since 1967, various port sampling programs have been utilized by state and federal marine fishery agencies to determine the species compositions of the commercial groundfish landings off the U.S. West Coast [@sampson_commercial_1997]. Stratified, multistage sampling designs are currently used in the port sampling programs for purposes of evaluating the species compositions of the total landings, as well as for obtaining biological data on individual species [@crone_sampling_1995; @sampson_commercial_1997].

From 1983 through 1994, canary rockfish were monitored as part of the *Sebastes* complex, with various trip limits imposed over this 10-year span. In 1993 and 1994, commercial fishermen communicated that fewer canary rockfish were being caught in their rockfish tows [@pfmc2002status]. The 1994 canary rockfish stock assessment [@sampson1994canary] confirmed that the observed declines in the field were likely the result of a population that had not responded favorably to recent levels of fishing pressure and further recommended that the canary rockfish \gls{abc} be reduced to allow the stock to recover. Beginning in 1995, the \gls{abc} for canary rockfish was reduced nearly 60%, to 1,250 mt. In 1995, trip limits specific to canary rockfish (cumulative monthly trip limit of 6,000 lb.) were imposed and commercial vessels were required to sort canary rockfish from other rockfishes. In 1998, catches of canary rockfish were regulated using a two-month cumulative trip limit of 40,000 lb. for the Sebastes complex, of which, no more than 15,000 lb. (38%) could be composed of canary rockfish. That is, although this species was allocated its own market category, it was still being managed as part of the mixed-species complex. The \gls{abc} was further reduced to 1,045 mt.

The two stock assessments conducted in 1999 (California and Washington-Oregon) found the stock to be depleted and an overfished determination was made in 2000. Subsequently, commercial and recreational fishing opportunities were severely restricted and removals were mainly from bycatch. Canary rockfish became a limiting species for fisheries that target other commercially important species on the continental shelf. The \gls{oy} in 2003 was 44 mt; which was only about 1% of the peak annual catches in the early 1980s. Management regulations were sufficiently strict to keep the catch that year to only 51 mt. During the overfished time period, the fishery was far below \gls{abc} levels. Shelf rockfish species (including canary) could no longer be retained by vessels using bottom trawl footropes with a diameter of greater than 8 inches. The use of small-footrope gear increases the risk of gear loss in rocky areas, and this restriction was intended to discourage trawlers from fishing in high-relief, rocky habitat. The impact of the change in gear regulations was reinforced through reductions in landing limits for all other shelf rockfish species.

In 2002, the trawl and non-trawl \glspl{rca} were implemented as depth-based closed areas to reduce bycatch of overfished rockfish species such as canary rockfish in the northern portion of the coast and bocaccio (*Sebastes paucispinis*) in the south. Specific boundaries for the trawl \gls{rca} have varied across bimonthly periods within and among years in response to changing discard rates and fishery dynamics. There was generally a dynamic pattern of the closed area extending from the shoreline (or 75 fm) out to 150 fm (274 m), 200 fm (366 m) or 250 fm (457 m). Deeper depths are generally closed in the winter months and there are a number of latitudinal differences in the extent of the current \gls{rca}; however the large majority of depths deeper than 75 fm (137 m) where canary rockfish occur were closed to all commercial on-bottom fishing for groundfish. It is possible that by closing most of the depth range of the species the RCA influenced the size range of `r spp` available to the fishery. The \gls{pfmc} eliminated the trawl \gls{rca} off of the coasts of California and Oregon in 2018, and the decision went into effect in 2020. The non-trawl \gls{rca} has also seen relaxation for some gear types over certain latitudes in recent years. 

Beginning in 2005, the modified "flatfish" trawl gear was required shoreward of the RCA. This gear was found to reduce the catch-per-unit-effort of canary rockfish relative to standard commercial gear in pilot experiments [@king_protecting_2004]. Recreational limits were also substantially reduced for more than a decade. After first reducing bag limits, starting in 2003 all three states allowed no retention of canary rockfish during recreational fishing. From 2005 to the end of the overfished designation, mortality associated with recreational fishing was primarily comprised of discard mortality from fish caught while targeting other species such as Pacific halibut (*Hippoglossus stenolepis*) or other rockfish.

A groundfish trawl rationalization program was commenced in 2010 via Amendment 20 to the Groundfish Fisheries Management Plan. Under this program, groundfish limited entry trawl vessels making shoreside deliveries are managed primarily through a system of \glspl{itq}. Trawl permit holders were provided with quota share percentages of the allowable catch of major species and assemblages, based on historical fishery participation. After \glspl{acl} are set for species for a given year, the shares are used to calculate individual quotas (in weight) that represent the amount of species' catch the permitted individual (and associated vessel) are entitled to catch. Unlike previous management, which relied on limiting the landings of vessels, the new system holds individual vessels responsible for retained and discarded catch. Discard amounts are verified by 100% at-sea observation of participating vessels. Vessel accountability for discards has generally led to a reduction in fleet discards since implementation for Pacific rockfishes as a whole. A system for tracking quota balances was also created, and vessels are not allowed to fish when they have negative balances for any species/assemblage. Quota pounds have been transferable between permit holders since the program's beginning, and now the shares of most species may be sold. Accumulation of shares or pounds is subject to accumulation and usage caps. Additionally, the program provided the opportunity for trawl pounds to be fished with other gears on qualified vessels ("gear switching").

Catch accountability for motherships and associated catcher-vessels in the mothership sector for Pacific hake (*Merluccius productus*) was achieved through a system of regulated cooperatives. Pacific hake catcher-processors operated for years as a voluntary cooperative, and that arrangement was formalized by provisions of Amendment 20 [@fed_registry_1992]. Cooperatives in both of these sectors received annual poundage allocations of hake and non-hake species, based on the entitlements of cooperative members, and these amounts are not transferable between cooperatives. There is also no provision for voluntary transfers of pounds or shares between fishery sectors. Beginning in 2020, the separate allocations for catcher-processors and motherships were combined into a single at-sea hake set-aside.

Canary rockfish was declared rebuilt following the 2015 stock assessment [@thorson_status_2016]. As a result, in 2017 the ACL increased more than tenfold from 125 mt to 1714 mt (Table \ref{tab:acls}). Catches increased substantially following this relaxation, especially in the recreational fishery and in a growing midwater trawl fishery (Figure \ref{fig:catches}). Since rebuilding, total mortality (catches plus dead discards) has generally been around 40% of the ACL. Areas and depths previously restricted have since started to reopen.

## Foreign and Alaska Fisheries

Canary rockfish in Canadian waters off the coast of British Columbia appear to have similar life history characteristics to those found off the U.S. West Coast. Similar to the U.S. West Coast, male age samples display a long tail past 60, but there are few females older than 40 [@dfo2023canary]. A 2022 assessment successfully estimated both male and female natural mortality (constant across ages) as 0.065 and 0.093 yr$^{-1}$, respectively [@dfo2023canary]. The canary rockfish population in Canadian waters reached a similar trough around 2000 to that observed in the U.S. [@dfo2023canary]. Removals are dominated by the trawl fishery and by catches off the west coast of Vancouver Island [areas 3C and 3D, @dfo2023canary]. Catches were highest (\>1200 mt) in the decade from 1986-1995, and then declined and have remained relatively stable since, averaging around 800 mt since 1996, and around 540 mt during that time for the west coast of Vancouver Island [@dfo2023canary].

It is difficult to conclude what the current status of canary rockfish is off of Alaska. The \gls{npfmc} assesses and manages canary rockfish as a minor part of an assemblage including seven species of demersal shelf rockfishes [@joy2022assessment]. The primary component of this group is yelloweye rockfish (*Sebastes ruberrimus*), although quillback (*Sebastes maliger*), copper (*Sebastes caurinus*), China (*Sebastes nebulosus*), tiger (*Sebastes nigrocinctus*) and rosethorn (*Sebastes helvomaculatus*) rockfishes are also included. No species in the assemblage are the target of a commercial fishery. Yelloweye rockfish biomass is estimated from an autoregressive random effects model applied to submersible biomass estimates (crewed 1994-2009, and remotely operated 2012-2022) and the \gls{iphc} longline survey [@joy2022assessment]. A bayesian state-space surplus production model that incorporated catches was also recently presented as a research model. Canary rockfish, in particular, is managed as Tier 6, and no direct indices of canary rockfish abundance in the Gulf of Alaska have been reported.
