## Base Model Results

### Parameter Estimates

The base model parameter estimates along with approximate asymptotic normal standard errors (SD column) are shown in Table \ref{tab:params}. This table enumerates a total of `r dplyr::filter(model$parameters, Phase > 0, !grepl('ForeRecr', Label)) |> nrow() - 1` estimated parameters. These include one parameter for ln(R~0~), one parameter for female natural mortality, nine parameters describing growth, one parameter for survey catchability in the \gls{s-tri}, one parameter for extra variability for the pre-recruit survey, `r dplyr::filter(model$parameters, Phase > 0, grepl('Size', Label)) |> nrow()` parameters for length-based selectivity and blocks along with `r dplyr::filter(model$parameters, Phase > 0, grepl('SzSel', Label)) |> nrow()` parameters for sex-dependent selectivity and blocks, and `r dplyr::filter(model$parameters, Phase > 0, grepl('Main_RecrDev|Early_RecrDev', Label)) |> nrow()` recruitment deviations. The likelihood components from fitting the base model to data are shown in Table \ref{tab:like}. The estimated data weights by the Francis method are shown in Table \ref{tab:data-weights}.

The full r4ss plotting output is available in the supplementary material on the [Pacific Fishery Management Council website](https://www.pcouncil.org).

#### Biology Parameters

The estimates of growth parameters by sex varied relative to the externally estimated parameters (Table \ref{tab:params}). The length-at-age 1 for both sexes were less than the external estimates using the survey age data while the $L_\infty$ estimates for both sexes were higher than the external estimates. The estimated $k$ for females and males was greater than the values estimated externally, with the value for females being more similar. Although estimated growth differed from external estimates, external estimates were within the 95 percent confidence interval (with males near the lower edge) given the estimated uncertainty from the model (Figure \ref{fig:mod-est-len-age}). The coefficient of variation in growth was assumed to be function of length-at-age. Estimates for the coefficient of variation at $L_\infty$ were approximately half those at length-at-age 1 for males and females. However, given the estimates for length at older and younger ages, this still results in greater variability in length at larger sizes.

#### Selectivity

Estimated selectivity curves are shown in Figure \ref{fig:comm-selex-female} and \ref{fig:noncomm-selex-female} for females and Figures \ref{fig:comm-selex-male} and \ref{fig:noncomm-selex-male} for males, with selectivity parameters provided in Table \ref{tab:params}. Nearly all fleets show a strong dome-shaped pattern with the exception of 1) selectivity for females by the Oregon and Washington trawl fleets from 2000--2011 2) selectivity for females by the Oregon non-trawl fleet prior to 2000 and after 2019, 3) selectivity for both sexes by the \gls{s-tri}. Sensitivity to allowing for one asymptotic fleet is shown in section \@ref(sensitivities).

For the trawl fleets, the length at peak selectivity is greatest prior to 2000, with the California peak at 46 cm and the mirrored Oregon and Washington peak at 49 cm. Selectivity shifts towards smaller fish in recent time periods between 3--6 cm depending on the fleet and time block. The pattern of dome-ness between time periods is stronger in California in recent years whereas for Oregon and Washington the curve tends to shift towards smaller fish, and to an asymptotic pattern between 2000-2011. The foreign fleets are mirrored to the trawl fleets and have the same selectivity curves.

For the non-trawl fleets, the patterns in selectivity are more variable, reflecting the sparseness of the composition data. In California, selectivity for smaller fish is greater in the non-trawl fleet than in the trawl fleet, with a peak at 36 cm. The range of lengths selected is more compressed but has shifted towards larger fish by 2 cm in the most recent years compared to before 2000. The selectivity curve has changed the most over time in Oregon. Prior to 2000, the peak in selectivity was 55 cm. It then decreased to 33 cm in the 2000s, and increased to 45 cm in the most recent period. The Washington non-trawl fleet has sparse data so is modeled as having constant selectivity across time, with a peak at 47 cm.

The at-sea hake fishery has mirrored selectivity across each state given the similarities in the fishery along the coast. The selectivity curve is more narrow than that for either the trawl or non-trawl fleets, with a steep increase around 40 cm and peak at 44 cm. No time-varying selectivity is applied to the at-sea hake fishery.

For the recreational fishery, the length at peak selectivity is shifted towards smaller fish compared to the commercial fleets. Selectivity increases sharply and reaches a peak of 29 cm in California, 30 cm in Oregon and 34 cm in Washington. For all fleets, selectivity in the earlier time periods is shifted towards smaller fish. Selectivity for Washington shifts greatly in 2021-2022 to a peak of 48 cm, which may be due in part to being the last two years, whereas the recent block for other fleets includes earlier years. All recreational fleets show strong dome-ness, with the greatest decline during the period of non-rentention.

The \gls{s-wcgbt} and \glspl{s-tri} are estimated to have a slowly increasing selectivity curve across a wide range of lengths; starting at very small sizes and increasing to a peak near 43--44cm. This likely reflects the spatial and bathymetric coverage and non-targeting nature of the survey design compared to the fishery. Selectivity for the \gls{s-wcgbt} declines for larger individuals whereas for the \gls{s-tri} selectivity is nearly asymptotic. No time-varying selectivity is applied for the surveys, and the \gls{s-tri} is mirrored across the early and late period.

For all fleets and surveys, male selectivity shows a greater dome-ness than females. This is likely compensating for a lower availability of large females given that their natural mortality estimate is higher than males. Thus, greater selectivity for females allows them to be selectied for at a rate proportional to their occurrence in the population, which is less than males due to greater mortality. This also allows for effective fishing mortality on larger and older females to be greater than for males, such that both natural mortality and fishing mortality contribute to the smaller number of old females observed.

#### Catchability

Catchability for surveys comparing observed to expected vulnerable biomass across all years was analytically solved for the \gls{s-wcgbt} and pre-recruit survey, and estimated for the \gls{s-tri}. The \gls{s-tri} was mirrored across the early and late period so catchability was equivalent. The values for catchability of the adult surveys are commensurate with surveys for a species that is partially inaccessible and caught on a subset of tows (Tables \ref{tab:wcgbts}, \ref{tab:triennial}). Catchability in regular space was calculated as `r round(model$cpue$Calc_Q[1], 2)` for the \gls{s-wcgbt}, `r dplyr::filter(model$cpue, grepl('prerec', Fleet_name)) |> head(1) |> dplyr::select(Calc_Q) |> as.numeric() |> round(2)` for the pre-recruit survey, and estimated to be `r dplyr::filter(model$cpue, grepl('Tri_early', Fleet_name)) |> head(1) |> dplyr::select(Calc_Q) |> as.numeric() |> round(2)` for the mirrored \gls{s-tri} (Table \ref{tab:params}). Additional survey index variability for the pre-recruit survey that is process error added directly to each year's input standard deviation was estimated within the model at `r dplyr::filter(model$parameters, grepl('extraSD', Label)) |> dplyr::select(Value) |> as.numeric() |> round(2)` Fits to adult surveys were near enough to confidence intervals of the estimates of the survey that down-weighting the survey data by estimating additional variability was not warranted.

#### Stock-recruit Parameters

In this assessment the natural logarithm of $R_0$ was estimated, while steepness was fixed at its prior mean of 0.72. Lognormal deviations from the standard Beverton-Holt stock-recruit relationship were estimated from 1892-2022 with a fixed $\sigma_R$ value of 0.5. There is limited information regarding recruitment prior to 1960 but deviations are estimated in the base model to account for uncertainty around the unfished condition to a degree consistent with estimated variability in recruitment. The time series of estimated recruitments and annual recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. The spawner-recruit curve is shown in Figure \ref{fig:bh-curve}.

Years with the highest recruitment deviations were estimated to have occurred in the 1960s and continued through 2000. Starting around 2004 recruitment deviations became more consistently negative and reached their nadir in 2018. This period corresponds to a period of relatively sparse composition data. Deviations have increased to average levels since 2018 but these deviations are more uncertain given the few years available to sample these age classes. The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias-adjust}. This relationship was updated during early model exploration with the final version near to the suggested alternative provided within r4ss such that it was left at the earlier values. Similarly, the value of $\sigma_R$ was tuned to match the observed variation in recruitment deviations, following @methot_adjusting_2011, and as provided in r4ss. The tuned value was similar (0.47 for the period 1960-2022) to that already used (0.5) so the value of 0.5 was retained.

### Fits to the Data

Fits to the data are shown based on the Pearson residuals for length and marginal age compositions, annual mean lengths and ages, and aggregated length and marginal age composition for the fishery. For the surveys, similar metrics were used; however, fits of ages are conditioned on length, and fits to the survey indices are also provided. For simplicity in writing up the fits to data within this section, we refer to marginal age compositions as simply age compositions.

The aggregated fit to the length composition data by fleet is shown in Figure \ref{fig:len-agg-fit}. Fits are generally consistent with observed data aggregated over all years for males, females, and combined when sex-specific data are unavailable. Fits balance the bimodal patterns for Oregon and Washington recreational data and Oregon non-trawl data, and are generally consistent for both Washington and Oregon trawl data, where selectivity was mirrored. The mode of proportion at length is generally larger for females than males in trawl gear, reflecting the dimorphic growth in canary, but are similar for other gears.

Pearson residual plots by fleet (fishery and survey) as well as mean lengths by year observed from the composition data are shown in (Figures \ref{fig:len-pearson1}--\ref{fig:mean-len-fit30}). Yearly mean length is variable for `r spp`, particularly for non-trawl fleets both in terms of sample sizes within and across years. However, patterns are still discernible. Patterns in length data indicate a declining trend in mean length of about 5 cm in the fishery starting in the early years (1980s) when data is available. The decline is best captured in the fit to the Oregon trawl lengths, although the fit declines around 3 cm and thus underestimates the decline in mean length data. The decline is also present to a lesser extent in the fit to California and Washington trawl lengths. Fits also reveal an increase in mean length in recent years (up to 7 cm in California non-trawl data but less for other fleet), which is best captured by fits to the non-trawl and recreational fleets within the final time-varying selectivity block of each fleet. Patterns in mean length for the at-sea hake fishery and the surveys are generally uninformative.

The aggregated fit to the age composition data by fleet is shown in Figure \ref{fig:age-agg-fit}. Fits are generally consistent with observed data aggregated over all years for males and females despite selectivity being based on lengths. Fits are best for the trawl fleets, and poorer for Oregon and Washington non-trawl data, which are sparse and variable. Fits do not capture the steeper decline and early long tail in the proportion of older fish in the recreational fleets. The mode of proportion at age is generally similarly for females and males, in contrast to the patterns in length, especially for the trawl gear. The aggregated age compositions show that general patterns of increasing selectivity for young individuals, and declining proportion at age for old individuals, are generally captured. Summaries also exhibit the greater proportion of males in the plus-group (age 35+) than females for the trawl fleets.

Pearson residuals plots by fishery fleet as well as mean age by year observed from the composition data are show in (Figures \ref{fig:age-pearson1}--\ref{fig:mean-age-fit12}). The range of ages cover a larger range of modeled ages compared to the length samples, but patterns are comparable to those observed from the length composition fits. Patterns in age data also indicate a declining trend in mean age in the fishery starting in the early years (1980s) when data is available. The decline is best captured in the fit to the Oregon trawl ages, which although the fit underestimates the decline in mean age, declines from approximately a mean age of around 20 to a mean age of 11. Fits to California trawl ages also indicate a long term decline but are sparse. Fits to Washington trawl ages are overestimated relative to observed data, but also indicate a decline in mean age, albeit from younger ages than the Oregon trawl trend. As with lengths, recreational mean ages are lower and suggest an increase in mean age in recent years. Patterns in mean length for the non-trawl and at-sea hake fleets are generally uninformative.

Pearson residuals of conditional age-at-length compositions are shown for each survey (Figures \ref{fig:caal-pearson28_1}--\ref{fig:caal-pearson30}). These show variability in length at age over time, which is propogated into model uncertainty through the use of conditional-age-at-length data. Positive residuals near the lower range of the data exist for the early \gls{s-tri} and recent years of the \gls{s-wcgbt}. These suggest that older male `r spp` at length are observed than estimated in the model for these years, which is consistent with our comparison of externally estimated growth parameters for males being near the lower uncertainty range for growth estimated internal to the model. Predictive plots, where a well-fitting model has a predicted average and standard deviation of age-at-length that is within the 95% predictive interval, are available within the r4ss documentation available online. Predictive plots for all surveys generally show fits are within the 95% predictive interval, indicating no evidence of poor fit to conditional age-at-length data. This suggests that a model with time-constant growth provides a satisfactory approximation to the process governing age and length.

Fits to indices of abundance are shown for each survey fleet (Figures \ref{fig:wcgbts-fit}--\ref{fig:prerec-fit}). These plots show that fits to the \gls{s-wcgbt} indices are generally within the 95% confidence interval bounds with the exception of 2009 and 2019. With 19 years of survey data, approximately one year is expected to fall outside of the 95% confidence interval, and two falling outside the range would not be an usual occurrence. The residuals appear randomly distributed, with no particularly long strings of positive or negative values. The survey index increases slowly, with a minor break point between a "low" state until 2013 and a "high" state thereafter. The triennial survey captures the general decline in population abundance during the 1980s and early 1990s and the beginning of rebuilding in the late 1990s and early 2000s. The model is unable to capture the sharp rise and fall at the beginning of the time series, and thus falls outside of the 95% confidence interval in 1980 and 1983. The pre-recruit survey captures high estimated recruitment events in 2013, 2016, and 2021, though the model underestimates recruitment in 2016 relative to the survey. The model falls outside of the input 95% confidence in five years (2002, 2004, 2007, 2009, and 2016), but in no years when including the extra estimated standard deviation. Sensitivity to estimation of this additional variability is included in Section \@ref(sensitivities).

### Population Trajectory

Summary time series of population trajectories are provided in Table \ref{tab:timeseries}. Total mortality estimates for 2023 and 2024 were provided by the \gls{gmt}. The estimated spawning output (in millions of eggs) is shown in Figure \ref{fig:ssb}, total biomass in Figure \ref{fig:tot-bio}, spawning output relative to unfished in Figure \ref{fig:depl}, and fishing intensity measured as one minus the spawning potential ratio (1-SPR) in Figure \ref{fig:spr}. Spawning output declines from the 1940s with the increase in harvest (Figure \ref{fig:catches}), stabilizes in the 1970s, and then declines to its lowest point in 1995. Spawning output stabilizes until 2000 when levels increase steadily to recent years with a slowing trend. The estimated total biomass follows the same general trend as observed in spawning output but with a more pronounced decrease from 1980 to 1995 (Figure \ref{fig:tot-bio}). The estimated spawning output relative to the unfished equilibrium spawning output was at its lowest (`r round(100*min(model$sprseries$Deplete,na.rm=TRUE), 1)` percent) in 1995 and has since increased. It is currently within the precautionary zone at `r round(100*model$current_depletion, 1)` percent for 2023 (Figure \ref{fig:depl}). Population trajectories track the patterns in fishing intensity, where fishing intensity was steadily above a fishing mortality that would produce an SPR of 0.5 starting in the 1960s and lasting nearly four decades (Figure \ref{fig:spr}). Fishing intensity has been low since 2000 but has recently increased to a fishing mortality corresponding to an SPR of near 0.5.
