## Model Diagnostics

### Convergence Status

The base model has a final gradient of \<0.00001 and the hessian is determinant. We therefore conclude that the parameter estimates represent a global minimum. No parameters are at or within 2.5 percent of a boundary but two parameter pairs have high correlation coefficients (0.97) with four others between 0.90 and 0.95.

#### Evidence of Search for Global Convergence

A search for global convergence was conducted multiple times during model development, and these led to the choices described within this report for developing the current model. Analyses from earlier models suggested the likelihood surface was flat around the maximum likelihood estimate, and found some improvements in the likelihood value. However, model trajectories were similar suggesting improvements in the likelihood surface did not greatly change model dynamics.

Model convergence of the current model was determined by starting the minimization process from dispersed values of the maximum likelihood parameter estimates. Starting parameters were jittered using the jitter function built into Stock Synthesis, using a jitter fraction of 0.05. This was repeated 50 times with ten runs returning to the original best likelihood value, and five runs being very close at just 0.01 likelihood units above. No jitter runs resulted in an improved likelihood value. Given that this jitter analysis did not result in a final better likelihood value, we conclude the model has obtained a global optimum, and we proceed with this model as the current base model. Profiles of key parameters (Section \@ref(likelihood-profiles)) and sensitivity runs (Section \@ref(sensitivities)) also did not show evidence of instability and support the conclusion from the jitter analysis. 

### Sensitivity Analyses {#sensitivities}

The base model contains substantial uncertainty in both how data were processed, and structural assumptions made. We test senstivity to a number of these assumptions. In general, structural assumptions regarding how productive the population is and how the model handles the relative lack of old females in age composition data led to the strongest changes in model outputs (Figure \@ref(fig:sens-summary)). All sensitivities with the exception of the bomb radiocarbon age bias led to relatively similar estimates of growth parameters, indicating growth is well-estimated in the model and we do not discuss it beyond the bomb radiocarbon sensitivity (Tables \@ref(tab:data-sens)--\@ref(tab:prod-sens)). We divide the sensitivities into four groups: how data are prepared, how data are weighted, selectivity and catchability, and population productivity.

#### Data Choices

Compiling data for the assessment model required a number of choices and assumptions. The following sensitivity models fall under data choices:

-   No sparse comps: exclude all year-fleet combination of length and age composition data with input sample sizes less than five.

-   Pre-recruit data: include pre-recruit survey index from 2010, 2012, and 2022 which had more limited sampling.

-   Canada catch: add catches from the west coast of Vancouver Island to Washington trawl and non-trawl fleets

-   Catch SE 0.1: Increase the uncertainty in input catches from 0.05 to 0.1 for years before 1980. Years before 1980 approximate the period with less extensive sampling, and where historical reconstructions are used to estimate catch. Adjusting catch standard error was done in lieu of manually changing catch streams to "low" and "high" scenarios.

-   Bomb radiocarbon age error: Recent research based on radiocarbon signatures in otoliths from the atomic testing era indicates that `r spp` ages based on otolith annuli may be biased negatively by approximately 10% from the true age (A. Stephens, NWFSC, personal communication, 4/19/23). This sensitivity assumes all readers have an additional 10% negative ageing bias from whatever bias was assumed in the base model.

Overall, decisions with respect to input data had a low impact on model outcomes (Table \@ref(tab:data-sens), Figures \@ref(fig:data-ssb-compare) and \@ref(fig:data-bratio-compare)). Sensitivities generally led to similar current biomass levels, but varying estimates of unfished biomass, leading to somewhat different depletion estimates. Still, in all cases depletion in 2023 was within the 95% confidence interval of the base model. Models produced similar estimates of female natural mortality. The bomb radiocarbon sensitivity produced a somewhat lower estimate because the additional ageing error bias allows for more older fish in the population than the base model assumes. The bomb radiocarbon sensitivity also had a higher unfished and recent biomass (within the base model 95% confidence interval), higher depletion (within base model 95% confidence interval), and lower estimates of von Bertalanffy growth rates (slower growth) because the sensitivity increases all ages by 10%, but leaves lengths unchanged. Including Canadian catches predictably increased the population scale substantially, well outside of the 95% confidence interval. Because Canadian fishing continued during the period `r spp` was declared overfished in the U.S., including Canadian catches also resulted in a more muted recovery and somewhat lower depletion in 2023.

#### Data Weighting

The assessment model contains data from a variety of sources, some of which are expected to be more informative than others. Sampling units from these different data sources are not necessarily comparable (e.g., an observation from a survey index versus an observation of a fish length). Data weighting procedures are objective algorithms that can be used to assign weights to different data sources to optimize the fit of the model to the data. The following sensitivity models fall under data weighting:

-   McAllister-Ianelli data weighting: Use the algorithm suggested by @mcallister_bayesian_1997 instead of @francis_data_2011

-   No extra SD: Do not estimate an extra standard deviation for the pre-recruit survey index. This means the pre-recruit survey cannot be down-weighted to allow for better fitting of other data sources.

-   Francis Ages X10: Upweight all age composition samples 10x relative to the weight assumed in the base model

-   Francis Length Weights X10: Upweight all length composition samples 10x relative to the weight assumed in the base model

The choice of data weighting algorithm and the extra standard deviation on the survey index were not influential (Table \@ref(tab:weight-sens), Figures \@ref(fig:weight-ssb-compare) and \@ref(fig:weight-bratio-compare)). Data weights for the McAllister-Iannelli method compared to those used in the base model indicate the McAllister-Iannelli weights the composition data less relative to the Francis method (Table \@ref(tab:dw-compare)). Eliminating the survey extra standard deviation did result in a larger survey index negative log-likelihood (worse fit), supporting the choice of its estimation. Increasing the weight of the age data led to a lower population scale (outside of the 95% confidence interval of the base model), similar depletion in 2023, and a trajectory where the population begins declining after fishing effort increases following the lifting of the overfished designation. Increasing the weight of length composition data essentially does the opposite, increasing the unfished biomass and 2023 depletion (both outside of base model 95% confidence interval), and leading to a steep and rapid recovery of the population in recent years. While age and length composition likelihoods are not comparable among these scenarios, the survey index negative log-likelihood increases both when upweighting lengths and when upweighting ages, indicating worse fits to survey indices in both cases. Upweighting the length and age data by a factor of ten is not meant to be realistic scenarios, but rather to illustrate how different data sources influence model results. All data weighting scenarios generally produced similar estimates of female natural mortality, with the model using the McAllister-Iannelli weights estimated a slightly larger value.

#### Selectivity and Catchability

There are numerous possible ways to parameterize selectivity in a stock assessment model, and its correct parameterization is generally a major source of structural uncertainty. Selectivity is of particular importance for `r spp` because it is unknown whether the absence of old females in composition data is due to a lack of availability, old females are available but experience higher natural mortality rates than their male counterparts, or some combination of the two. Catchability represents the fraction of the population that is available to a survey. It can either be estimated as a model parameter with uncertainty, or analytically calculated within the model. Because the base model mirrors catchability between the early and late triennial periods, catchability for the triennial survey had to be estimated rather than calculated analytically ("floated"). The following sensitivity models fall under selectivity and catchability:

-   No sex selectivity: Assume males and females have the same three-parameter double-normal selectivity curve (applies to all fleets)

-   Simpler blocks: Remove all selectivity blocks for California trawl, California non-trawl, California recreational, and Oregon recreational fleets because each had relatively similar selectivity curves over time. Combine the later two periods for Oregon-Washington trawl into one block (2000-2022) due to similarities in the left hand side of their selectivity curves.

-   WA NTWL asymptotic: Assume the Washington non-trawl fleet has asymptotic selectivity, applied to males and females. The base model assumes all fleets can have dome-shaped selectivity, and many do, which could lead to the presence of cryptic biomass. The Washington non-trawl fleet was deemed most likely to have asymptotic selectivity because 1) it fishes in untrawlable habitat where larger fish likely reside, 2) the average size of canary rockfish tends to increase northward along the coast, and 3) there is no nearshore component so harvest would presumably be at depths where larger individuals would be found.

-   \Gls{s-wcgbt} asymptotic: Assume the \gls{s-wcgbt} has asymptotic selectivity, applied to males and females. This sensitivity serves a similar purpose as the sensitivity assuming the Washington non-trawl fleet has asymptotic selectivity. The \gls{s-wcgbt} samples across the full range of deeper depths of canary rockfish habitat where larger individuals likely reside, as well as samples across a wide range of latitudes, and so could presumably encounter larger individuals. 

-   Float Q: Move all triennial data into the early triennial period and float Q (i.e., calculate it analytically).

-   Unmirror tri: Estimate separate selectivity for early and late triennial. Calculate two Q values analytically, one for each period.

Eliminating sex-specific selectivity was one of the most influential sensitivities tested, across all groups of sensitivity analyses (Table \@ref(tab:selec-sens), Figures \@ref(fig:sens-summary) and \@ref(fig:selec-ssb-compare)--\@ref(fig:selec-bratio-compare)). Eliminating sex-specific selectivity resulted in a higher unfished and recent biomass and higher depletion in 2023, both well outside the 95% confidence interval of the base model. The estimate of female natural mortality goes down substantially to a value even lower than the fixed value of males. Fits to age and length composition data deteriorate, as expected, and the survey negative log-likelihood also increases, indicating a worse fit to survey indices, particularly the \gls{s-wcgbt}.

Treatment of the \gls{s-tri} catchability value and including an asymptotic selectivity curve for the \gls{s-wcgbt} were not influential on model estimates, while simpler selectivity blocks, including an asymptotic selectivity curve for the Washington non-trawl fleet, and unmirroring the \gls{s-tri} were moderately influential (Table \@ref(tab:selec-sens), Figures \@ref(fig:selec-ssb-compare) and \@ref(fig:selec-bratio-compare)). The latter three scenarios resulted in higher estimates of unfished biomass. Simplifying selectivity blocking led to a more rapid recovery over the past two decades, and a 2023 depletion above the target of 40%. Unmirroring the \gls{s-tri} similarly resulted in a more rapid recovery compared to the base but leveled off in recent years and reached a 2023 depletion near the target of 40%. Assuming the Washington non-trawl fleet has asymptotic selectivity led to a depletion slightly lower to that estimated in the base model, and the population trend increased at a consistent rate in recent years, rather than leveling off as in the base model. Other than eliminating sex-specific selectivity, all sensitivities in this group led to similar estimates of female natural mortality. Simplified blocking and asymptotic fleets both increased the negative log-likelihood. Unmirroring the triennial, which is associated with estimating three additional parameters, only decreased the negative log-likelihood by 1 unit, supporting mirroring the two time periods. Fully combining the triennial and floating catchability does not have a comparable likelihood to the base model because the composition data for the late period were all assigned to the early period fleet, and therefore assigned a different Francis weight.

#### Population Productivity

The base model makes a number of structural assumptions related to population productivity. These assumptions are known to be influential and drive how quickly a population will recover from an overfished state. The following sensitivity models fall under population productivity:

-   Estimate h: Estimate steepness of the stock-recruit relationship

-   Estimate male M: Estimate male natural mortality

-   Single M: Fix female natural mortality to the median of the prior distribution, similar to males.

-   M ramp: Fix female natural mortality at young ages to the median of the prior distribution, similar to males. Assume, similar to recent assessments, natural mortality increases linearly from age 6 to 14, and estimate female natural mortality for ages 14 and higher. This ramp roughly follows the maturity curve, thus presuming that higher female natural mortality rates are associated with maturation and spawning.

-   M break 20: Similar to the M ramp scenario, but instead of a linear ramp in natural mortality between a younger and older age, assume a single break-point in natural mortality. For this scenario we assume a break-point of 20 (change starting at age 21) which is approximately the point at which the sex ratio begins to change in survey and fishery data.

Structural assumptions in the model that determine population productivity were strongly influential on derived model outputs (Table \@ref(tab:prod-sens), Figures \@ref(fig:prod-ssb-compare) and \@ref(fig:prod-bratio-compare)). The model internally estimates steepness to be 0.895. This indicates expected recruitment of the population remains high even at low spawning outputs, and led to a lower estimate of unfished biomass (within the 95% confidence interval), but a more rapid recovery in the 2000s and 2010s, leading to a depletion above the target of 40%. Female natural mortality was similar to the base model. The likelihood increased by two units despite estimating one additional parameter, indicating that the model was likely close to, but not quite at, the global optimum for this scenario.

The model internally estimated male natural mortality to be 0.0708 yr^-1^, higher than the fixed value of 0.0643 yr^-1^ (Table \@ref(tab:prod-sens), Figures \@ref(fig:prod-ssb-compare) and \@ref(fig:prod-bratio-compare)). When the model freely estimated male natural mortality, the estimate of female natural mortality also increased to 0.084 yr^-1^. This increase in natural mortality for both sexes resulted in a lower estimate of unfished biomass, but as with the estimation of steepness, a steeper increase in population size in recent years and a higher depletion in 2023 near the 40% target, though still within the base model 95% confidence interval. The negative log-likelihood decreased by only 1 unit with the flexibility of estimating an additional parameter. This decrease of less than two units supports the choice to fix male natural mortality in the base model.

Assuming that female natural mortality increases as they reach sexual maturity rather than remaining constant throughout their lives led to lower unfished biomass than the base model (within or just beyond the 95% confidence interval) and a higher depletion in 2023 (near to or above the management target; Table \@ref(tab:prod-sens), Figures \@ref(fig:prod-ssb-compare) and \@ref(fig:prod-bratio-compare)). The estimate of natural mortality for only old females as a ramp to age 14 was higher than the estimate of natural mortality for all females (0.0934 versus `r round(model$MGparmAdj[1, 'NatM_uniform_Fem_GP_1'], 4)` yr^-1^, respectively), but lower than for only old females as a break-point at age 20 (0.171 yr^-1^). The total likelihood was 2 units more for the ramp scenario and 26 units lower for the break-point scenario compared to the base model. Both scenarios estimate the same number of parameters as the base model. Together, this indicates some support within the data to differentiate between the two biological hypotheses of constant versus increasing natural mortality, conditional on the structure of selectivity. However, estimates for female natural mortality for the better fitting break-point model would suggest a longevity of 32 years based on the natural mortality prior, which is inconsistent with what is known about `r spp`.

Finally, fixing female natural mortality at the median of the prior used for males resulted in a substantially higher estimate of unfished biomass (outside the 95% confidence interval of the base model) and a much more muted recovery, leading to a lower spawning output in 2023 and a significantly lower depletion (outside the base model 95% confidence interval and below the minimum stock size threshold; Figures \@ref(fig:prod-ssb-compare) and  \@ref(fig:prod-bratio-compare)). The direction of these results is expected, as the fixed rate is 20% lower than the rate estimated in the base model, indicating a less productive population.

#### Sensitivities Not Included in Document

Using \gls{mrfss} length samples instead of those from the Deb Wilson-Vandenberg data, including lengths of released fish in California and Oregon recreational composition data, and assuming the pre-recruit survey occurs after density-dependence instead of before all had minimal impacts on model outputs. Dirichlet-multinomial data weighting, and estimating a fourth parameter of the double-normal selectivity curve for all fleets led to models that did not converge (final gradient \>0.01 for Dirichlet-multinomial, gradient \>100 for fourth selectivity parameter).

### Retrospective Analysis

A five-year retrospective was done by successively removing years of data to obtain models with ending years ranging from 2017 to 2021. The retrospective analysis shows a negative retrospective bias in that initial spawning output and recent spawning output generally decline as more years of data are removed, but changes are within the uncertainty intervals of the base model (Figure \ref{fig:retro_bio}). The largest change in scale occurs when four years of data are removed, and although the exact reason for this is unknown this peel is the first to miss the high value in the \gls{s-wcgbt} index and ends in the year with the lowest recruitment deviation from the base model. The magnitude of change in initial and recent spawning output is generally comparable across all peels, although recent spawning output declines slightly more for each peel and leads to slightly lower estimates of spawning output relative to unfished (Figure \ref{fig:retro_relbio}). Estimates of Mohn's $\rho$ [@mohn_rho_1999], which measures the magnitude of retrospective bias, are -0.42 over all years (average of -0.084 per year) for spawning output and -0.23 over all years (average of -0.046 per year) for spawning output relative to unfished. According to @hurtado-ferro_looking_2015, Mohn's $\rho$ values on a per-year basis of less than -0.15 are not cause for concern, but should not be taken as lack of true bias.

### Likelihood Profiles

We use likelihood profiles to assess the support of the data for the estimation of different key parameters (steepness, average unfished recruitment, and female and male natural mortality rates). A likelihood profile over a parameter fixes that parameter to a range of values, and then freely estimates the rest of the base model at each fixed value. We separate the likelihood profile into contributions from different data sources to assess the degree to which different data sources agree or conflict.

Low values of ln(R~0~) maximize the age composition likelihood, the recruitment penalties are minimized by slightly higher values of ln(R~0~) than the full model estimates, and the indices support a value of ln(R~0~) close to the full model estimate (Figures \ref{fig:r0-profile}, \ref{fig:r0-profile2}). The Oregon recreational fleet most strongly drives the age composition likelihood, but age composition data from many fleets support lower population scales. The length composition data are relatively uninformative in determining population scale. The survey index likelihood is mainly informed by the early and late triennial indices, which show the most contrast over their survey period.

The likelihood profile over steepness indicates that a value higher than that fixed in the model, around 0.9, maximizes the full likelihood (Figures \ref{fig:h-profile}, \ref{fig:h-profile2}). This is similar to the internally estimated value of steepness (0.895) found in section \@ref(population-productivity). We do not consider that to be plausible for a long-lived species such as `r spp` and therefore fix steepness at the mean of the prior distribution for rockfishes ($h=0.72$). The profile is most strongly informed by recruitment penalties and age data. There is some conflict between length data, which favor low steepness, and age data, which favor high steepness. There is some conflict among fleets in the length data, with some fleets supporting higher steepness and other fleets supporting lower steepness. The survey index favors steepness relatively close to the fixed value, around 0.7, and this is mainly informed by the triennial surveys.

The female natural mortality likelihood profile is most strongly driven by length data, with some influence of age data and recruitment penalties (Figures \ref{fig:female-m-profile}, \ref{fig:female-m-profile2}). Survey indices contain little information to inform female natural mortality estimation. The length composition data shows a conflict between trawl gears supporting natural mortality close to the estimate, Washington non-trawl and recreational fleets supporting lower values, and the Oregon recreational fleet supporting higher values. 

The likelihood profile over male natural mortality shows relatively little information from the data to support its estimation, confirming the choice to fix it to the median of the prior distribution (Figures \ref{fig:male-m-profile}, \ref{fig:male-m-profile2}). The profile is minimized at a similar value (around 0.070 yr^-1^) to the sensitivity that estimates male natural mortality (Section \@ref(population-productivity)) and slightly higher than the fixed value in the base model of 0.0643. Unlike females, recruitment penalties are most influential on the male natural mortality profile. There is a conflict between age data, which supports lower natural mortality values, and length data, which supports higher values. Similar to females, survey indices contain very little information to estimate male natural mortality.

### Comparison of Base Model to Previous Assessments

We plot summary biomass and recruitment from eight past benchmark and update assessments conducted for canary rockfish, starting in 1994, and compare to current estimates (Figure \ref{fig:hist_compare}). Summary biomass is used because fecundity relationships have changed over time between biomass and egg production. Summary biomass has most often been modeled as biomass of age 5 and above `r spp`, with the exception of the 2002 assessment, which used age 3 and above. A metric of summary biomass was not readily obtainable for the 1999 assessment, so is excluded from the figure. The plot of summary biomass indicates that the equilibrium scale of the current base model is very similar to that of the last three assessment models, and is lower than other assessment models. Summary biomass around 1990 is similar for all models produced from 1999 onward. The current base model indicates a slower rate of increase than either the 2007 or 2015 assessment models, and faster rate of increase since 1990 than the other assessment models. Age-0 recruits are estimated to be slightly higher for the current base model compared to the 2015 assessment model and similar to the 2009/2011 update assessments. Recruitment in recent years for the current base model is similar in scale and general pattern to past assessments, although the individual trajectories are variable.

### Comparison with Similar Stocks and Species

The recent assessment for canary rockfish in Canada shows a similar decline and subsequent rebuilding of the stock in Canadian waters, where the magnitude of decline and the timing of the commencement of rebuilding are generally similar to the current assessment [@dfo2023canary]. The Canadian assessment was a catch-at-age model and included six fishery-independent trawl survey series and a bottom trawl CPUE series. It internally estimated constant male and female natural mortality at 0.065 and 0.093 yr^-1^, respectively, while assuming asymptotic selectivity curves. The male natural mortality is similar to this assessment, while the female rate is higher. The model penalized recruitment variability much less ($\sigma_R = 0.9$), and estimated stock-recruit steepness. Recruitment in the Canadian assessment showed a long-term increasing trend, unlike the long-term decreasing trend estimated in this assessment. This may be because the Canadian assessment assumed selectivity remained constant over time. Detrended recruitment deviations show a minor correspondence between the U.S. and Canada models (Figure \@ref(fig:canada-rec), correlation = 0.23, two-sided 95% confidence interval -0.01- 0.45). This indicates uncertainty in estimates of year-class strength between the two models. The Alaska assessment is based upon density estimates of yelloweye rockfish from crewed or remotely operated vehicles, as well as the \gls{iphc} long-line survey, and therefore contains no information for canary rockfish [@joy2022assessment].

### Unresolved Problems and Major Uncertainties

The major uncertainty in this assessment is treatment of natural mortality. This issue has been a long-standing uncertainty for `r spp` assessments, and remains so. This uncertainty arises from observations in survey and fishery data that age-based sex-ratios are male skewed starting around age 20. This could be explained by females being less susceptible to capture, or to fewer females in the population, or to some combination of both. No refugia for old females has been found thus far suggesting mortality may be a more probable culprit, however sex ratios within Oregon fishery data have been nearer to equal in the last decade. Regardless, there is uncertainty on how best to model this dynamic. 

The choice of how to model natural mortality matters. Assuming fixed sex-specific age-invariant natural mortality results in a more pessimistic outlook because natural mortality for females is fixed at the lower prior (0.0643) value. If natural mortality is age-dependent, female natural mortality is estimated to be higher at older ages, and the magnitude of the value increases with the age at which the break in natural mortality occurs. A higher natural mortality estimate results in a more optimistic population estimate that increases dramatically from low abundance in the 2000s. Modeling selectivity as sex-dependent, as in the base model, reflects a middle ground in the estimate of natural mortality, in that age-invariant estimates between males and females differ by 20 percent (with females higher), while avoiding the less common biological assumption that natural mortality increases with age. However, applying sex-dependent selectivity results in larger females having greater selectivity values than males, which would seem to be opposite to historical treatments for explaining the male-skewed sex ratio due to older females being less susceptible to capture. Assuming no no sex-dependent selectivity results in a worse fitting model, and also has a different population outlook in that natural mortality for females is estimated lower than the prior estimate (0.055) while high recruitment in recent years results in a greater population increase than would be expected under such a low natural mortality estimate under average recruitment deviations.   

A challenge with the current base model is that it is highly parameterized with many correlations between parameters above 0.8, including some parameters with correlations as high as 0.97. Earlier versions of the model also suggested flat likelihood surfaces. Although the current base model is more stable due to simplifications of the Washington recreational and Oregon non-trawl selectivity blocks, the number of selectivity parameters and correlations among them indicate additional simplification may be warranted. Simplifying the number of selectivity parameters by reducing the number of time-varying blocks degrades model fit by a large degree and does not appear to be a solution for reducing model complexity. Modeling selectivity as a three parameter double-normal reduces correlation in parameters compared to a four parameter formulation, however modeling sex-dependent selectivity reintroduces a fourth selectivity parameter. Alternative forms for modeling selectivity and continued explorations into ways to model processes that lead to high male sex ratios in older ages may help reduce parameter correlations, and limit concerns about potential over-parameterization.
