# Acknowledgments

Many people were instrumental in the successful completion of this assessment and their contribution is greatly appreciated. We gratefully acknowledge substantial input and helpful review from the STAR panel: John Field (chair), Kristin Marshall, Joe Powers, and Martin Cryer. We are very grateful to all agers past and present at \gls{wdfw}, \gls{odfw}, and the CAPS lab, and to Patrick McDonald and Betty Kamikawa in particular for their hard work reading numerous otoliths and availability to answer questions when needed. We thank Tanya Rogers and John Field for processing data and developing the index for the pre-recruit survey, Kelli Johnson for providing extensive analyses and development of the indices of abundance for all assessments this cycle, John Wallace for pre-processing data from the Pikitch historical discard study and answering questions about it, Vanessa Tuttle for assistance in providing and understanding data from the at-sea hake fishery, and Kayleigh Somers for providing data from \gls{wcgop}. We would also like to acknowledge Brenda Erwin and Jason Edwards for helping understand the available data from \gls{pacfin} and \gls{recfin} and resolving questions and issues about its interpretation and use. We wish to thank Kristen Hinton, who was incredibly helpful in providing extensive assistance with providing Washington commercial and recreational data and answering questions about their interpretation. Members of the \gls{nwfsc} stock assessment program and assessors at \gls{swfsc}, and in particular, Owen Hamel, Ian Taylor, Jason Cope, and E.J. Dick were instrumental in helping to identify and navigate important issues during model design and interpretation. We also thank Chantel Wetzel, Kelli Johnson, and Ian Taylor for providing extensive help in understanding the various data software packages available for data processing, model interpretation, and report writing. We appreciate the contributions of the numerous individuals who took the time to participate in the pre-assessment data webinar. Finally, an assessment is only as good as the data it contains, and this assessment would not have been possible without the hundreds of port samplers, fishery observers, survey staff, and survey volunteers who have collected data on canary rockfish over the decades. 