\clearpage
\floatplacement{table}{H}

# Tables

<!-- ======================================================= -->
<!-- ********  Catch tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/canary_total_removals.csv')) |> 
  dplyr::select(Year,
                 TWL.C, TWL.O, TWL.W,
                 NTWL.C, NTWL.O, NTWL.W,
                 rec.C, rec.O, rec.W.mt.2) |>
  knitr::kable(caption = 'Total removals (mt) of canary rockfish for the trawl (TWL), non-trawl (NTWL), and recreational (REC) fleets used in the assessment model. See text for description of sources',
               label = 'catches1', 
               format = 'latex',
               col.names = c("Year", 
                             "TWL CA", "TWL OR", "TWL WA",
                             "NTWL CA", "NTWL OR", "NTWL WA",
                             "Rec CA", "Rec OR", "Rec WA"),
               booktabs = TRUE,
               longtable = TRUE,
               linesep = "",
               digits = 1) |>
  kableExtra::kable_styling(
      latex_options = c("repeat_header"),
      font_size = 9)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/canary_total_removals.csv')) |> 
  dplyr::select(Year,
                 FOR.C, FOR.O, FOR.W,
                 ASHOP.C, ASHOP.O, ASHOP.W) |>
  dplyr::filter(Year > 1965) |>
  knitr::kable(caption = 'Total removals (mt) of canary rockfish for the foreign (FOR) and at-sea hake (ASHOP) fleets used in the assessment model. Removals before 1966 are zero. See text for description of sources',
               label = 'catches2', 
               format = 'latex',
               col.names = c("Year",
                             "FOR CA", "FOR OR", "FOR WA",
                             "ASHOP CA", "ASHOP OR", "ASHOP WA"),
               booktabs = TRUE,
               longtable = TRUE,
               digits = 1)
```

\newpage

<!-- ======================================================= -->
<!-- ********  ACL tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/ACL_history.csv')) |>
  knitr::kable(caption = 'The OFL, ABC, ACL, and total mortality (landings + dead discards) in metric tons',
               label = 'acls', 
               format = 'latex',
               booktabs = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Commercial sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results = 'asis', message=FALSE}
readr::read_csv(here('documents/tables/pacfin_lengths.csv')) |>
  dplyr::select(Year, 
         Trips_TWL.C, Lengths_TWL.C, Trips_TWL.O, Lengths_TWL.O, Trips_TWL.W, Lengths_TWL.W, 
         Trips_NTWL.C, Lengths_NTWL.C, Trips_NTWL.O, Lengths_NTWL.O, Trips_NTWL.W, Lengths_NTWL.W) |>
  as.data.frame() |>
  sa4ss::table_format(caption = "Summary of the number of length samples and trips for commercial trawl (TWL) and non-trawl (NTWL) fleets for California (CA), Oregon (OR), and Washington (WA)",
                      label = "comm-sample-lengths",
                      align = 'l',
                      col.names = c("Year",
                            "Trips TWL CA", "Lengths TWL CA", 
                            "Trips TWL OR", "Lengths TWL OR", 
                            "Trips TWL WA", "Lengths TWL WA",
                            "Trips NTWL CA", "Lengths NTWL CA", 
                            "Trips NTWL OR", "Lengths NTWL OR", 
                             "Trips NTWL WA", "Lengths TWL WA"),
                      longtable = TRUE,
                      landscape = FALSE)
```

\newpage

```{r, results = 'asis', message=FALSE}
readr::read_csv(here('documents/tables/pacfin_ages_fixAges.csv')) |>
  dplyr::select(Year, 
         Trips_TWL.C, Ages_TWL.C, Trips_TWL.O, Ages_TWL.O, Trips_TWL.W, Ages_TWL.W,
         Trips_NTWL.C, Ages_NTWL.C, Trips_NTWL.O, Ages_NTWL.O, Trips_NTWL.W, Ages_NTWL.W) |>
  as.data.frame() |>
  sa4ss::table_format(caption = "Summary of the number of aged samples and trips for commercial trawl (TWL) and non-trawl (NTWL) fleets for California (CA), Oregon (OR), and Washington (WA)",
                      label = "comm-sample-age",
                      align = 'l',
                      col.names = c("Year",
                            "Trips TWL CA", "Ages TWL CA", 
                            "Trips TWL OR", "Ages TWL OR", 
                            "Trips TWL WA", "Ages TWL WA", 
                            "Trips NTWL CA", "Ages NTWL CA", 
                            "Trips NTWL OR", "Ages NTWL OR", 
                            "Trips NTWL WA", "Ages NTWL WA"),
                      longtable = TRUE,
                      landscape = FALSE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  ASHOP sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/Canary_ashop_LengthComps_hauls_and_samples.csv')) |> 
  dplyr::select(Year, OR_nhaul, OR_N, WA_nhaul, WA_N) |>
  knitr::kable(caption = 'Summary of the number of hauls and length samples for the at-sea hake fleets for Oregon (OR), and Washington (WA). No samples were collected in California',
               label = 'ashop-sample-lengths', 
               format = 'latex',
               col.names = c("Year", "Hauls OR", "Lengths OR", "Hauls WA", "Lengths WA"),
               booktabs = TRUE)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('data/Canary_ashop_AgeComps_hauls_and_samples.csv')) |>
  dplyr::select(Year, OR_nhaul, OR_N, WA_nhaul, WA_N) |>
  knitr::kable(caption = 'Summary of the number of trips and aged samples for the at-sea hake fleets for Oregon (OR), and Washington (WA). No samples were collected in California',
               label = 'ashop-sample-age', 
               format = 'latex',
               col.names = c("Year", "Hauls OR", "Ages OR", "Hauls WA", "Ages WA"),
               booktabs = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Recreational sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/rec_lengths.csv')) |>
  dplyr::select(year, N_CA, ntrip_CA, N_OR, ntrip_OR, N_WA, ntrip_WA) |>
  knitr::kable(caption = 'Summary of the number of length samples and trips for recreational fleets for California (CA), Oregon (OR), and Washington (WA)',
               label = 'rec-sample-lengths', 
               format = 'latex',
               col.names = c("Year", "Lengths CA", "Trips CA", "Lengths OR", "Trips OR", "Lengths WA", "Trips WA"),
               booktabs = TRUE,
               longtable = TRUE)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/rec_ages.csv')) |>
  dplyr::select(year, O_or_ora_N, O_or_ora_ntrip, W_wa_sport_N, W_wa_sport_ntrip) |>
  knitr::kable(caption = 'Summary of the number of aged samples and trips for recreational fleets for Oregon (OR), and Washington (WA). No aged samples are available for the California recreational fleet',
               label = 'rec-sample-age', 
               format = 'latex',
               col.names = c("Year", "Ages OR", "Trips OR", "Ages WA", "Trips WA"),
               booktabs = TRUE,
               longtable = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Survey sample size tables *************** --> 
<!-- ======================================================= -->

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/wcgbts_summary.csv')) |>
  knitr::kable(caption = 'Summary of canary rockfish samples in the West Coast Groundfish Bottomtrawl Survey (WCGBTS)',
               label = 'wcgbts', 
               format = 'latex',
               booktabs = TRUE)
```

\newpage

```{r, results='asis', message=FALSE}
readr::read_csv(here('documents/tables/triennial_summary.csv')) |>
  knitr::kable(caption = 'Summary of canary rockfish samples in the Triennial Shelf Survey (Triennial)',
               label = 'triennial', 
               format = 'latex',
               booktabs = TRUE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Model results *************** --> 
<!-- ======================================================= -->


```{r, results = 'asis', message=FALSE}
options(knitr.kable.NA = NA)
parm_table <- readr::read_csv(here('documents/tables/parameters.csv')) |>
  as.data.frame()
parm_table[parm_table$Parameter == "Wtlen 1 Fem GP 1","Value"] = format(parm_table[parm_table$Parameter == "Wtlen 1 Fem GP 1","Value"], scientific = TRUE)
parm_table[parm_table$Parameter == "Wtlen 1 Mal GP 1","Value"] = format(parm_table[parm_table$Parameter == "Wtlen 1 Mal GP 1","Value"], scientific = TRUE)
parm_table[parm_table$Parameter == "Eggs scalar Fem GP 1","Value"] = format(parm_table[parm_table$Parameter == "Eggs scalar Fem GP 1","Value"], scientific = TRUE)

sa4ss::table_format(parm_table, caption = "List of parameters used in the base model, including estimated values and standard deviations (SD), bounds (minimum and maximum), estimation phase (negative values not estimated), status (indicates if parameters are near bounds), and prior type information (mean and SD).",
                      label = "params",
                      align = 'l',
                      # col_names = col_names,
                      longtable = TRUE,
                      font_size = 9,
                      digits = 3,
                      landscape = TRUE,
                      custom_width = TRUE,
                      col_to_adjust = c(1,7),
                      width = c("7.5cm", "3.5cm")
                      )
```


\newpage

```{r like, results='asis', message=FALSE}
readr::read_csv(file.path(model_dir, "tables", "likelihoods.csv")) |>
  knitr::kable(caption = 'Likelihood components by source',
               label = 'like',
               format = 'latex',
               col.names = c("Data type", "Total"),
               booktabs = TRUE,
               escape = TRUE,
               digits = 2)
```

\newpage

```{r tables-weights, results = "asis"}
source(here('code/table_compweight.R'))
table_compweight(model,
  caption_extra = paste("The WCGBTS age comps are conditioned on length,",
   "so there are more observations with fewer samples per observation."),
   label = "data-weights") |>
  kableExtra::kable_styling(font_size = 10)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Timeseries *************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
timeseries = read.csv(file.path(model_dir, "tables", "TimeSeries.csv"))
col_names = c("Year", "Total Biomass (mt)", "Spawning Output", "Total Biomass 5+ (mt)", "Fraction Unfished", "Age-0 Recruits", "Total Mortality (mt)", "1-SPR", "Exploitation Rate")

table_format(x = round(timeseries,2),
                 caption = "Time series of population estimates from the base model. Spawning output is in millions of eggs and age-0 recruits is in numbers of 1000s. Total mortality for 2023 and 2024 is based on projected estimates provided by the Groundfish Management Team.",
                 label = "timeseries",
                 longtable = TRUE,
                 col_names = col_names,
                 row.names = FALSE)
```

\newpage

<!-- ======================================================= -->
<!-- ********  Sensitivities *************** --> 
<!-- ======================================================= -->
```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/data_table.csv')) |>
  dplyr::mutate(dplyr::across(-...1, ~ sapply(., format, digits = 3, scientific = FALSE))) |>
  dplyr::rename(` ` = '...1') |>
  # knitr::kable(caption = 'Estimates of likelihood components and major model parameters for data sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, not all likelihoods are comparable.',
  #              label = 'data-sens',
  #              format = 'latex',
  #              booktabs = TRUE) |>
  # kableExtra::landscape()
  table_format(caption = 'Estimates of likelihood components and major model parameters for data sensitivities. Likelihood is negative log-likelihood, where a lower value would indicate better fit to data. However, because of differences in input data for these sensitivities, likelihoods are generally uncomparable among scenarios.',
             label = "data-sens",
             row.names = FALSE,
             landscape = TRUE,
             custom_width = TRUE,
             align = "l",
             col_to_adjust = c(2,3,4,5,6,7),
             width = c("1.27cm", "1.676cm", "1.676cm", "1.27cm", "1.27cm", "1.905cm"))
```

```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/weighting_table.csv')) |>
  dplyr::mutate(dplyr::across(-...1, ~ sapply(., format, digits = 3, scientific = FALSE))) |>
  dplyr::rename(` ` = '...1') |>
  knitr::kable(caption = 'Estimates of likelihood components and major model parameters for data weighting sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, likelihoods are only comparable between the base model and the `No extra SD` model.',
               label = 'weight-sens',
               format = 'latex',
               booktabs = TRUE) |>
  kableExtra::landscape()
```

```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/selectivity_table.csv')) |>
  dplyr::mutate(dplyr::across(-...1, ~ sapply(., format, digits = 3, scientific = FALSE))) |>
  dplyr::rename(` ` = '...1') |>
  # knitr::kable(caption = 'Estimates of likelihood components and major model parameters for selectivity sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, likelihoods for the `Float Q` model are not comparable.',
  #              label = 'selec-sens',
  #              format = 'latex',
  #              booktabs = TRUE) |>
  # kableExtra::landscape()
  table_format(caption = 'Estimates of likelihood components and major model parameters for selectivity sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data. Because of differences in input data, likelihoods for the `Float Q` model are not comparable.',
             label = "selec-sens",
             row.names = FALSE,
             landscape = TRUE,
             custom_width = TRUE,
             align = "l",
             col_to_adjust = c(3,4,5,6),
             width = c("1.27cm", "1.27cm", "1.905cm", "1.905cm"))
```

```{r, results = 'asis'}
readr::read_csv(here('documents/figures/sensitivities/productivity_table.csv')) |>
  dplyr::mutate(dplyr::across(-...1, ~ sapply(., format, digits = 3, scientific = FALSE))) |>
  dplyr::rename(` ` = '...1') |>
  knitr::kable(caption = 'Estimates of likelihood components and major model parameters for productivity sensitivities. Likelihood is negative log-likelihood, where lower values indicate better fit to data.',
               label = 'prod-sens',
               format = 'latex',
               booktabs = TRUE) |>
  kableExtra::landscape()
```

```{r, results = 'asis'}
readr::read_csv(here('documents','tables','data-weight-compare.csv')) |>
  knitr::kable(caption = "Data weightings applied to length and age compositions according to the `Francis` and `McAlister Ianelli` (MI) methods. `CAAL` is conditional age-at-length data.",
               label = 'dw-compare',
               format = 'latex',
               booktabs = TRUE)
```


<!-- ======================================================= -->
<!-- ********  Reference points *************** --> 
<!-- ======================================================= -->

<!-- ```{r, results = 'asis'} -->
<!-- readr::read_csv(here('documents/tables/ref_points.csv')) |> -->
<!--   knitr::kable(caption = 'Various reference points for three different management targets', -->
<!--                label = 'ref-pts', -->
<!--                format = 'latex', -->
<!--                booktabs = TRUE, -->
<!--                escape = FALSE) -->
<!-- ``` -->

<!-- Update with larger reference point table -->
```{r, results = 'asis'}
options(knitr.kable.NA = '')
readr::read_csv(file.path(model_dir, "tables", "e_ReferencePoints_ES.csv")) |>
  knitr::kable(caption = 'Summary of reference points and management quantities, including estimates of 95 percent intervals',
               label = 'ref-pts',
               format = 'latex',
               col.names = c("Category", "Estimate", "Lower Interval", "Upper Interval"),
               digits = 2,
               booktabs = TRUE,
               escape = FALSE)
```


<!-- ======================================================= -->
<!-- ******** Projection and Decision Tables *************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
#options(knitr.kable.NA = '')
readr::read_csv(here('documents','tables','projections.csv'), na = "-") |>
  data.frame() |>
  table_format(caption = "Projections of estimated OFL (mt), ABC (mt), resulting ACLs (mt) based on 40-10 rule and applied buffers, and estimated spawning output in millions of eggs, and spawning output relative to unfished for 2025-2034, with assumed removals in 2023 and 2024 based on recommended values from the Groundfish Management Team.",
             label = "project",
             row.names = FALSE,
             col_names = c('Year', 'Adopted OFL (mt)', 'Adopted ABC (mt)', 'Adopted ACL (mt)', "Assumed removals (mt)", "OFL (mt)", "Buffer", "ABC", "ACL", "Spawning Output", "Fraction Unfished"),
             landscape = TRUE,
             custom_width = TRUE,
             align = "l",
             col_to_adjust = c(2,3,4,5,10,11),
             width = c("1.27cm", "1.27cm", "1.27cm", "1.676cm", "1.676cm", "1.676cm"))
```

\clearpage

\input{../tables/decision_table.tex}